### ISSUE TITLE
Using `--changelog` regenerates the full changelog instead of just the current increment

### ISSUE THREAD

**Issue by edgarrmondragon** [commitizen-tools/commitizen#1024]
### Description

Starting with [v3.18.1](https://github.com/commitizen-tools/commitizen/releases/tag/v3.18.1), using `--changelog` generates the full catalog instead of only prepending the changes for the current increment.

This can be seen even in the GitHub release notes of commitizen itself starting with `v3.18.2`: they now include the full changelog.

### Steps to reproduce

For example:

```
cz --no-raise 21 bump --yes --changelog --files-only --check-consistency --changelog-to-stdout >_changelog_fragment.md
```

### Current behavior

The full changelog is regenerated instead of just the current increment.

### Desired behavior

Only generate the current increment section of the changelog.

### Screenshots

<img width="1159" alt="Screenshot 2024-03-13 at 2 06 46 p m" src="https://github.com/commitizen-tools/commitizen/assets/16805946/0dda4abf-dcbb-42a3-9ea6-16aaf73b4b02">

### Environment

- commitizen version: `3.18.3`
- python version: `Python 3.12.2`
- operating system: `Darwin`

**Comment by woile** [comment]
Good point, thanks for raising the issue, we'll take a look tomorrow. @noirbizarre any thoughts what could've been the issue? Thanks

**Comment by woile** [comment]
A WIP is on its way, awaiting for @noirbizarre

**Comment by noirbizarre** [comment]
Yes, sorry I noticed that.
I think I will revert the change (tomorrow) and provide a more robust approach.
In fact we have a design flaw to fix: the way we are handling `--changelog-to-stdout` on the `bump` command we can't have both dry-run, incremental and changelog_hook at the same time

**Comment by woile** [comment]
I made a PR: #1026 I think to patch this issue it works, but fill free to send more commits to that PR

**Comment by woile** [comment]
Please confirm if it's working now, 🙏🏻

**Comment by edgarrmondragon** [comment]
> Please confirm if it's working now, 🙏🏻

@woile I can confirm only the increment is generated when using 3.18.4 🎉
