### ISSUE TITLE
Generated pre-release part of SemVer differs from SemVer spec

### ISSUE THREAD

**Issue by Xiangze-Li** [commitizen-tools/commitizen#1025]
### Description

When using SemVer schema and bumping to pre-release version, the version generated is like `1.0.0-a0`.

This differs from examples from [SemVer spec 9](https://semver.org/#spec-item-9), which is `1.0.0-alpha.0`, using "alpha" instead of "a", and having a dot between "a" and the sequential number.

Current behavior may break the version comparison when the number has more than 1 digits. 
For example, `1.0.0-a10` is less than `1.0.0-a2` according to [spec 11](https://semver.org/#spec-item-11), because `a10` is less than `a2` lexically.  

### Steps to reproduce

1. Setup commitizen using SemVer schema
2. Run `cz bump --pr alpha`

### Current behavior

Bumped into `x.y.z-a0`

### Desired behavior

Bumped into `x.y.z-a.0` or `x.y.z-alpha.0`

### Environment

Commitizen Version: 3.18.3
Python Version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Operating System: Linux

**Comment by woile** [comment]
Did you configure the version scheme?
https://commitizen-tools.github.io/commitizen/bump/#version_scheme

**Comment by Xiangze-Li** [comment]
> Did you configure the version scheme? https://commitizen-tools.github.io/commitizen/bump/#version_scheme

I set this field (when initializing) in `.cz.toml` as `version_scheme = "semver"`.

Actual behavior is exactly same with what stated in the linked manual, which disagrees with SemVer spec.

**Comment by Xiangze-Li** [comment]
I just realized this behavior is OK under [SemVer 1.0.0](https://semver.org/spec/v1.0.0.html#spec-item-4). 

Maybe it's nice to seperate the two SemVer more clearly?

**Comment by woile** [comment]
What do you mean the two semver?

**Comment by Xiangze-Li** [comment]
> What do you mean the two semver?

SemVer has two major versions now. Version 2 has changed the spec of the pre-release part.

**Comment by woile** [comment]
mm we may need a new version scheme: `semver_v2`
Thoughts on this @Lee-W @noirbizarre ?

**Comment by krumlo** [comment]
Second this, I'd really enjoy semver 2.0 support!

**Comment by noirbizarre** [comment]
Hum, makes sense.
I need to review quickly differences with v1, but it should be easy with the versioon providers

**Comment by noirbizarre** [comment]
There it is, implemented in #1072.

Note that SemVer2 is underspecified on the `prerelease` part (I include development releases as the concept does not exist in SemVer2) and some choices has been made, staying close to the examples (only example are using `alpha`, `beta`), the specification itself is just about the format and the precedence rules, it does not specify the standard parts (`alpha`, `beta`, dev`... which might also be `a`, `b` end `dev`). 

(This point is one of the reason than Python community dropped SemVer for PEP440)

**Comment by Xiangze-Li** [comment]
Many thanks!

**Comment by krumlo** [comment]
@noirbizarre very quick feedback, thanks a bunch!!
