### ISSUE TITLE
Provider for conan package manager versioning

### ISSUE THREAD

**Issue by rols121** [commitizen-tools/commitizen#1094]
### Description

A provider for the [conan C++ package manager](https://conan.io/) would be great.

### Possible Solution

I had already forked the commitizen repo and started working on this before I read the contributing section docs. I have attached a patch for a proposed solution which includes tests for the provider.
[conanfile_provider.patch](https://github.com/commitizen-tools/commitizen/files/15209711/conanfile_provider.patch)

A simple
```bash
git apply conan_provider.patch
```
In the root of the commitizen repo should apply the patch (Hopefully if master has not moved on).

Conan has recently moved to version 2. Version 1 is on a deprecation path, but people and organisations are still using version 1. The version of the project in both versions is in a conanfile.py which can be in the root of the project directory. The proposed patch 

### Additional context

![image](https://github.com/commitizen-tools/commitizen/assets/16399703/740e0b22-be51-4571-81cc-cee97135d8b7)

**Comment by Lee-W** [comment]
Due to maintenance efforts, we tend to get rid of pluggable stuff from the core if possible. Please feel free to create your conan provider plugin and publish it. We would be happy to mention it in our document.
