### ISSUE TITLE
option `ci` reads `Changes to our CI configuration`, possibly an error

### ISSUE THREAD

**Issue by nbehrnd** [commitizen-tools/commitizen#1095]
### Description

I think the instruction about option `ci` as one of the options to commit an edit can be improved.

### Steps to reproduce

1. edit a git managed project, e.g. in a file `test.txt`
2. pick up the file in question by `git add test.txt`
3. run `cz c`, option `ci`

### Current behavior

The description currently reads as 

```
ci: Changes to our CI configuration files and scripts (example scopes: GitLabCI)
```

### Desired behavior

I think it however should read as

```
ci: Changes to your CI configuration files and scripts (example scopes: GitLabCI)
```

instead

### Environment

- commitizen (commitizen-3.25.0-py3-none-any.whl.metadata) as fetched by `pip` (version 24.0) from PyPI
- Python 3.11.8 as provided by Linux Debian 13/trixie

**Comment by nbehrnd** [comment]
Initially filed in as a discussion (#1036) by 2024-03-22 about then version 3.20.0 of commitizen.  So far (till today, 2024-05-04), the entry however did not receive a comment.

**Comment by woile** [comment]
Yeah, it depends on the perspective of how you read it, I don't mind changing it to `your`, feel free to open a PR 👍🏻

**Comment by Lee-W** [comment]
Closed by https://github.com/commitizen-tools/commitizen/pull/1107
