### ISSUE TITLE
Add RyeProvider to version providers.

### ISSUE THREAD

**Issue by tabassco** [commitizen-tools/commitizen#1102]
### Description

I'd like to support Rye (https://rye-up.com) to provide versioning.
It should be a simple addition as it utilizes the same pyproject.toml as poetry, etc.

I'll gladly implement this.

### Possible Solution

Add RyeProvider class in providers module

**Comment by Lee-W** [comment]
Hi @tabassco , thanks for creating this issue. But we'd like to avoid adding new providers to the core. We'd encourage to create your own provider plugin and we'll be more than happy to mention your plugin in https://commitizen-tools.github.io/commitizen/third-party-commitizen/#installation_3. (This page should probably be updated a bit, though 🤔 )

**Comment by woile** [comment]
If my memory serves me well, rye uses the default parameters from `[project]`, so the `pep621` should work with `rye` for version management.
https://commitizen-tools.github.io/commitizen/config/#version-providers

**Comment by Lee-W** [comment]
@woile Looks like some of the detail is still different 🤔 https://github.com/commitizen-tools/commitizen/pull/1103/files

**Comment by woile** [comment]
I haven't found any `rye` repo using that configuration, even the default template from rye uses `version` from the `[project]`: 
https://github.com/astral-sh/rye/blob/main/rye/src/templates/pyproject.toml.j2#L3

On top of that, running `rye version -b minor` also bumps the `[project.version]`, not the `tool.rye.version`. I think the `tool.rye.version` points to the actual version of `rye` that you expect in the project (I couldn't find any docs about it though)
