### ISSUE TITLE
Use of version_provider doesn't add changed files on cz bump

### ISSUE THREAD

**Issue by kassi** [commitizen-tools/commitizen#1108]
### Description

When using a custom version provider that changes some arbitrary file defined in the version provider itself, this file is not added to git on a `cz bump`.
Only files defined within `version_files` are added. However having to specify the file that is being changed within the version provider also inside `version_files` may lead to problems.

### Steps to reproduce

- Specify a version provider, e.g. `commitizen_lrplugin` or `commitizen_ruby` (without specifying the actual version file in `version_files`
- bump the version with `cz bump`
- run `git status`
- see that the version file has not been committed.

### Current behavior

The file with version number changed by the version provider is not added to the bump commit.

### Desired behavior

The file with version number changed by the version provider should be automatically added to the bump commit.

### Environment

Commitizen Version: 3.25.0
Python Version: 3.12.3 (main, Apr 16 2024, 11:43:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Operating System: Darwin

**Comment by woile** [comment]
Is the file being tracked by git? `commitizen` does `git commit -a` which should include modified files

**Comment by kassi** [comment]
@woile yes, it's tracked by git. I tested again and again and finally realized, that the file is being checked-in, but after the commit increasing the version number, some automatism updated itself in the lock file (`Gemfile.lock` in this case), raising the version number and making the repo dirty again. I'll close this issue and have to figure out what's causing this in the ruby environment.
