### ISSUE TITLE
Add option for "cz.toml" config file

### ISSUE THREAD

**Issue by marcosdotme** [commitizen-tools/commitizen#1111]
### Description

Actually we can configure the commitizen through:

_Dot_ files:
```
.cz.toml
.cz.yaml
.cz.json
```

_Non dot_ files:
```
pyproject.toml
cz.yaml
cz.json
```

Theres an reason for not having an "cz.toml" without the dot? I like that my config files be explicit and not hidded. Can I open an PR to add this support? Seems easy to do.

### Possible Solution

Include "cz.toml" on `commitizen.defaults.config_files`:

```diff
# commitizen.defaults.py

config_files: list[str] = [
    "pyproject.toml",
    ".cz.toml",
    ".cz.json",
    "cz.json",
    ".cz.yaml",
    "cz.yaml",
+   "cz.toml"
]
```

**Comment by Lee-W** [comment]
Don't have a strong opinion on it. Either way works for me @woile @noirbizarre thoughts?

**Comment by woile** [comment]
Sounds good 👍🏻

**Comment by marcosdotme** [comment]
@Lee-W Assign this to me so I can open an PR

**Comment by Lee-W** [comment]
Sure 🙂
