### ISSUE TITLE
automate cli screenshot update in CI

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#1112]
### Description

Currently, we don't have [scripts/gen_cli_help_screenshots.py](https://github.com/commitizen-tools/commitizen/blob/3e57007bf1f882a6ed34717c68d3a265e16dcf7a/scripts/gen_cli_help_screenshots.py) to generate the cli help message for us. But this has to be done manually. It would be great if we can automate the process

This issue is a follow up to https://github.com/commitizen-tools/commitizen/pull/1086

### Possible Solution

Automate it in GitHub actions

### Additional context

This idea comes from airflow so take a look at https://github.com/apache/airflow/blob/029cbaec174b73370e7c4ef2d7ec76e7be333400/dev/breeze/src/airflow_breeze/utils/recording.py#L35 might be helpful

**Comment by marcosdotme** [comment]
@Lee-W I would love to work on this too, as it is related to my PR #1120

**Comment by Lee-W** [comment]
Sure 🙂

**Comment by marcosdotme** [comment]
@Lee-W Waiting review on #1122 🤝🏻

**Comment by Lee-W** [comment]
Closed by https://github.com/commitizen-tools/commitizen/pull/1122
