### ISSUE TITLE
missing help text when subcommand is used (e.g., `cz commit --help`)

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#1115]
### Description

When running `cz --help`, we have the help text for each subcommand (e.g., `cz commit`), but `cz commit --help` does not have the description `create new commit`

### Steps to reproduce

1. `cz --help`
2. `cz commit --help`hope

### Current behavior

missing help text in subcommandthe 

### Desired behavior

the help text should appear

### Screenshots

<img width="1714" alt="image" src="https://github.com/commitizen-tools/commitizen/assets/5144808/1e1f0f2e-39ad-4e2e-91bd-7410b50c0ff7">

### Environment

Commitizen Version: 3.24.0
Python Version: 3.12.2 (main, Apr 19 2024, 14:41:00) [Clang 15.0.0 (clang-1500.3.9.4)]
Operating System: Darwin

**Comment by marcosdotme** [comment]
@Lee-W Can I act on this?

**Comment by Lee-W** [comment]
sure! that would be awesome. assigning this to you

**Comment by marcosdotme** [comment]
@Lee-W Waiting review on #1120 🤝🏻
