### ISSUE TITLE
Skip "git push" is no screenshot is updated in job "update-cli-screenshots"

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#1138]
### Description

https://github.com/commitizen-tools/commitizen/blob/e9aa5d979ea6fd14dcf59c6bd3836bef17d386c1/.github/workflows/docspublish.yml#L28 should be skipped if nothing is updated in https://github.com/commitizen-tools/commitizen/blob/e9aa5d979ea6fd14dcf59c6bd3836bef17d386c1/.github/workflows/docspublish.yml#L27

### Steps to reproduce

1. `poetry run python scripts/gen_cli_help_screenshots.py`
2. Run git commit and git push

### Current behavior

Blocking documentation generation due to https://github.com/commitizen-tools/commitizen/blob/e9aa5d979ea6fd14dcf59c6bd3836bef17d386c1/.github/workflows/docspublish.yml#L33-L34 failure if there's no screenshot update

### Desired behavior

If no screenshot is updated, the CI should just skip the committing and pushing steps.

### Environment

Commitizen Version: 3.13.0
Python Version: 3.11.6 (main, Oct 16 2023, 12:18:37) [Clang 15.0.0 (clang-1500.0.40.1)]
Operating System: Darwin

**Comment by marcosdotme** [comment]
@Lee-W Well, since its a bug related to an feature introduced by me, can I work on it?

**Comment by Lee-W** [comment]
> @Lee-W Well, since its a bug related to an feature introduced by me, can I work on it?

Definitely 🙂 let me assign it to you
