### ISSUE TITLE
Check the commit in the whole branch/pull request

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#114]
**Goal**
Check whether all the commits in a branch/pull request are in a proper format

**Description**
In a project bumping version through commitizen, commits that do not follow the rule could break.

**Comment by Woile** [comment]
For which use cases would this feature be useful?

I don't know if a repo should have every commit following the convention. Not following the convention is the easiest way to skip being parsed into a changelog or for bumping the version, or event triggering a CI.

**Comment by Lee-W** [comment]
It's for organization to force using `commitizen`.  It's a pain point my friends encounter when applying `commitizen` to their projects. Sometimes people forget to use `commitizen,` but the changes should be properly recorded. If too many commits fails to follow the rule, the generated version and changelog won't make sense anymore.

**Comment by Woile** [comment]
Oh okay, makes sense now. My idea was for check to do this, but it's
probably checking the last commit right? Maybe it should have a flag
--branch to check up to the last tag. What do you think?

**Comment by Lee-W** [comment]
Yes, the current implementation only checks the last commit which is useful for `pre-commit`.

My idea is having a `--rev` for [revision range] in `git log`.
e.g., `cz check --rev 5f39..HEAD`
If the [revision range] is not given, the default can be `master..HEAD`.

**Comment by Woile** [comment]
okay, it makes sense :+1:

**Comment by Lee-W** [comment]
#141 Merged. Close this issue.
