### ISSUE TITLE
git cz doesn't return success status when used with the --retry flag. Causing command to hang.

### ISSUE THREAD

**Issue by ghaschel** [commitizen-tools/commitizen#1152]
### Description

When using commitizen through git (`git cz`) everything works as it should. As soon as all the cycles and tooling finishes, it ends the command. But when using with `git cz --retry` it doesn't. It happens in `Windows CMD`, `ZSH on Ubuntu WSL`, and `ZSH on Mac OS Sonoma`.

I am creating a simple repository to reproduce this issue. If by any means the issue is something other than cz, please, let me know. This is an issue I have been facing for a long time. It didn't use to happen before a version upgrade (sorry, but I won't be able to remember the version in specific)

Here is the repo: https://github.com/ghaschel/git-cz-retry-troubleshooting

### Steps to reproduce

1) Change anything and run `git add .`
2) Create the initial commit `git cz`
3) After the linting and tooling process finished change something else and run `git add .`
4) Run `git cz --retry`
5) The command will finish successfully, but it will hang. Causing any other subsequent commands to not run. (I.e.: git cz --retry && git push)

### Current behavior

`git cz --retry` doesn't return status 0 and hangs, preventing subsequent commands not to run. One must ctrl + c to end the command manually after successfully using `git cz --retry` in order to proceed.

### Desired behavior

It should return a success status code so that it doesn't get stuck. One should not need to use ctrl+c to exit the stuck command just to be able to follow through.

### Screenshots

![image](https://github.com/commitizen-tools/commitizen/assets/5878866/1401c210-c86b-49c6-9649-504263a3d3ce)

### Environment

-- @commitlint/cli version: 19.3.0
-- @commitlint/config-conventional version: 19.2.2
-- @typescript-eslint/eslint-plugin version: 7.12.0
-- @typescript-eslint/parser version: 7.12.0
-- commitizen version: 4.3.0
-- commitlint-plugin-function-rules version: 4.0.0
-- conventional-changelog-cli version: 5.0.0
-- cz-conventional-changelog version: 3.3.0
-- eslint version: 8.57.0
-- eslint-config-prettier version: 9.1.0
-- eslint-plugin-prettier version: 5.1.3
-- husky version: 9.0.11
-- lint-staged version: 15.2.5
-- prettier version: 3.3.0
-- os version: Windows 10 (cmd), Mac OS Sonoma (zsh), Ubuntu 18.04 on WSL (zsh)

**Comment by Lee-W** [comment]
Hi, I'm afraid this might not be the commitzen you're looking for 🙂  https://github.com/commitizen/cz-cli is the one implemented in JavaScript
