### ISSUE TITLE
commitizen didn't break when there is only unstaged file

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#116]
## Description

commitizen should break if there is nothing to commit.

After you modify an existing file, the file goes into unstaged. If we use `cz` at this time, it will finish all the questions and says `no changes added to commit`.
I trace back to the git command I use in [cz-cli](https://www.google.com/search?client=firefox-b-d&q=cz+cli). They changed from `git diff --cached --name-only` to `git diff --no-ext-diff --name-only && git diff --no-ext-diff --cached --name-only` on  [commit 7c4703bb](https://github.com/commitizen/cz-cli/commit/7c4703bb2afc8bbb8a910aa958a855cad2f6beb7)
It's probabaly due to the behavior change of `git-cz -a` which we do not provide.
It seems to me that using `git diff--cached --name-only` is a more reasonable option for this project at this time.

## Steps to reproduce
1. `mkdir test`
2. `cd test`
3. `git init`
4. `touch testfile`
5. `git add testfile`
6. `cz commit`
7. `echo "testtest" > testfile`
8. `cz commit`

## Current behavior
commitizen runs even after the change on step 7

## Desired behavior
commitizen should block users from making commit as there's nothing changed

## Environment

- commitizen version: 2.17.13
- python version: Python 3.8.5
- operating system: Darwin

**Comment by Lee-W** [comment]
@Woile Since we're not planning on adding things like `cz -a`, I'd like to use `git diff--cached --name-only`. Does it make sense to you?

**Comment by Lee-W** [comment]
@Woile Since we're not planning on adding things like `cz -a`, I'd like to use `git diff--cached --name-only`. Does it make sense to you?

**Comment by Woile** [comment]
> git diff --cached --name-only

I don't know what it does, can you expand what would be the idea?

We have `retry`. Why not `cz commit -a --retry`

**Comment by Lee-W** [comment]
`git diff --cached --name-only` allows us to view the changes we staged for the next commit.
btw `--no-ext-diff` disallow external diff drivers which could be added in our case.

`git cz -a` is used to add files and then commit which does not seem to be a good convention to me.

**Comment by Lee-W** [comment]
Thanks for folks in PyCon TW 2021 sprint. This issue has been solved in the latest version
