### ISSUE TITLE
Committing bumps fails on signing using GPG's tty-pinentry

### ISSUE THREAD

**Issue by shahinism** [commitizen-tools/commitizen#1184]
### Description

Hi,

I'm using `tty-pinentry` and when using `cz bump` this happens:
![image](https://github.com/user-attachments/assets/1e2254da-3505-421a-97da-b5dd5f791fcf)

### Steps to reproduce

Configure `tty-pinentry` and enable loopback in gpg configuration, and try to sign with a password protected GPG key. 

### Current behavior

Fails on sign without being able to prompt the use for the password.

### Desired behavior

Prompt user to type the password. 

### Environment

Commitizen Version: 3.28.0
Python Version: 3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 13.2.0]
Operating System: Linux

**Comment by Lee-W** [comment]
I'm not sure this is something we can fix. 🤔  That part is controlled by pre-commit instead. I'm closing it for now. But feel free to re-open it if you have an idea on how we can deal with it.
