### ISSUE TITLE
JSON support for configuration

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#120]
**Goal**
Support `.cz.json`, `cz.json` configuration

**Description**
JSON seems to be a more common configuration format for non-python project.

**Comment by Woile** [comment]
That's relative, rust uses `toml`, netlify also uses `toml`, and it's becoming quite a standard for configuration (specially because it support comments).
Spite of that, because of the flexibility we now have, a json parser could be implemented.

**Comment by winniepopu** [comment]
I would like to take this issue @Lee-W

**Comment by Lee-W** [comment]
Sure 😃 Feel free to ask us if you encounter any problem

**Comment by Lee-W** [comment]
It seems this feature has been added
