### ISSUE TITLE
Add commitizen-deno-provider to third party commitizen

### ISSUE THREAD

**Issue by dhmmasson** [commitizen-tools/commitizen#1257]
### Type

- [ ] Content inaccurate
- [X] Content missing
- [ ] Typo

### URL

https://commitizen-tools.github.io/commitizen/third-party-commitizen/

### Description

I was missing a provider for a deno project that would handle deno.json. 
I have created one and published it to Pypi. It is still a work in progress, but it might be worth mentioning: https://pypi.org/project/commitizen-deno-provider/

**Comment by woile** [comment]
Nice! Care to send a PR?

**Comment by dhmmasson** [comment]
Yes, 
I'll look into the contributing guideline and provide a PR by the end of the week.

**Comment by dhmmasson** [comment]
I have created a PR, it is somehow related to my #1258 issue, the provider when installed won't be discoverable through cz init because init relies on a fixed list of providers.

**Comment by dhmmasson** [comment]
close by #1259
