### ISSUE TITLE
[test] Update commit messages in test cases

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#127]
**Goal**
make unit tests more accurate

**Description**
In [tests/commands/test_bump_command.py#L23](https://github.com/Woile/commitizen/blob/v1.16.0/tests/commands/test_bump_command.py#L23), the message is `feat: msg` which should be `feat(scope): msg`. There might be some cases like it.

**Comment by Woile** [comment]
keep in mind that scope is optional, I guess we can have a mix of both to make it more accurate

**Comment by Lee-W** [comment]
Ah, I didn't notice that. Yes, we should definitely add test for both cases.

**Comment by Woile** [comment]
### Goal
Review tests, and verify that some commits have scope and some other don't

**Comment by josix** [comment]
Hi, is someone working on this issue? I want to take this issue and try to get more familiar with this project by writing some tests. Not sure if I can start from this issue? Look forward to your response, thank you.

**Comment by Woile** [comment]
Yes, go ahead please. 

So basically the idea is to try to diversify ours tests a bit more, in this particular case is to have some examples **with** scope and some others **without** scope. In case it's not clear the scope is the part that goes between the parenthesis:

```
feat(users): add full name
``` 

`users` would be the scope.

Keep in mind, (AFAIK) that nor @Lee-W , nor me have checked if the tests are already diversified haha. But if you start reading the tests, and there are enough tests with scope and enough without, then this ticket could be closed :+1: 

It could be consider **an investigation** on our source code :muscle: 

Good luck!

**Comment by josix** [comment]
I got it! Thank you for your quick reply. I'll make a draft PR soon and we could have a discuss on the codes there.
