### ISSUE TITLE
[test] check the error code when raising System Exit

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#128]
**Goal**
make unit tests more accurate

**Description**
In [tests/commands/test_bump_command.py#L86](https://github.com/Woile/commitizen/blob/v1.16.0/tests/commands/test_bump_command.py#L86), we do not check the error code. It's possible to raise the same exception but not our expected case. Maybe we should refactor them as custom exceptions?

**Comment by Woile** [comment]
Yes, custom exceptions makes sense. But this would be a breaking change, we can schedule it for 2.0

**Comment by Lee-W** [comment]
Maybe we can fix it in two steps. The first step is to check only the error code and merge it into `1.*`. The second step is to refactor it into custom exceptions and release it in `2.0`.

**Comment by Woile** [comment]
To be honest, I don't see much value in adding the checks for `1.x`. The error code thing is an idea I had to give people flexibility to decide what to do on each error when writing configuration scripts, but I've never seen anyone do conditions on error in bash, even less with commitizen.

So I say we don't waste time on it (be my guest if you want to do it, but I don't think it really adds value). And refactor into more expressive custom exceptions for 2.0

**Comment by Lee-W** [comment]
Yes, that makes sense. Do we have any plan on when or how we release 2.0? Maybe a branch `2.0` so we can merge `2.0-only` commits into the branch?

**Comment by Woile** [comment]
I've created a branch `next`, we can start sending PR there

**Comment by Lee-W** [comment]
I think the error code is quite useful when I use some of the new features recently. I'm thinking of refactoring these errors into classes but still have the same error code which makes it a non-breaking change. @Woile What do you think?

**Comment by Woile** [comment]
Great idea! Go for it!

**Comment by Woile** [comment]
@Lee-W can we close this ticket?

**Comment by Lee-W** [comment]
Ah yes, I forgot it haha. Let's close it!
