### ISSUE TITLE
[feature] support finding latest relase version in bump version commit message

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#130]
**Goal**
Make automatic version bumping possible through version specified in `version_files`

**Description**
In [commitizen/commands/bump.py#L36](https://github.com/Woile/commitizen/blob/v1.16.0/commitizen/commands/bump.py#L36), we only use `git tag` to find whether the tag specified in `version_file` exists. If one project use `version_files` without `git tag`, "commitizen" will not be able to know whether it should bump without asking the user, which makes auto version bumping through CI difficult in this case.

**Comment by Woile** [comment]
Makes sense, it would completly ditch the `git` dependency. Seems nice.

At the moment my only proposal would be to add a `--no-git` to `cz bump`, any other ideas?

**Comment by Lee-W** [comment]
I think `--file-only` alone should work. But I do not have a clear idea of how this should be implemented. I used to need it, but I solve it in another way.

**Comment by Woile** [comment]
Maybe we need to document `cz bump --files-only` better, which is there already.

**Comment by voidful** [comment]
The same problem also occurs in `cz init`
When I init cz for my existing project, it detect version from `git describe --abbrev=0 --tags`. However, this is not the version I wanted. 
Therefore, one of the solutions is to allow me to enter the latest version number during init.

**Comment by Woile** [comment]
Agreed, that'd be helpful in the init
