### ISSUE TITLE
[feature - changelog] configurable changelog_pattern/map

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#131]
**Goal**
Make changelog more configurable 

**Description**

**Related Issue**
#129

**Comment by Woile** [comment]
This is configurable now. More info in the [documentation](https://commitizen-tools.github.io/commitizen/changelog/#description)
We have several variables that allow customization.
We have established a pattern (change_type, scope and breaking are optional), but if the pattern is not used, the `message` alone will be rendered, being a simple changelog.

Should we close it?

**Comment by Lee-W** [comment]
Yes, let's close it!
