### ISSUE TITLE
[feature - changelog] support custom change log template for changelog command

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#132]
**Goal**
Make changelog more configurable

**Comment by Woile** [comment]
I think this would add quite a lot of complexity, IMO it's better to add extra annotations through hooks to the changelog. And the existing template is relatively flexible (enough for me).

**Comment by Lee-W** [comment]
Yep, I agree with you. But i'd like to keep this issue open. Maybe someone would be interested in making this happen.

**Comment by Woile** [comment]
Keep in mind that the more flexibility, the higher maintenance burden :firefighter:  falls on us.
Flexible enough is sometimes the right amount

**Comment by Lee-W** [comment]
The purpose of this issue is not clear enough. Even I forget which part I want changelog to be configurated. Let' close this one and open another one if we have concrete ideas
