### ISSUE TITLE
Provide shell completion for cz

### ISSUE THREAD

**Issue by rnc** [commitizen-tools/commitizen#137]
Once it is installed it would be very useful to have shell completion (bash/zsh) for it.

**Comment by Lee-W** [comment]
We could use [python-prompt-toolkit autocompletion](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#autocompletion) to achive it.

**Comment by danvergara** [comment]
Hi buddies! Is this still open and not implemented? What's the status of this?

**Comment by Woile** [comment]
It's still open. There's no implementation.
I've found this https://kislyuk.github.io/argcomplete/ that may be helpful, but didn't look further.

**Comment by danvergara** [comment]
Great! I'd like to take this!

**Comment by Lee-W** [comment]
folk from pycontw 2021 develop sprint just found out this feature has been implemented. let's close it 🎉
