### ISSUE TITLE
Feature request: `commitizen` should support revert commits

### ISSUE THREAD

**Issue by lucatrv** [commitizen-tools/commitizen#142]
I know that a similar request was discussed [before](https://github.com/Woile/commitizen/issues/36), however [`angular` does contemplate revert commits](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#revert).

As a minimum, `cz check` should accept commit messages beginning with `revert:`, otherwise when it is configured as a `pre-commit` hook it does not allow revert commits.

Moreover, IMHO a `cz revert` command should be added, accepting the `<commit>` to revert. It should run `git revert <commit>`, including in the message body: `This reverts commit <hash>.` as per `angular` instructions. See information on [`git revert`](https://www.atlassian.com/git/tutorials/undoing-changes/git-revert).

For examples of revert commit messages, see for instance [`standard-version`](https://github.com/conventional-changelog/standard-version/commits/master) and [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog/commits/master) commit logs.

Notice that both [`commitlint`](https://github.com/conventional-changelog/commitlint#what-is-commitlint) and [`gitlint`](https://jorisroovers.com/gitlint/contrib_rules/#ct1-contrib-title-conventional-commits) support revert commits.

**Comment by lucatrv** [comment]
I add that IMHO, other than `revert`, also the `chore` type should be added. In fact the [Conventional Commits website](https://www.conventionalcommits.org/) clarifies that their specifications are **inspired** by the Angular Commit Guidelines (so not identical), and reports as an example the [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) recommendations, which include also `chore` and `revert` types.

**Comment by lucatrv** [comment]
I now noticed the following definition of the `schema_pattern` function in `conventional_commits.py`:

```python
def schema_pattern(self) -> str:
    PATTERN = (
        r"(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)"
        r"(\(\S+\))?:\s.*"
    )
    return PATTERN
```

So it includes both `revert` and `chore`.

**Comment by Lee-W** [comment]
To have `revert` and `chore` type, we'll have to add it [here](https://github.com/Woile/commitizen/blob/v1.17.0/commitizen/cz/conventional_commits/conventional_commits.py#L38) as well.

**Comment by Lee-W** [comment]
As for command like `cz revert`, we can add a command under [commitizen/commands](https://github.com/Woile/commitizen/tree/v1.17.0/commitizen/commands). By doing so, we might need to also consider the default behavior for the cz that does not have revert type (e.g., [cz_jira](https://github.com/Woile/commitizen/tree/v1.17.0/commitizen/cz/jira))

**Comment by Woile** [comment]
> To have `revert` and `chore` type, we'll have to add it [here](https://github.com/Woile/commitizen/blob/v1.17.0/commitizen/cz/conventional_commits/conventional_commits.py#L38) as well.

I wouldn't add them, those 2 are added to the "pattern" in order to prevent backward errors, but officially they are not part of conventional commits, we are using the latest [types from Angular](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) (they used to but were removed).Using `chore` or `revert` would be part of a different custom rule.

Regarding the `revert` commit, I'm not really sure if we want to add a whole new command because it would be pretty much useless for any other "rule" like jira. And it can be achieved by doing:

```
git revert --no-commit <SHA>
git commit -m "revert: foo bar"
```
```

**Comment by Lee-W** [comment]
When checking the commit message through `cz check`, I skip `Merge` and `Revert`. Thus, this won't be a problem.

**Comment by Lee-W** [comment]
This issue is raised more than one time (I had the same question when I first use commizen as well.) Maybe we could consider adding it to FAQ in documentation?

**Comment by lucatrv** [comment]
OK, in this case I would document it in `README.md` after the ["Help" section](https://github.com/commitizen-tools/commitizen#help), maybe in a new section titled "How to handle revert commits?" or similar. It could reference the corresponding section on the [Conventional Commits website](https://www.conventionalcommits.org/en/v1.0.0/#how-does-conventional-commits-handle-revert-commits), and report the [two commands suggested above](https://github.com/commitizen-tools/commitizen/issues/142#issuecomment-599499113).

**Comment by Lee-W** [comment]
Thanks for the feedback 🙂 I just added it to the FAQ. I'll close this issue.
