### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#154]
The changelog is outdated since 1.12.0.

**Comment by Woile** [comment]
I'm working steady but slowly on the auto-changelog, I hope once I'm done with it, we can regenerate the changelog automatically  :ok_hand:

**Comment by Lee-W** [comment]
I'll back to auto-changelog soon lol    Just found some bug related to `mypy`, want to enforce it to make `commitizen` more bug-free. 🙂

**Comment by Woile** [comment]
No rush, I hope to make a PR this week and we can discuss it

**Comment by Lee-W** [comment]
Thanks @Woile . After the release of auto changelog, this issue is resolved as well 🎉
