### ISSUE TITLE
Incorrect deprecation warning when no config is used

### ISSUE THREAD

**Issue by jameswilliams1** [commitizen-tools/commitizen#159]
On my project the default settings are fine but I use a `setup.cfg` for configuring other tools. Because of this I get a deprecation warning from commitizen about switching to using `pyproject.toml` instead. If no settings are specified for commitizen in the `setup.cfg` then it shouldn't give a warning. Currently I have had to add:

```toml
[tool.commitizen]
```
to my `pyproject.toml` with no settings to stop the warning.

**Comment by Lee-W** [comment]
@jameswilliams1 Thanks for reporting the issue! I just confirmed this error.

**Comment by Lee-W** [comment]
@jameswilliams1 This bug is fixed on 1.18.1.
