### ISSUE TITLE
[GitHub Action] Separate github page publish from python package publish

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#171]
Currently, we publish the GitHub page and python package after a new version is deployed. If we only update documentation, it won't trigger a version bump and thus will not update the documentation on GitHub page

**Comment by Woile** [comment]
I don't know how important is this to us, because we are making releases quite often.

Being said that, if we want to release the docs on every merge, we can make a separated GitHub action only for the docs. That'd solve our problem.

**Comment by Lee-W** [comment]
It's nice to fix the bug, but not in an urgent one.
