### ISSUE TITLE
Show all ill-formatted commits when running batch cz check

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#175]
`cz check --rev-range master..HEAD` currently only shows the latest commits that do not follow the pattern. It would be more convenient if these ill-formatted are showed at once

**Comment by josix** [comment]
Hi, is this issue currently processing ? May I try to solve this issue?

**Comment by Woile** [comment]
Fine by me, I don't know if @Lee-W is working on this

**Comment by Lee-W** [comment]
@josix Sure! I've not yet worked on this one.

**Comment by josix** [comment]
Thank you for your quick reply! I'll make a draft PR first to let you be able to track my progress.

**Comment by Lee-W** [comment]
We're looking forward to it 🎉

**Comment by Lee-W** [comment]
Fix by #244
