### ISSUE TITLE
[Bug Report] cz bump --changelog adds empty lines to the beginning of the CHANGELOG.md

### ISSUE THREAD

**Issue by misterkramer** [commitizen-tools/commitizen#192]
## Description
After each execution of the command `cz bump --yes --changelog`, one new empty line is invariably added to the `CHANGELOG.md`

## commitizen version
1.22.1

## Steps to Reproduce
1. Commit change
2. Run `cz bump --yes --changelog` 

## Expected Behavior
After **each** executing `cz bump --yes --changelog`  there is only one empty line at the beginning of the `CHANGELOG.md`

## Actual Behavior
An empty line are added to the beginning of the `CHANGELOG.md` after **each** execution `cz bump --yes --changelog`

## More Information
This can also be seen here with blame - https://github.com/commitizen-tools/commitizen/blame/master/CHANGELOG.md
![image](https://user-images.githubusercontent.com/23519610/83082059-056ab900-a08b-11ea-897b-9ef0cf186243.png)

I assume this is because of the parameter: https://github.com/commitizen-tools/commitizen/blob/601bd29edcc19f2ba8c6a30605b4d7e910f99e32/commitizen/commands/bump.py#L148

I can also reproduce this problem by running `cz changelog --incremental`

**Comment by Lee-W** [comment]
Hi, thanks for the report. I've confirmed and reproduced this bug. We'll take a look. 🙂

**Comment by Woile** [comment]
Thanks we'll try to fix it, though it shouldn't affect the rendering of the changelog.

I think a possible fix would be removing the [second line in the template](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/templates/keep_a_changelog_template.j2#L2)

Or doing an `lstrip` in the [incremental changelog_out](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/changelog.py#L120)

Also we should add a test for this, after some times I think it would affect people reading the source directly.

**Comment by misterkramer** [comment]
Thank you so much for such a quick solution! 
And thank you for `commitizen` - this is a cool tool that we use in each of our projects. 
Keep it up!:+1:
