### ISSUE TITLE
Need doc for pre-commit integration

### ISSUE THREAD

**Issue by guihao-liang** [commitizen-tools/commitizen#196]
## Type
* [x] Content missing

## URL

My understanding is that this tool can only work in `commit-msg`  and `prepare-commit-msg` stage based on this [doc](https://pre-commit.com/#pre-commit-for-commit-messages).

But I haven't found any doc showing me how to use this nice tool with `pre-commit` tool.

## Description

I think it's better to provide a doc to explicitly mention this in README.md.

```
 27 - repo: https://github.com/commitizen-tools/commitizen
 28     rev: v1.22.2
 29     hooks:
 30       - id: commitizen
 31         stages: ["commit-msg"]
```

When used, it should use `pre-commit install -t commit-msg`.

**Comment by guihao-liang** [comment]
I can add this to README if you think it's appropriate to add this to there.

**Comment by Lee-W** [comment]
It can be found [here](https://commitizen-tools.github.io/commitizen/check/).

**Comment by guihao-liang** [comment]
> Thank you for your suggestion! But it can be found [here](https://commitizen-tools.github.io/commitizen/check/). Or do you think it's not that easy to find? We can discuss more on how to make this better 🙂

Wow! I didn't find that. Yeah, it's good to provide a link to this in the README.md.

**Comment by Lee-W** [comment]
I just add a link to our GitHub page. I'll close this issue for now. We can discuss more if you think we can do better. Also, feel free to send us a pr 🙂
