### ISSUE TITLE
commitzen is not fully compatible with the latest conventional commit

### ISSUE THREAD

**Issue by guihao-liang** [commitizen-tools/commitizen#199]
## Type
* [x] Conent inaccurate

## URL

Just realize this tool is not using a conventional commit spec,
```
$ cz schema
<type>(<scope>): <subject>
<BLANK LINE>
(BREAKING CHANGE: )<body>
<BLANK LINE>
<footer>
```

Whereas in [conventional commit ](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both-and-breaking-change-footer)spec, `BREAKING CHANGE` should belong to footer.

## Description
Is it by design?

I don't think this is fully compatible with conventional commit. I think you may need to mention this explicitly.

**Comment by Woile** [comment]
Hey! thanks for raising this issue.

It may not match with `v1.0.0`, but `v1.0.0-beta` says:

> BREAKING CHANGE: a commit that has the text BREAKING CHANGE: at the beginning of its **optional body** or footer section introduces a breaking API change (correlating with MAJOR in semantic versioning). A breaking change can be part of either a fix: or feat: type commit

https://www.conventionalcommits.org/en/v1.0.0-beta/

if you only add body with this `commitizen`, then the body is also, technically, the footer. 

If you use BREAKING CHANGE in a body or in a footer, `commitizen` won't care and will pick it up, so it doesn't really matter to `commitizen`.

I'd like to know how does this affect you, and if you could provide some use cases.

What do you think @Lee-W should we add a new patch to comply with `v1.0.0`? I think the change would be small.

**Comment by guihao-liang** [comment]
> if you only add body with this `commitizen`, then the body is also, technically, the footer.
> 
> If you use BREAKING CHANGE in a body or in a footer, `commitizen` won't care and will pick it up, so it doesn't really matter to `commitizen`.

Thanks for the prompt reply! Got it. I just want to know whether adding `BREAKING CHANGE` to different places will cause any effect or not. I think it's better to mention this explicitly because I was reading the spec from [1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) and I expect `commitizen` will comply with that spec. Other users may have the same expectations.

One more question, does commitizen recognize `!`?

> appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in semantic versioning)

**Comment by Lee-W** [comment]
@Woile Yes, I think it would be better if we can comply with `v1.0.0`.

@guihao-liang Yes, `!` is recognized in [default.py](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/defaults.py#L23).

**Comment by Woile** [comment]
Makes sense @Lee-W
