### ISSUE TITLE
[Bug Report] Some commands won't work if no git repository

### ISSUE THREAD

**Issue by Woile** [commitizen-tools/commitizen#206]
## Description
Commands like `cz --help`, `cz example`, `cz schema`, `cz ls`  and `cz version` won't work if there's no repository

## commitizen version
`1.23.0`

## Steps to Reproduce
1. `cd`
2. `cz --help`
3. Observe error

> fatal: not a git repository (or any of the parent directories): .git

## Expected Behavior
Show information when necessary, people may want to see the `schema`, `example`, or `version` at any place.

## Actual Behavior

> fatal: not a git repository (or any of the parent directories): .git

**Comment by Lee-W** [comment]
This is fixed by #219. Close this issue
