### ISSUE TITLE
[Documentation] External Links and Articles

### ISSUE THREAD

**Issue by Woile** [commitizen-tools/commitizen#208]
## Goal
Add new **"External Links and Articles"** section in the documentation

## Description
It would be nice if we start collecting the talks, and articles written in that section, I think it would also help people wrap their minds around it, and see how we are using it.

@Lee-W if you could share the links of your existing talks (and the dates) that'd be great to start with :D

What do you think?

**Comment by Lee-W** [comment]
Yep, it's a great idea! I'll add it this week!
