### ISSUE TITLE
[Documentation] Add instructions on how to use commitizen with pre-commit in README.md

### ISSUE THREAD

**Issue by altusgerona** [commitizen-tools/commitizen#209]
## Type
* [ ] Conent inaccurate
* [x]  Content missing
* [ ] Typo

## Description
We should add a small snippet for `pre-commit` integration with Commitizen. I realize that this is in the docs, would be nice to include it in the `README.md` as well for an easy reference to first-time viewers.

Would be happy to submit a PR if needed. Would love for `commitizen` to be more widely used.

**Comment by Woile** [comment]
Feel free to submit a PR :smiley: 

Thanks! We too!

**Comment by altusgerona** [comment]
I just realized this is sort of an extension of #196. The resolution for that was the full documentation link to the README.md. I'll make this issue specifically about visibility in the README.md. Will submit a PR in a few.

**Comment by Lee-W** [comment]
Since this issue has been raised more than once, maybe there is a better way to structure/link the document. We can discuss more on this issue or your PR 🙂

**Comment by altusgerona** [comment]
We can close this now due to #210 being merged.
