### ISSUE TITLE
[Feature Request] Add pre-commit integration

### ISSUE THREAD

**Issue by altusgerona** [commitizen-tools/commitizen#211]
## Description
Currently, the contributing guide states that we run the lints and tests manually before resolving a commit. Why not force this already by using [pre-commit](https://pre-commit.com/)?

## Possible Solution
Add pre-commit config file and dev dependency.

**Comment by Lee-W** [comment]
do you mean generate it when running `cz init`?

**Comment by altusgerona** [comment]
Nope. Basically adding `pre-commit-config.yaml` to the repository and having contributors run `pre-commit install` before running a commit to make sure that their staged changes and commit message are linted and follow convention.

**Comment by altusgerona** [comment]
We could also add `pre-commit install` to poetry scripts so it enforces the standard.

**Comment by Lee-W** [comment]
> Nope. Basically adding `pre-commit-config.yaml` to the repository and having contributors run `pre-commit install` before running a commit to make sure that their staged changes and commit message are linted and follow convention.

Yep, it sounds good to me 🚀


> We could also add `pre-commit install` to poetry scripts so it enforces the standard.

Do you mean to set it up for contributors when they run `poetry install`? How could we achieve it?

**Comment by altusgerona** [comment]
I was thinking maybe using [`poetry` scripts](https://python-poetry.org/docs/pyproject/#scripts) but that looks like it doesn't behave the same way as package.json's `postinstall`. It's okay though. We should be enforcing the convention at CI level too. So before tests start, `pre-commit run -a` should not fail.

**Comment by Lee-W** [comment]
We already have those scripts under `scripts`. I think I'll have the time to set up the pre-commit config late today.

**Comment by altusgerona** [comment]
The `scripts` would be redundant with the pre-commit config. I can also submit a PR if you'd like.

**Comment by Lee-W** [comment]
#216 merged.
