### ISSUE TITLE
Add new 3rd party template

### ISSUE THREAD

**Issue by marcelomaia** [commitizen-tools/commitizen#214]
## Type
* [x] new plugin

## URL
https://github.com/marcelomaia/commitizen-emoji

## Description
In 3rd party templates add: https://github.com/marcelomaia/commitizen-emoji

**Comment by Woile** [comment]
Thanks, looks great! I'll add it :)

**Comment by Lee-W** [comment]
@marcelomaia It looks great! 🎉 Could you please send us a pull request? I think you're the best person to add the short description for commitizen-emoji in the documentation 🙂
You can do so by modifying this file. https://github.com/commitizen-tools/commitizen/blob/master/docs/third-party-commitizen.md

**Comment by marcelomaia** [comment]
Sure I will. Thanks!

**Comment by Lee-W** [comment]
solved by #217
