### ISSUE TITLE
[Feature Request] Execute pre-commit hooks before prompting for the message

### ISSUE THREAD

**Issue by lyz-code** [commitizen-tools/commitizen#220]
## Description
If any pre-commit hook fails, the commitizen message is lost and you need to run `cz c --retry`.

## Possible Solution
If the hooks are run before prompting the user for input this would be avoided. Plus is the default git behavior.

**Comment by Lee-W** [comment]
It's a great idea! I also suffer from this time to time.

**Comment by jtpavlock** [comment]
This might be as easy as just running `.git/hooks/pre-commit` before showing the prompt and continuing based on exit status.

**Comment by Lee-W** [comment]
After a second through, I'm not sure it's a good idea. commitizen works more like `git commit -m` instead of `git commit` and then enter an editor. I don't think we should actively trigger pre-commit before commitizen. Currently, I can not think of other good solutions for it.

**Comment by alecgerona** [comment]
@Lee-W we should at least make the `--retry` option more prominent in the README. This leads to a lot less headaches.

**Comment by Lee-W** [comment]
@alecgerona I just add a new issue so that we won't forget it.
https://github.com/commitizen-tools/commitizen/issues/268

**Comment by Lee-W** [comment]
As #268 has been closed, I think we can close this one
