### ISSUE TITLE
[Bug Report] Changelog is not added to the bump commit

### ISSUE THREAD

**Issue by lyz-code** [commitizen-tools/commitizen#221]
## Description

When running `cz bump --changelog`, the changes to `CHANGELOG.md` are not added to the `bump: version x.y.z -> a.b.c`, so the release `a.b.c` doesn't have the updated `CHANGELOG.md`.

## commitizen version
1.23.0

## Steps to Reproduce

```bash
mkdir bump_test
cd bump_test
git init
cz init
touch some_file.txt
git add .
git commit -m "feat: added some_file"
cz bump --changelog

$: git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	CHANGELOG.md

nothing added to commit but untracked files present (use "git add" to track)
```

## Expected Behavior
Changes on CHANGELOG.md should be added to the bump commit.

## Actual Behavior

Changes to the Changelog aren't staged before [the commit is performed](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/bump.py#L156).

**Comment by Woile** [comment]
This is happening because `CHANGELOG.md` is not tracked by default. 
We are doing `git commit -a` which includes what's already being tracked, I think this would simplify our lifes.
I wonder if it would bring any drawbacks, what do you think @Lee-W ?

**Comment by Lee-W** [comment]
I'm not sure. Will we accidentally add unrelated files by doing so? Maybe "git add <changelog_filename>" would be better?

**Comment by Woile** [comment]
`git commit -a` will add only already tracked files. And it's what we are doing now. This way we can include into the commit any change happening in `version_files` + `pyproject.toml` or `.cz.toml`.
If `CHANGELOG.md` is tracked before doing `bump`, there won't be any issues.
But, if it's the first time, and you let `commitizen` create it, then it won't be included the first time.
I don't see any issues with adding the command you mention then :+1:

**Comment by Lee-W** [comment]
Thanks for your explanation! I think it might be better that we replace `git commit -a` with `git add <version_files>` and `git add <changelog_file>` then `git commit` to avoid accidentally adding unexpected files.

**Comment by Woile** [comment]
The only issue I see with removing `git commit -a` is that if you want other changes to be picked up by the bump commit, you'd have to remove the tag, amend the commit and add the tag again. While the current side effect, allows u to make a modification that you want to be picked up by the bump.

IMO we should just track the `changelog_filename` after the `git commit -a`

**Comment by Lee-W** [comment]
Yep, that makes sense.

**Comment by Lee-W** [comment]
This is now fixed 🙂 Close this issue
