### ISSUE TITLE
[Bug Report] Commitizen returns a failing exit code on success.

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#222]
## Description
Using `cz -c` with other pre-commit hooks, it seems like commitizen returns a non-zero (i.e. failing) exit code even if all hooks pass and the commit is successful

## commitizen version
1.23.0

## Steps to Reproduce
1. Run `cz c` with other git commit hooks enabled (I have them installed via pre-commit)

## Expected Behavior
Should return exit code of 0 if all tests pass and the commit is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/26807251/88189987-54eae280-cbff-11ea-95bd-7c6792fd2937.png)

compared to normal:

![image](https://user-images.githubusercontent.com/26807251/88190236-a8f5c700-cbff-11ea-9965-7c2c9fd380ee.png)

## Actual Behavior
Returns a non-zero exit code even if commit is successful. This is confusing behavior.

## More Information
As it is now, it is hard to tell if a commit was successful or not.

**Comment by Woile** [comment]
Fixed on the latest release `1.23.3`

Can u check @jtpavlock ? Gonna close it for now

**Comment by jtpavlock** [comment]
Looks good, thanks for the fix 👍
