### ISSUE TITLE
[Feature Request] Automatic bump on fix or feature

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#223]
## Description
Not sure if there is a current way to do this or not, but if would be useful (especially for CI implementation), if there was a way to have `cz bump` automatically ran if a version increment is warranted after a commit

## Possible Solution
Perhaps a `--check-increment` option that would return true or false if running `cz bump` would result in incrementing and a new tag. This could then be checked in CI as a precursor to running `cz bump`

**Comment by jtpavlock** [comment]
I saw https://commitizen-tools.github.io/commitizen/tutorials/github_actions/ which seems to be what I'm looking for. I just initially misunderstood it's purpose 😅

**Comment by Woile** [comment]
Yes, by using github actions you can achieve that behavior, or other CI. Glad you found it, gonna close it now :+1:
