### ISSUE TITLE
[Feature Request] Limit any commit line to 100 characters

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#224]
## Description
Currently, [AngularJS limits their commit lines to 100 characters max.](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)

Is there any plan to also enforce this?

## Possible Solution
Return an error if the user attempts to commit a line longer than 100 characters.

**Comment by Woile** [comment]
Duplicate of #191. Le's continue the discussion over there :pray:
