### ISSUE TITLE
[Feature Request] Check with CI that all commits use proper format

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#227]
## Description
I'd like to be able to automatically check all commits (perhaps since the last tag?) follow the proper format with a github action. I have seen `cz check --rev-range`, but the example given (`cz check --rev-range master..HEAD`) only works if a commit was made on a branch other than master. There's no (easy) way to check commits directly on master.

## Possible Solution
add a `cz check --new` that will "lint" any commits that have been added since the last version tag.

## Additional context
This would ideally be able to be run along side any normal tests/linting that gets checked on push or pull_request github actions.

A current workaround for checking all commits since the last tag is to do `$ cz check --rev-range $(git describe --tags | grep -o "v[^-]*")..HEAD` but still this is not perfect as it will fail if it doesn't find any commits since the last tag, and thus will fail the lint check on CI.

**Comment by jtpavlock** [comment]
So I guess the best thing is to just do it since the first commit at which you started using `commitizen`. So, `cz check --rev-range <first_commitizen_commit>..HEAD`

I think this should perhaps be explained in the docs a little since [it currently seems fairly bare](https://commitizen-tools.github.io/commitizen/check/) (and doesn't even mention --rev-range

Thanks for all the great work you guys are doing here, if I get some time maybe I'll try to expand on the docs a bit.

**Comment by jtpavlock** [comment]
On another note, would you guys be interested in exposing this behavior via a pre-commit hook? That way it could be run along side other hooks with `pre-commit run -a` as an all encompassing lint command.

**Comment by Woile** [comment]
Please do! If you have time feel free to expand the docs, it's very welcome.

I don't use much the check command, I think @Lee-W can give better feedback whether it's relevant or not.
