### ISSUE TITLE
Documentation link broken?

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#245]
https://commitizen-tools.github.io/ returns 404

**Comment by Lee-W** [comment]
Hmmm... we don't have a document for the whole group at this moment. @Woile Do you think we should have one? Or, we could redirect it to https://commitizen-tools.github.io/commitizen/?

**Comment by jtpavlock** [comment]
This is the link in the README. I assume it should be changed to the one you posted.

**Comment by Woile** [comment]
Indeed we should update it
