### ISSUE TITLE
Support revert bump or commit

### ISSUE THREAD

**Issue by Woile** [commitizen-tools/commitizen#251]
## Description
So the idea is to be able to undo a bump + changelog just made or commit.

This can be either a command or just documentation (doesn't need to be part of the code).
For example, in my use case I usually forget to add `--changelog` or sometimes I forgot something.

This command is intended for local usage. Specially if you manually execute `cz bump --changelog`

## Possible Solution

The code to revert a bump for example is:

for a bump:

```bash
git tag --delete <created_tag>
git reset HEAD~
git reset --hard HEAD  # or git checkout -f
```

for a commit:

```bash
git reset HEAD~
```

## Additional context
In case we go for a command I see something like this:

```
cz undo --bump
cz undo --commit
```
I'd avoid `revert` because it has a different meaning in git. Which is adding a new commit reverting the previous one.

Opinions? Thoughts?

**Comment by Lee-W** [comment]
Do you mean `cz undo --bump` and `cz undo --commit`? I'm neutral about this feature.

**Comment by Woile** [comment]
Yes, updated, thanks.

It could also be just a revert for a bump, like `cz bump --undo`.

**Comment by Sirius207** [comment]
I would like to take this issue 👍 

@Lee-W

**Comment by Lee-W** [comment]
Sure 👍
