### ISSUE TITLE
[pytest] pytest fail on Windows 10

### ISSUE THREAD

**Issue by chencheyu** [commitizen-tools/commitizen#253]
## Description

pytest fail on Windows 10, the system language is zh_tw.

## Steps to reproduce
1.  `$pytest`

## Current behavior

![擷取1](https://user-images.githubusercontent.com/39858274/91655540-e0e80800-eae3-11ea-8205-ea7d0c236c62.PNG)

![擷取2](https://user-images.githubusercontent.com/39858274/91655560-112fa680-eae4-11ea-91a7-0c055f295e4f.PNG)

## Environment

- commitizen version:2.1.0
- python version:3.8.5
- operating system:Windows

**Comment by Woile** [comment]
At first sight seems to be related to the lack of a dependency. Try `pip install pytest-mock` and let me know if that fixes the problem

**Comment by Lee-W** [comment]
as no new comment been added after the latest suggestion, close this issue
