### ISSUE TITLE
[Feature Request] Be more verbose about which input is required or optional

### ISSUE THREAD

**Issue by alecgerona** [commitizen-tools/commitizen#258]
## Description
So for each of the text inputs on the cli: scope, subject, footer etc. I think we should be more explicit about which is required or not. Also adding some helpful guideline like "press enter to skip" could help.

**Comment by Woile** [comment]
Agreed!

**Comment by alecgerona** [comment]
I think this should be easy enough to implement. Mind if I take this?

**Comment by Woile** [comment]
Go ahead! That'd be great

**Comment by alecgerona** [comment]
Also quick question, do we parse out the final dot on the subject?
