### ISSUE TITLE
Make commitizen installable via MacPorts

### ISSUE THREAD

**Issue by harens** [commitizen-tools/commitizen#260]
## Description
Although Homebrew doesn't work very well with Poetry packages, there is a viable method of writing a Portfile for commitizen. This would allow for the following command to install the package.

```
sudo port install commitizen
```

## Possible Solution
Add a setup.py file to each release/tag of both commitizen and decli via [dephell](https://dephell.org).
Create portfiles for any dependencies that don't already have one.

questionary: https://github.com/macports/macports-ports/pull/8296 ✅
decli: https://github.com/macports/macports-ports/pull/8645 ✅

## Additional context
Poetry currently cannot be built using the `--no-binary:all:` flag: https://github.com/python-poetry/poetry/issues/1975. This makes it difficult to create a homebrew package https://github.com/commitizen-tools/commitizen/issues/256.

**Comment by harens** [comment]
questionary has now been added to MacPorts. I'm still happy to try and add commitizen as well if this is what you want, but it would be really useful if a setup.py could be added to both decli and commitizen. Thanks.

**Comment by Lee-W** [comment]
I personally don't like to maintain `setup.py`. But if we could auto-generate `setup.py` from `pyproject.toml` and use it only when we need to update to MacPorts, I'll be fine with it. @Woile What do you think?

**Comment by Woile** [comment]
Same. But I don't know how it works. Is it mandatory to track it?

**Comment by harens** [comment]
🎉 Commitizen has been added to MacPorts! 🎉

A summary page can be found [here](https://ports.macports.org/port/commitizen/). To my knowledge, there is no simple way of automatically updating the portfile with each release. However, it is quite simple to update it manually, and I will be sure to do that as often as I can.
