### ISSUE TITLE
[Question] Shouldn't releases be automated? 

### ISSUE THREAD

**Issue by alecgerona** [commitizen-tools/commitizen#261]
Just curious why releases don't happen as soon as changes are merged to master. The version is already bumped anyway.

**Comment by Woile** [comment]
Yes, they should. There's a bug, the new CI is using `secrets.GITHUB_TOKEN`, but we should go back to `secrets.PERSONAL_ACCESS_TOKEN`, because the first one doesn't trigger new builds :/

**Comment by Woile** [comment]
mmm not really. The vision we have is a bit more decoupled.
- a **new commit to master** triggers a bump version, which in turn will push a tag.
- a **new tag** with the format `v*` triggers a publish. This means that if I want to make a release pushing a local tag we can (for example a release candidate).

See it like "which git event triggers which action".

The update I mention is when we started using our own github action, you can see the change [here](https://github.com/commitizen-tools/commitizen/commit/7ec5c1fbbb2d7e1b2cc86778cf111d56f3b1294b)

It's fixed now, a new release will happen soon

**Comment by alecgerona** [comment]
We can have release candidates or alphas or betas as branches, too. Just for context my flow draws from how [semantic-release](https://github.com/semantic-release/semantic-release) does it.

**Comment by alecgerona** [comment]
Hmm I think there's no release yet.

**Comment by Woile** [comment]
I've released the latest versions, but indeed it's not automatically releasing, I'll make an investigation

**Comment by alecgerona** [comment]
Thanks! Let's close this once it's resolved. If you need help lemme know.

**Comment by Lee-W** [comment]
Is it the action that releases 2.3.1?
https://github.com/commitizen-tools/commitizen/actions/runs/242737189

**Comment by alecgerona** [comment]
Seems like it.

**Comment by Lee-W** [comment]
Is there anything we need to do for this issue?

**Comment by Woile** [comment]
I manually pushed the tags in order to trigger the action.
Since we introduced the github action, it doesn't trigger other github actions. We need to find out why.
I'm still not sure, because I've updated the secret to use the `PERSONAL_ACCESS_TOKEN`.

AFAIK if you use `GITHUB_TOKEN` it doesn't trigger other jobs, kind of like using `[skip ci]`, so you have to use your own token to trigger the jobs. But again, I updated the token, and it didn't make a release. Maybe some leftovers, and the next release will work.

**Comment by Lee-W** [comment]
Got it. Thanks for the explanation 😄

**Comment by Woile** [comment]
Releases are working fine again
