### ISSUE TITLE
Add  example and illustration to `cz commit --retry` 

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#268]
## Type
* [x] Content missing

## URL
https://commitizen-tools.github.io/commitizen/check/

## Description
We could add some example of how `cz commitz --retry` can be used.

**Comment by woile** [comment]
Is this still valid?

**Comment by Lee-W** [comment]
Yes, I think so.

**Comment by Lee-W** [comment]
just checked. it seems to be there now https://commitizen-tools.github.io/commitizen/commit/#retry

**Comment by Lee-W** [comment]
Thanks, @Smallfu666, for the reminder. This has been resolved.
