### ISSUE TITLE
[Feature Request] Make -R an alternative for --retry

### ISSUE THREAD

**Issue by alecgerona** [commitizen-tools/commitizen#269]
## Description
Currently retry is only usable with `--retry`. It should also be doable with `-R`

## Related Issue
This would be a great precursor to #268.

**Comment by Woile** [comment]
I'm doubtful about this, `-r` or `-R` are populary used for recursive. Someone reading `cz c -r` may wonder "why recursive?". I think that's the reason I didn't want to introduce a shortcut for retry.

In what context are you typing `retry` so often? maybe we can solve it in a different way.
For example we could add the `-a` flag :thinking: so `cz commit -a` to automatically do a `git add -u`.

@Lee-W what is your opinion on this topic

**Comment by Lee-W** [comment]
I'm netural to the `-r`, `-R` idea. I don't see recursive argument that often but I understand your concern. As for `cz commit -a`, as long as we don't make it default, I think it's nice to have. BTW, I use `cz commit --retry` quite often haha. pre-commit blocks my commit if I have some minor error to fix

**Comment by alecgerona** [comment]
I guess I don't really have a strong opinion on it either. Just wanna put it up for discussion. But like with @Lee-W, I also use `cz c --retry` a _lot_ :joy:

**Comment by Lee-W** [comment]
The discussion seems to stop here. Thus, I'll close this one for now. Feel free to reopen it if any further discussion needed
