### ISSUE TITLE
Silly question about commitizen and use for C/C++ repos

### ISSUE THREAD

**Issue by krish2487** [commitizen-tools/commitizen#274]
Hello,

Please excuse my rather stupid and silly question, for I am trying to learn.
I m a firmware ( C /C++ ) engineer working with microcontrollers.
I m trying to adopt good, standardized practices for maintaining projects - personal and professional.

I was wondering, if I can use standard git flow + commitizen as a SOP for commiting my changes to the repo.
Are there any drawbacks to doing so?

I was hoping a good samaritan might indulge a noobs request and handhold me to use this tool.
Nothing exotic or esoteric, a standard conventional commit style (which I understand is the default) will be a good starting point.

As I understand, getting started with commitizen is as simple as pip install and running "cz init" in my repo.
As I have mentioned I come from a C/C++ background. 
Can I trouble the kind folks here to give a walkthrough on how to progress from there..

How do I setup a tag, version number and so forth?

A basic example will be sufficient to get started. I can experiment and learn from there.

Thanks in advance and I apologize if this seems like a rather irrelevant question in this place.

**Comment by Woile** [comment]
The question doesn't bother at all, glad to see adopted elsewhere.

You are done after those 2 commands haha.

The workflow would be:

```
$ pip install commitizen==2.4.0  # I'm pinning to the latest version here, you can always install the latest but if it's 3.0 it owuld break
$ cz init # follow the steps presented
$ cz bump --changelog  # this will bump the version and create and track the changelog
```

everytime you want to make a new release, just run `cz bump --changelog`

Some recommendations:
- [writing commits](https://commitizen-tools.github.io/commitizen/tutorials/writing_commits/)
- learn the idea behind [semver](https://semver.org/)

You can run this [demo](https://gist.githubusercontent.com/Woile/4c13a7c9f64c81fbb18169bec8e883c7/raw/d444dd881b330193f3393da7cbe6232ccb145a6b/cz-example.sh) to see how it works if you are on linux or mac:

```
wget -o /tmp/cz-example.sh https://gist.githubusercontent.com/Woile/4c13a7c9f64c81fbb18169bec8e883c7/raw/d444dd881b330193f3393da7cbe6232ccb145a6b/cz-example.sh
chmod +x /tmp/cz-example.sh
/tmp/cz-example.sh
```
the scripts assumes `cz` is installed globally.
it does everything in the `tmp` folder.

Let us know if u have more doubts!

**Comment by krish2487** [comment]
Wow!! That was a fast reply!! :-)

👍 

It is very nice of you to forward the relevant docs for someone like me. 
I ll go through and experiment for now. :-)

I will post any further questions that may arise, as I progress.

I am closing this question for now. 
Thank you so much again for the help! 
PS: I cant stress this enough, you guys are awesome!! The utility is awesome and so are you guys! 
Cheers!! :-)
