### ISSUE TITLE
Use heredoc for commit message

### ISSUE THREAD

**Issue by blaggacao** [commitizen-tools/commitizen#275]
## Description
`|` is not very compfortable to properly style a paragraph.

## Possible Solution
Use heredocs proper or any suitable equivalent, instead.

## Related Issue
#264

**Comment by Lee-W** [comment]
We'll probably implement something supported by https://github.com/commitizen-tools/commitizen/issues/264#issuecomment-876797865. (Still in progress)
Thus, I'll close this issue. Feel free to reopen it or discuss on https://github.com/commitizen-tools/commitizen/issues/264
