### ISSUE TITLE
Commitizen tries to create a tag eventhough no increment is detected and it fails with tag already exists.

### ISSUE THREAD

**Issue by Rio** [commitizen-tools/commitizen#280]
## Description
Whenever something is merged in our main branch commitizen checks if a version bump is required. Usually it's fine but whenever no increment is detected it will still try to create a tag while it shouldn't. Because the version is still the same and matches a previously created tag the command and the pipeline fails. Am I just not handling this correctly? I can't imagine nobody has run into this yet.

## Steps to reproduce
Make sure a git tag exists that matches the version commitizen is tracking. Create a new commit that shouln't trigger a version bump then run `cz bump` and watch it fail.

```
bump: version 0.10.2 → 0.10.2
tag to create: v0.10.2
increment detected: None
fatal: tag 'v0.10.2' already exists
```

## Desired behavior
I think it shouldn't try to create a git tag if no change is detected.

**Comment by Woile** [comment]
I think this could be solved by adding a [tag_exist](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/git.py#L114) check [in here](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/bump.py#L110).

I'm a bit busy at the moment, but once I find some time I'll tackle some current issues.

**Comment by Lee-W** [comment]
I think this one also relates to #118 . In my own project, I use [this error code](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/exceptions.py#L14) to avoid pipeline failed. I'll be a biy busy recently. Will see whether I can have more time to solve isssues on November.

**Comment by christian-hawk** [comment]
@Woile plz check #285 if possible, related to #284
