### ISSUE TITLE
pre-commit hook fails on feat! (doesn't allow exclamation point)

### ISSUE THREAD

**Issue by evanstoddard23** [commitizen-tools/commitizen#283]
## Description
Commits like `feat!: describing my breaking change` fail at the pre-commit hook

## Steps to reproduce
1. Make a breaking change
2. Include the pre-commit hook from the readme in your pre-commit-config.yaml file and install hooks
3. Try to commit with a message like `feat!: breaking change`

## Current behavior

```sh
commitizen check.........................................................Failed
- hook id: commitizen
- exit code: 14

commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "feat!: breaking change"
pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?:(\s.*)
```

## Desired behavior
Check should pass according to https://www.conventionalcommits.org/en/v1.0.0/ rules

## Environment

- commitizen version: 2.4.1
- python version: 2.7.16
- operating system: Darwin

**Comment by Woile** [comment]
Nice catch, I think the [pattern used by check](https://github.com/commitizen-tools/commitizen/blob/5c0dd546866f2bd2ab6b4ecd27035441b7b4692b/commitizen/cz/conventional_commits/conventional_commits.py#L179) should be similar to [commit_parser](https://github.com/commitizen-tools/commitizen/blob/5c0dd546866f2bd2ab6b4ecd27035441b7b4692b/commitizen/defaults.py#L33)

I'll try to take a look next weekend.
