### ISSUE TITLE
ImportError: cannot import name 'BaseCommitizen' and others in files starting with `cz_`

### ISSUE THREAD

**Issue by andres-fr** [commitizen-tools/commitizen#287]
## Description

As it can be seen in the following line, all files present in the Python environment whose filename begins with `cz_` will be discovered and iteratively loaded by `commitizen`. Unfortunately this also includes files that aren't in the scope of commitizen but happen to be in `PYTHONPATH`:

https://github.com/commitizen-tools/commitizen/blob/14b6c382ff96e37ba118ba1b75073b0d2313ee91/commitizen/cz/__init__.py#L18

The reaction is very cryptic and can lead to long and frustrating debugging sessions. Fortunately it is known that the "cannot import" message is linked to circular dependencies, e.g. see https://stackoverflow.com/a/746655

Just importing `commitizen` doesn't break, but further recursive imports down the package trigger the issue.

## Steps to reproduce
1. Create a file starting with `cz_...` and call e.g. ` from commitizen.commands.bump import Bump`
2. Run that file with the python interpreter, making sure that the file's directory is in `sys.path`
3. The import will trigger an `ImportError` that is **internal to commitizen** like the one in the title. 

## Current behavior
Code that runs from interactive CLI doesn't run from script

## Desired behavior
Code that runs on CLI should also run on script.

## Environment

python --version Python 3.6.12 :: Anaconda, Inc.
python3 -c "import platform; print(platform.system())"

- commitizen version: 2.4.2
- python version: 3.6
- operating system: Ubuntu

**Comment by andres-fr** [comment]
I guess the main idea here is that a library shouldn't discover and load  files from the python path by regex. That can be very tricky to find and could be even more problematic at other levels e.g. security. At the moment I'm kind of saturated and don't have any meaningful quickfix, apart from the obvious *Don't ever name any Python file starting by `cz_`*

**Comment by Woile** [comment]
Sorry if it's a big frustrating :disappointed: , the plugin system can be improved, but it's based on a simple version of [flask extension system](https://flask.palletsprojects.com/en/1.1.x/extensiondev/).

There should be a way to avoid this kind of errors, I'm open to enhancements

**Comment by andres-fr** [comment]
Thanks for your answer, I would have to analyze more the plugin system to propose something more specific.
What do you think about this plugin architecture?

https://amir.rachum.com/blog/2017/07/28/python-entry-points/

**Comment by Lee-W** [comment]
I browse through the article you shared but not yet try it, but it looks like a good approach to me. Also, I just found how poetry can support similiar functionality. https://python-poetry.org/docs/pyproject/#plugins

**Comment by Woile** [comment]
Interesting, I like it, seems quite intuitive. We'd have to update the template as well. Keep in mind, this would introduce a breaking change, but it's fine by me.

**Comment by andres-fr** [comment]
If you guys are comfortable with that I could give a hand in the next few weeks (we could do a hackathon or something) and try to refactor the CLI/plugin section. Only changes that you approve of course

**Comment by Lee-W** [comment]
It sounds good to me. I just add a `3.0.0` tag to this issue.

**Comment by Woile** [comment]
I'm in, great idea! Let's coordinate a date

**Comment by Woile** [comment]
21 November 2020 I'll be joining to pycon argentina with a sprint for commitizen, hope you can join!

**Comment by andres-fr** [comment]
Sounds good, I can't promise it but will mark the date :memo:. In any case this sounds amazing for the project! Looking forward to what comes out of it

**Comment by Lee-W** [comment]
Hi @andres-fr , https://github.com/commitizen-tools/commitizen/pull/480/files seems to solve this issue. Could you please check again? As this issue also proposed something worth enhancing, @Woile do you think we should keep this one open or create a new one for tracking that stuff?

**Comment by Woile** [comment]
I think we should create a new ticket, I still want to refactor the plugin system

**Comment by andres-fr** [comment]
Hey, sorry for dropping the ball here. I'm happy to close this one if you think that is appropriate!

**Comment by Lee-W** [comment]
Hi all, I've created a new issue for tracking this https://github.com/commitizen-tools/commitizen/issues/495. Let's close this one
