### ISSUE TITLE
message_template description inaccurate?

### ISSUE THREAD

**Issue by bradym** [commitizen-tools/commitizen#288]
## Type

* [x] Content inaccurate
* [ ] Content missing
* [ ] Typo

## URL
https://commitizen-tools.github.io/commitizen/customization/

## Description

The description for `message_template` currently reads (emphasis mine):

> The template for generating message from the given answers. message_template should either follow the string.Template or Jinja2 formatting specification, and all the variables in this template should be defined in name in questions. **Note that Jinja2 is not installed by default.** If not installed, commitizen will use string.Template formatting.

It seems the bold sentence is actually backwards as Jinja2 _is_ installed by default as it is [defined as a dependency](https://github.com/commitizen-tools/commitizen/blob/14b6c382ff96e37ba118ba1b75073b0d2313ee91/pyproject.toml#L54).

I'm happy to submit a PR to fix, but wanted to confirm the issue first.

**Comment by Woile** [comment]
Go ahead! Thanks!
