### ISSUE TITLE
Is there a way to make this work in a monorepo with polygot services?

### ISSUE THREAD

**Issue by rlam3** [commitizen-tools/commitizen#289]
Is there a way to make this work in a monorepo with polygot microservices? If there is I don't see it in the documentation. I'd love to help out on this or find a workaround for it. Thanks!

**Comment by Lee-W** [comment]
I'm not sure I get your question. What's the problem you encounter when you try to do so? We'll need python to run/install `commitizen` but it doesn't have to be a python project.

**Comment by Woile** [comment]
What kind of issue are you having? I think `commitizen` can be used for that purpose but I don't think it can handle all situations well.
A simple implementation, given this monorepo:
```
monorepo/
├── .cz.toml
├── express-app
│   └── package.json
├── service-rs
│   └── cargo.toml
└── web-py
    └── pyproject.toml
```
In this example there's a rust, node and python projects.

You'd configure `.cz.toml` at the root of it with the `version_files` option configured like this:
```
[tool.commitizen]
version = "0.1.0"
version_files = [
    "web-py/pyproject.toml:version",
    "express-app/package.json:version",
    "service-rs/cargo.toml:version"
]
```

Then running `cz bump --changelog` would create the tag and would generate **one** changelog at the root of the project `monorepo/CHANGELOG.md`. And all of the packages version would be updated.
You can use the `scope` from conventional commits to highlight which service is the change for, or built a custom cz rule.

That's a simple implementation for a monorepo. What other features would you expect?
