### ISSUE TITLE
Add configuration file option for changelog --start-rev/--incremental

### ISSUE THREAD

**Issue by janw** [commitizen-tools/commitizen#291]
## Description
When adopting commitizen and Conventional Commits on a long-running existing project, there are many old commits that do not follow the formatting spec. Thus running `cz changelog` always requires the `--start-rev` or `--incremental`  parameter to be set so that it only considers commits after a certain point in time and not try to parse poorly formatted commit messages.

## Possible Solution

1. Introduce a configuration flag à la `changelog_incremental` (defaulting to False to mimic current behavior), that when set to True would have the same effect as providing the `--incremental` flag.
1. Introduce a configuration flag à la `changelog_start_rev` that can hold a Git rev from which to always start creating the changelog.

---

Again, if this is something the maintainers agree is a useful feature, I'd be happy to provide a PR for it.

**Comment by Lee-W** [comment]
Thanks for your suggestion! I like this idea!

**Comment by Woile** [comment]
I'm in for this change, I like it :muscle:

**Comment by Lee-W** [comment]
As #294 is merged, I'll close this one. Thanks for the contribution 🙏
