### ISSUE TITLE
Bump: Optional Commit and Tag

### ISSUE THREAD

**Issue by marcossantiago** [commitizen-tools/commitizen#298]
## Description
It would be very great if the `bump` command accepted the Commit and Tag to be optional instead. 

## Possible Solution
Add the option in the configuration:
```
commit = true
tag = true
```

## Additional context
My workflow is usually require squashing and merging Pull Requests, making the tag in a branch not so useful. So I haveI have to re-tag the commit in the master branch.

**Comment by Lee-W** [comment]
In my workflow, I usually do `cz bump` after the branch is merged into master branch.

Currently, commitizen use git tag to find which commit is the previous release. If git tag is not created, commitizen will not be able to bump version correctly

**Comment by Woile** [comment]
As Lee pointed out, the idea is to run `cz bump` on your main branch. If you run it on your "work" or "feature" branch, you may have issues, like 2 people creating the same version, because both were creating features.

Anyway, you may find useful this command which doesn't create a tag nor a commit, just increments the version:

```cz bump --files-only```

**Comment by marcossantiago** [comment]
Thanks for the input. The `cz bump --files-only` seems to be the right approach here, but it seems it does not update the ` pyproject.toml`. Is that correct ?

**Comment by marcossantiago** [comment]
It seems to be the case...when using `files-only` the command exits before the toml config is written as per this [line](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/bump.py#L162). 

What do you think of changing the order to write the toml config before it exits [here](https://github.com/commitizen-tools/commitizen/blob/ae03624d512557804d86bcfbe8497035bb27ed74/commitizen/commands/bump.py#L148) ?

**Comment by marcossantiago** [comment]
@Woile @Lee-W I have created a PR with a simple change.
