### ISSUE TITLE
Changelog is creating wrong sections when parsing commits with multiple statements

### ISSUE THREAD

**Issue by lyz-code** [commitizen-tools/commitizen#301]
## Description

`cz changelog` is creating the wrong sections when parsing commits with several statements.

It will be nice if `cz changelog` could understand this as two changes.

## Steps to reproduce
From a clean git repository:

1. Create a commit with message `feat: add file`
2. Create another commit with message:

```
fix: something broken

Fix explanation

feat: new feature

New feature explanation
```
3. Execute `cz changelog --dry-run`

## Current behavior

Two *feat* sections were created: `Feat` and `feat`.

```
## Unreleased

### Fix

- something broken

### feat

- new feature

### Feat

- add file
```

## Desired behavior

Create one `Feat` section.

```
## Unreleased

### Fix

- something broken

### Feat

- add file
- new feature
```

## Environment

- commitizen version: 2.6.0
- python version: 3.7.3
- operating system: Linux

**Comment by Lee-W** [comment]
Thanks for your report! I've confirmed this bug.

**Comment by edvm** [comment]
@Woile If you think it's ok, I'll be working on this one.

**Comment by lyz-code** [comment]
@edvm have you dived into the problem? I was thinking of fixing it myself, but I don't want to step on your work.

**Comment by Woile** [comment]
This is no longer happening, just tested, feel free to open in case it happens again.
Remember to install the latest version.
