### ISSUE TITLE
I/O exception and does not commit

### ISSUE THREAD

**Issue by LukeSavefrogs** [commitizen-tools/commitizen#318]
## Description
Prints an I/O exception and continues. At the end doesn't commit to git but only prints the commit text

## Steps to reproduce
Type `cz commit` or `cz c` and continue

## Current behavior
```PowerShell
→ Test_Mattutini_PICO: [master ≡ +0 ~2 -0 !]› cz c
? Select the type of change you are committing fix: A bug fix. Correlates with PATCH in SemVer
? What is the scope of this change? (class or file name): (press [enter] to skip)
 C2C

Unhandled exception in event loop:
  File "c:\python38\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] Operazione di I/O terminata a causa dell'uscita dal thread oppure della richiesta di un'applicazione
Press ENTER to continue...
? Write a short and imperative summary of the code changes: (lower case and no period)
```

## Environment

- commitizen version: 2.11.1
- python version: Python 3.8.3
- operating system: Windows

**Comment by Woile** [comment]
I think it's related to https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1023
And happens because of windows and because of our dependency with `prompt-toolkit`.
Seems like a python bug: https://github.com/python/cpython/commit/8d68e59f11267ded765d4af6d71a49784a12fad5

**Comment by Bogay** [comment]
According to this comment, It seems that this bug is fixed at python? But in a newer version (e.g. 3.8.7)
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1023#issuecomment-776072636

At least it works on my windows (I use python 3.8.7 instead of 3.8.3)

**Comment by Lee-W** [comment]
@LukeSavefrogs in this case, I don't think we'll be able to fix the older version on our side. 
@Bogay Could you please add a FAQ page and add it as part of the documentation so that others will know they need to upgrade their python version for this to work? Thanks!

**Comment by Bogay** [comment]
@Lee-W I found there exist 2 FAQ section: one in README and one in documentation, and the documentation one covers README one. Should I also removed the README's FAQ secion? (or leave the documentation link there)

**Comment by Lee-W** [comment]
Let's move all the FAQ to https://commitizen-tools.github.io/commitizen/faq/ and add a link to README

**Comment by Bogay** [comment]
@Lee-W As #431 merged, maybe this issue can be closed?

**Comment by Lee-W** [comment]
Sounds good! Let's me close it
