### ISSUE TITLE
Github Slack Integration

### ISSUE THREAD

**Issue by ShaneMalachow** [commitizen-tools/commitizen#327]
Would it be possible to add the Github Slack integration to this repo? My team tries to follow our dependencies releases via Slack notifications, so enabling the integration allows us to subscribe to events.

**Comment by Lee-W** [comment]
Hi, you could implement a custom slack hook through`changelog_hook` See [Custom changelog generator](https://commitizen-tools.github.io/commitizen/customization/#custom-changelog-generator) for more information.

**Comment by ShaneMalachow** [comment]
No I don't need integration to Slack via commitizen itself, I was referring to Github's Slack app. It requires implementation on the Github repo itself for others to get events from Github broadcast to Slack channels.

**Comment by Lee-W** [comment]
I'm afraid I don't quite get it. Could you please provide more context? like the documentation of the GitHub slack app you mention

**Comment by ShaneMalachow** [comment]
https://slack.github.com/

Basically the organization can enable the official github slack integration, which allows publishing Github events to Slack workspaces. Other workspaces can also subscribe to events for repos that use this integration, which my org uses to track our dependencies when they publish new releases. Those messages automatically port to our slack channel for things like hashicorp's products or golangci-lint

**Comment by Lee-W** [comment]
Does that mean we'll need to have a slack workspace? If so, we don't have one at this moment. I'm not sure whether we'll have one. @Woile What do you think?

**Comment by Woile** [comment]
I don't quite get it also, sorry @ShaneMalachow

If I had to guess I'd say he wants to receive their releases in their slack. For that we don't have to enable slack on our repo. But we do have to provide a way to create a release in an easier way (my idea was to print the incremental changes to the standard output, so it can be saved in a file, or piped to another command).

My understand is that If we enable slack on our repo, (potentially) you will know when commitizen makes a new release. Is that what you expect @ShaneMalachow ?

**Comment by ShaneMalachow** [comment]
Yup, your last statement is accurate to my goal. However, we've recently discovered Github provides Atom feeds for all repos by default, so this is no longer needed for my use case. Thanks for the effort and quick responses though!
