### ISSUE TITLE
Is this project affiliated with the Commitizen JS project?

### ISSUE THREAD

**Issue by ShaneKosieradzki** [commitizen-tools/commitizen#328]
## Type

* [ ] Content inaccurate
* [x] Content missing
* [ ] Typo

## URL
[Commitizen JS Repo](https://github.com/commitizen/cz-cli)

## Description
This project seems to be functionally the same as the Commitizen JavaScript project I linked above except written in Python. I personally have more experience in Python so I am more inclined to use this project. But given their similarities, it would be nice to know how these projects relate to each other, things like:

* Are these projects affiliated in any official way? If so what?
* Does this project seek to accomplish something different than the JS project?
* Is there anything this project can do that the JS project cannot or vice versa?

I understand that this question doesn't pertain to this project per se, but given that both projects share the name "Commitizen" and that both projects show up in Google searches, this ambiguity obfuscates the landscapes and makes it more difficult to adopt this technology.

Thank you for taking the time to answer this slightly tangental question.

**Comment by Woile** [comment]
They are not affiliated.
They are used for similar purposes, parsing commits, generating changelog and version I presume.
One is written in python to make integration easier for python projects and the other serves the JS packages.

I think they differ in design a bit, I'm not sure if cz-js does any of this, as I got lost trying to use it, but these are some of the stuff you can do with this repo (python's commitizen):
- create custom rules, version bumps and changelog generation, by default we use the popular conventional commits.
- single package, install one thing and it will work (cz-js is a monorepo, but you have to install different dependencies AFAIK)
- pre-commit integration
- works on any language project, as long as you create the `.cz.toml` file.

Regarding the name, cz-js came first, they used the word commitizen first. When I created the project originally, I remember reading "be a good commitizen", and I thought it was just a cool word that made sense, and this would be a package that helps you be a good "commit citizen". I'm not sure if they mind if we use it now that I think of 😅

**Comment by ShaneKosieradzki** [comment]
Thanks for the quick response. This information is helpful to understand the current landscape!
