### ISSUE TITLE
(Optional?) support for annotated tags

### ISSUE THREAD

**Issue by SpokeyWheeler** [commitizen-tools/commitizen#329]
## Description
Currently, lightweight tags are generated by `cz bump`. This means you have to remember to push the tag separately from the commit, and also means you can't use `--follow-tags`.

## Possible Solution
I did this in my clone, but I genuinely don't know if it's anything more than a hack:

I changed [this line](https://github.com/commitizen-tools/commitizen/blob/99d4024e0d80a00d1ff1439b5977d447b6e82e70/commitizen/git.py#L49) from
`    c = cmd.run(f"git tag {tag}")`
to
`    c = cmd.run(f"git tag -a -m '{tag}' {tag}")`

DISCLAIMER: I wouldn't know Python if it ran me over in a bus. But it seemed to work!

## Additional context
N/A

## Related Issue
I didn't find anything related.

**Comment by Woile** [comment]
There's an open (abandoned) PR for annotated tags: https://github.com/commitizen-tools/commitizen/pull/272
Feel free to add corrections and re-submit it. I'll try to pick it up but I'm quite busy atm

**Comment by SpokeyWheeler** [comment]
Honestly, I've never written any Python in anger before. I don't feel comfortable with starting with this! :-)

**Comment by Woile** [comment]
No worries, thanks for sharing. I'll try to push this change in the coming weeks 💪🏻

**Comment by cliles** [comment]
@Woile - To help speed this up (to maybe days instead of weeks), I went ahead and looked at #272 and "adopted" it for #332.

**Comment by SpokeyWheeler** [comment]
Thanks guys!

**Comment by cliles** [comment]
@Woile  and @SpokeyWheeler  - #332 is merged, this issue can be closed.

**Comment by SpokeyWheeler** [comment]
Awesome! Thank you so much! 🎉🎉
