### ISSUE TITLE
Auto-run Commitizen on `git commit`

### ISSUE THREAD

**Issue by ShaneKosieradzki** [commitizen-tools/commitizen#330]
## Description
To help with the adoption of Commitizen by project contributors who are unfamiliar with Commitizen, it would be nice if `cz commit` could run automagically whenever a user tries to `git commit`. That is, `cz commit` should transparently replace `git commit`.

## Possible Solution
Your project is already using `pre-commit` for `cz check` (🎉 yeah! 🎉). It would be nice if there were a `pre-commit` hook that could run on `prepare-commit-msg`.

## Additional context
[pre-commit project](https://pre-commit.com/index.html)

**Comment by ShaneKosieradzki** [comment]
Also, you should add a [pre-commit badge](https://pre-commit.com/#badging-your-repository) to this repo.

**Comment by Lee-W** [comment]
#250 works on something relates to it but I failed to run it on my local machine.

**Comment by Lee-W** [comment]
As this is a similar issue to #249, let's close this one and discuss there
