### ISSUE TITLE
Wrap lines longer than some limit

### ISSUE THREAD

**Issue by lovetoburnswhen** [commitizen-tools/commitizen#331]
## Description
Long lines in the commit description should be automatically wrapped to comply with tools like [`gitlint`](https://github.com/jorisroovers/gitlint)

Similar to https://github.com/commitizen/cz-cli

**Comment by Lee-W** [comment]
Interesting, I didn't know cz-cli provides such functionality. I'll take a look when I have time

**Comment by Lee-W** [comment]
Just notice this is a similiar one to https://github.com/commitizen-tools/commitizen/issues/191. Will close this one. Let's discuss there
