### ISSUE TITLE
A generator that respects keep-a-changelog change types

### ISSUE THREAD

**Issue by dmyersturnbull** [commitizen-tools/commitizen#335]
## Description

First off, this is a fantastic project. I only learned about it recently. Thanks for all your hard work.

[keep-a-changelog 1.0](https://keepachangelog.com/en/1.0.0/) has these change types:
- Added
- Changed
- Deprecated
- Removed
- Fixed
- Security

Commitizen puts "dropped support" in the changelog "Feat", and that doesn't conform with types.

Conventional commits appears to allow custom commit types.
Perhaps there could be a built-in style that maps directly to the keep-a-changelog types?

## Possible Solution

I started by trying this:

```
bump_pattern = "^([Aa]dd(?:ed)?|[Cc]hanged?|[Dd]eprecated?|[Rr]emoved?|[Ff]ix(?:ed)?|[Ss]ecurity)?"
```

But I didn't know how to handle `!` / `BREAKING CHANGE` in `bump_pattern`.

**Comment by Woile** [comment]
This is our current mapping: https://github.com/commitizen-tools/commitizen/blob/master/commitizen/cz/conventional_commits/conventional_commits.py#L35

I think your best bet is to make a new cz like matching keep a changelog using our template: https://github.com/commitizen-tools/commitizen_cz_template

Out current changelog is an opinionated version of conventional changelog:
https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

**Comment by dmyersturnbull** [comment]
Thanks for the clarification!

**Comment by Woile** [comment]
No problem, feel free to re-open this issue or open a new one if you need more help!

And if you do create it you can add it to the third party section: https://commitizen-tools.github.io/commitizen/third-party-commitizen/
