### ISSUE TITLE
2.15.0 changelog didn't include the changes

### ISSUE THREAD

**Issue by Woile** [commitizen-tools/commitizen#351]
## Description

Last [CHANGELOG](https://github.com/commitizen-tools/commitizen/blob/master/CHANGELOG.md) didn't include the changes for `v2.15.0`

Investigate why it is not picked up.
I did some debugging and the commit doesn't appear, even before generating the changelog.
I placed a pdb here commitizen/commands/changelog.py:105 and the `commits` don't include the latest one

## Steps to reproduce

1. Run `cz changelog`
2. Observe CHANGELOG.md

## Current behavior

A commit which complies with the format is being skipped

## Desired behavior

All the commits complying with the format should be included

## Environment

- commitizen version: `v2.15.0`
- python version: `3.7.6`
- operating system: linux / Ubuntu

**Comment by Lee-W** [comment]
It seems to happen after 2.14.2.

**Comment by Lee-W** [comment]
Some of our git commits have "\n" at the end of the commit file while some don't. This happens when a pull request is merged.

e.g., 

```
d09841655e36c70fb6fd2624fc8325dfe0ab0b83
bump: version 2.15.0 → 2.15.1
GitHub Action
action@github.com
----------commit-delimiter----------
3a4d13f3e1af8882b38fe2e398a72073e402c9a2
Merge pull request #353 from loonghao/change_read_mode
...
...
fix(config): change read mode from `r` to `rb`----------commit-delimiter----------
4671258523cf331904080753c9d83c3cf8b55388
fix(config): change read mode from `r` to `rb`
...
...
----------commit-delimiter----
```

**Comment by Lee-W** [comment]
I'm now looking into it but encounter some failed tests. Will send a pr these days

**Comment by Woile** [comment]
Merged and fixed.
For some reason the latest attempt to generate didn't work. But I pulled the latest and it did work, so I guess no worries.
I pushed a new commit to master which includes the previous not generated versions in the CHANGELOG.
