### ISSUE TITLE
Confirm type question didn't work

### ISSUE THREAD

**Issue by jenhausu** [commitizen-tools/commitizen#366]
## Description
The confirm type question didn't work, even when I answer the question with no, the git still commits.

**Screenshots**
<img width="730" alt="截圖 2021-04-04 上午4 07 59" src="https://user-images.githubusercontent.com/5162963/113490244-6a890980-94fb-11eb-852d-74b39deb4e2a.png">

## Environment

- commitizen version: 2.17.0
- python version: 3.9.2
- operating system: Mac OS Big Sur 11.2.2
- computer: MacBook Pro (13-inch, M1, 2020)

**Comment by Lee-W** [comment]
Could you please run `which cz`? It doesn't look like our commitizen.

**Comment by jenhausu** [comment]
If so that would be embarrassing. I use the conventional template.
This is what I get:`/usr/local/bin/cz`

**Comment by Lee-W** [comment]
What about the content of `/usr/local/bin/cz`?

**Comment by jenhausu** [comment]
It's what I run `which cz` return.

**Comment by Lee-W** [comment]
What I meant was `cat /usr/local/bin/cz`.

**Comment by jenhausu** [comment]
Sorry for didn't see your question clearly, this is the content:

```
#!/usr/local/Cellar/commitizen/2.17.0/libexec/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from commitizen.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by Lee-W** [comment]
Is there any configuration for commitizen in your repo? Or is there any virtual environment activated? Most of your steps look reasonable. I'm still trying to reproduce the error you report.

**Comment by jenhausu** [comment]
This is my configuration file, I use ` .cz.toml`
```
[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{change_type}}[{{scope}}]: {{title}}\n\n{% if body %}{% endif %}"

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [
{value = "feat", name = "feature: A new feature."},
{value = "fix", name = "bug fix: A bug fix."},
{value = "refactor", name = "refactor: A code change that restructuring an existing body of code without changing its external behavior."},
{value = "perf", name = "perf: A code change that improves performance"},
{value = "test", name = "test: Adding missing or correcting existing tests"},
{value = "chore", name = "chore: updating grunt tasks."},
{value = "style", name = "style: formatting."},
{value = "build", name = "build: Changes that affect the build system or external dependencies"},
{value = "docs", name = "docs: Documentation only changes"},
{value = "ci", name = "ci: Changes to our CI configuration files and scripts"}]
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "scope"
message = "What is the scope of this change? (class or file name):"

[[tool.commitizen.customize.questions]]
type = "input"
name = "title"
message = "Write a short and imperative summary of the code changes: (lower case and no period)."

[[tool.commitizen.customize.questions]]
type = "input"
name = "body"
message = "Provide additional contextual information about the code changes:"

[[tool.commitizen.customize.questions]]
type = "confirm"
name = "confirm"
message = "Are you sure you want to proceed with the commit above?"
```

**Comment by Lee-W** [comment]
Ah, I thought you were using `cz_convention`. This is not actually a bug. It's just not supported at this moment. You might want to use https://commitizen-tools.github.io/commitizen/customization/#2-customize-through-customizing-a-class to achieve what you want.

**Comment by Lee-W** [comment]
The `confirm` type in toml can only be used in the commit template. e.g, `"{{change_type}}:{% if show_message %} {{message}}{% endif %}"` It can not be used to do any other operation.

**Comment by Lee-W** [comment]
As this isn't a bug, I'll mark this one as closed.

**Comment by jenhausu** [comment]
Thanks a lot, That explain everything.
