### ISSUE TITLE
Question Flow Map

### ISSUE THREAD

**Issue by jenhausu** [commitizen-tools/commitizen#368]
## Description
It is possible to make a question flow map? Base on what user answers to show different following questions.

## Possible Solution
Maybe a new kind of title parameter like this:
`[[tool.commitizen.customize.questions.<parent question's name>]]`

which indicates what parent question it follows.

**Comment by Lee-W** [comment]
I think it's can be done through https://commitizen-tools.github.io/commitizen/customization/#2-customize-through-customizing-a-class.

**Comment by jenhausu** [comment]
Thank you, I'll give it a try.

**Comment by Lee-W** [comment]
As no further comments have been added, I'll close this one. Feel free to reopen it if you find the solution didn't solve your problem
