### ISSUE TITLE
changelog generator got messed up with annotated tags

### ISSUE THREAD

**Issue by Trim21** [commitizen-tools/commitizen#378]
## Description
 Tags are mssing in generated tags

## Steps to reproduce
```bash
git clone https://github.com/Trim21/transmission-rpc.git

cd transmission-rpc

pip install -U commitizen

cz changelog

git tag -l

```

## Current behavior

annotated tags like `v3.2.2` and `v3.2.1` are  missing from changelog

## Desired behavior

generate a changelog with all kind of tags

## Environment

- commitizen version: 2.17.4
- python version: 3.8.9
- operating system: Windows

**Comment by Woile** [comment]
Hello @Trim21 I just confirmed this bug, I think we have to run the `get_tags` function with `creatordate` instead of `committerdate`. I'll try to submit a patch soon. Thanks 👍🏻 

```
git tag --format="%(refname:lstrip=2)---inner_delimiter---%(objectname)---inner_delimiter---%(creatordate:format:%Y-%m-%d)\n" --sort=-creatordate
```

**Comment by Trim21** [comment]
> Hello @Trim21 I just confirmed this bug, I think we have to run the `get_tags` function with `creatordate` instead of `committerdate`. I'll try to submit a patch soon. Thanks 👍🏻
> 
> ```
> git tag --format="%(refname:lstrip=2)---inner_delimiter---%(objectname)---inner_delimiter---%(creatordate:format:%Y-%m-%d)\n" --sort=-creatordate
> ```

Thanks. There's a bug here but this won't fix this issue
.

The reason is that annotated tag's ref is not same with it's commit.
