### ISSUE TITLE
Improve selection prompt UX; Add single-character shortcut keys mnemonics 

### ISSUE THREAD

**Issue by webstoreportal** [commitizen-tools/commitizen#380]
We should aim for a quick win in keystroke reduction here without detracting from existing slow prompts.

* Allow user to confirm an option by first-letter (or second letter, in name clash) as a keyboard shortcut

https://github.com/commitizen-tools/commitizen/blob/32916abd2210e8c2c8852b42f51fcbbb01181f4b/commitizen/commands/commit.py#L50

https://github.com/commitizen-tools/commitizen/blob/32916abd2210e8c2c8852b42f51fcbbb01181f4b/commitizen/cz/conventional_commits/conventional_commits.py#L42

per Python Questionary dependency docs 
https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.shortcut_key

Slightly surprised no one has taken the opportunity to improve developer quality of life here. In commitizen-tools and cz-cli. Is there another alternative workflow we are missing out on?

Balancing forced verbose arrow navigation prompts vs command-line direct parsing

Adding the keyboard shortcut could be a happy medium solution

**Comment by webstoreportal** [comment]
Wonder if this would affect customisable templates elsewhere

https://commitizen-tools.github.io/commitizen/customization/#2-customize-through-customizing-a-class

**Comment by Lee-W** [comment]
Hi @webstoreportal Thanks for the suggestion!
@Woile I'm good with this feature. What do you think?

**Comment by Woile** [comment]
We have key shortcuts now, I think this PR can be closed, what do you think?

**Comment by Lee-W** [comment]
Yep, let's close it
