### ISSUE TITLE
bug(cz_conventional_commits): cz check's schema_pattern is inconsistent with conventional commits spec

### ISSUE THREAD

**Issue by shifqu** [commitizen-tools/commitizen#381]
## Description
The `schema_pattern` used in ConventionalCommitsCz allows for a `!` before the scope, while the [spec](https://www.conventionalcommits.org/en/v1.0.0/#specification) states
> 13. If included in the type/scope prefix, breaking changes MUST be indicated by a ! immediately before the :.

## Steps to reproduce
1. Run `cz -n cz_conventional_commits check -m "feat!(scope): message"`
2. Observe the (wrongly) successful validation
3. Run `cz -n cz_conventional_commits check -m "feat(scope)!: message"`
4. Observe the (wrongly) failed validation

## Current behavior
- Command in 1) validates successfully
- Command in 3) fails validations

## Desired behavior
- Command in 1) to fail validation (as the `!` is not right before the `:`.)
- Command in 3) to validate successfully (as it aligns with the conventional commits spec)

## Environment
- commitizen version: 2.17.4
- python version: 3.8.8
- operating system: Darwin (macOS 11.2.3)

**Comment by shifqu** [comment]
@Woile I can take a stab at it, if you like. I feel like the change is minor.

**Comment by Woile** [comment]
Of course, go ahead.
