### ISSUE TITLE
Is there any way to export changelog for updating version

### ISSUE THREAD

**Issue by pratikbalar** [commitizen-tools/commitizen#387]
## Description
assume that cz will going to bump 1.0.0 -> 2.2.0 so is there any way i can get change log between 1.0.0 -> 2.2.0  not the whole

## Possible Solution
NA

## Additional context
NA

## Related Issue
NA

**Comment by Lee-W** [comment]
Try `cz changelog --incremental --dry-run`

**Comment by pratikbalar** [comment]
Yup just seen that in document :sweat_smile: 

thanks for fast as flash replay
