### ISSUE TITLE
Neither body nor footer do appear in the commit message

### ISSUE THREAD

**Issue by ALABSTM** [commitizen-tools/commitizen#393]
## Description

Neither the message body (containing the longer description paragraph) nor the footer (containing bug identifiers) do appear in the commit message once the commit is done and the commit message is displayed on the console using the `git log` command or using a GUI-based tool.

## Steps to reproduce

1. Install Commitizen as an extension of **Visual Studio Code**.
2. Invoke Commitizen by pressing `ctrl`+`shift`+`p` and prepare your commit message (fill the "longer description" paragraph). 
3. Once finished, your changes will be automatically committed.
4. On the Git output console type `git log`. You can also use a GUI-based tool such as Tortoise (see screenshots below).

## Current behavior

Neither body nor footer appear as part of the commit message.

```
<type>[optional scope]: <description>

[optional body] <!-- The body does not appear -->

[optional footer(s)]  <!-- The footer does not appear -->
```

**Screenshots**

![image](https://user-images.githubusercontent.com/46019491/123124536-ac14bb00-d43f-11eb-9842-093d585ab7c9.png)

## Desired behavior

Both body and footer should appear as part of the commit message.

## Environment

- commitizen version: 0.14.1
- python version: 2.7 
- operating system: Windows 10
- vscode version: 1.56.1 (user setup)

**Comment by Woile** [comment]
Hey sorry for the confusion but we do not provide a commitizen for vs code, that's the javascript version.
I think you have to report the issue here: https://github.com/KnisterPeter/vscode-commitizen

**Comment by ALABSTM** [comment]
@Woile,

Thank you for your reply. I will forward this report to the right addressee. The issue can be closed then.

By the way, very nice and very helpful tool. Quite complete too. Thank you very much! :clap:

**Comment by jlanzarotta** [comment]
Thanks.  This solution worked great.
