### ISSUE TITLE
Changelog excludes signed commits when git config log.showsignature=True

### ISSUE THREAD

**Issue by lobotmcj** [commitizen-tools/commitizen#397]
## Description
When the git repo instance is configured to show signatures (`log.showsignature=True`) -- all signed commits are excluded from the changelog produced by Commitizen

## Steps to reproduce
1. git config log.showsignature true
2. cz ch --dry-run > broken
3. git config log.showsignature false
4. cz ch --dry-run > fixed
5. vimdiff broken fixed

## Current behavior
Any signed commits are missing from the changelog because git.py's `get_commits()` retrieves just the gpg signature line

## Desired behavior
The actual commit message should be retrieved and included in the changelog, regardless of the repo instance's git configuration

## Suggested Fix
Change line 80 of git.py from
`git_log_cmd = f"git --pretty={log_format}{delimiter} {args}"`
to
`git_log_cmd = f"git -c log.showsignature=False log --pretty={log_format}{delimiter} {args}"`
This will ensure that log.showsignature is false for the purpose of retrieving commits within Commitizen, but will not alter the underlying git repository's configuration as the `-c` flag applies for that command only.

**Screenshots**
![image](https://user-images.githubusercontent.com/32695581/124496292-3e458900-dd87-11eb-9be5-b9dd6f5eda66.png)

## Environment
- commitizen version: 2.17.11
- python version: 3.6.9
- operating system: Linux

**Comment by Lee-W** [comment]
@lobotmcj Thanks for reporting! I do not use signed commits frequently. I doubt I can test as accurately as you can. It would be great if you could send us a PR to fix it as you've almost fixed it. 🙂
