### ISSUE TITLE
generate changelog for a single tag

### ISSUE THREAD

**Issue by Trim21** [commitizen-tools/commitizen#399]
## Description

Hi everyone, thanks for your work.
I'd like to generate my changelog with commitzen in ci, and store them in github releases instead of a whole changelog.md in my source files.

But It looks impossible now, I can only generate the full changelog, or split them manually from a specific tag.

## Possible Solution

add a filter arguments to filter single tag like:

```bash
cz changelog --tag v0.0.5
```

## additional information

There already has been a `--start-rev` argument that may help with this. But I think it would be better to have a way select to just a single tag for ci or other things to simplify the workflow.

This is inspired by https://github.com/git-chglog/git-chglog#cli-usag

Now I'm doing it with `git-chglog "$TAG" > chglog.md` and `gh release create "$TAG" -F chglog.md`

**Comment by Lee-W** [comment]
Do you mean you want to get the changelog between `v0.0.5` and `v0.0.4` by using `cz changelog --tag v0.0.5`?

**Comment by Trim21** [comment]
> Do you mean you want to get the changelog between `v0.0.5` and `v0.0.4` by using `cz changelog --tag v0.0.5`?

Yes

**Comment by Woile** [comment]
This could be interesting.
What if we used version instead of tag? Would that be okay? Of course the tag would be calculated based on the tag_format.

This way you could do:

```bash
cz changelog --version $(cz version --project)
```

**Comment by Trim21** [comment]
I’m okay with that, sounds good.





------------------ Original ------------------
From: Santiago ***@***.***&gt;
Date: Fri,Jul 9,2021 1:59 AM
To: commitizen-tools/commitizen ***@***.***&gt;
Cc: Trim21 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [commitizen-tools/commitizen] generate changelog for a single tag (#399)

**Comment by Trim21** [comment]
git-chglog has a syntax like `0.0.3..0.0.5` to select versions from 0.0.3 to 0.0.5

Hope this information could help.
