### ISSUE TITLE
Changelog change type sections are ordered "incorrectly"

### ISSUE THREAD

**Issue by lobotmcj** [commitizen-tools/commitizen#402]
## Description
The default value for `change_type_order` uses lower-case "feat", "perf", etc instead of "Feat", "Perf", and is therefore ignored in changelog output

## Steps to reproduce
1. `mkdir /tmp/cztest && cd /tmp/cztest`
2. `git init`
3. `touch foo && git add foo && git commit -m "feat: first commit"`
4. `touch foo2 && git add foo2 && git  commit -m "perf: second commit"`
![image](https://user-images.githubusercontent.com/32695581/125208418-317dd500-e260-11eb-9267-cbe9f1ed75b0.png)
5. `cz ch --dry-run`
![image](https://user-images.githubusercontent.com/32695581/125208460-81f53280-e260-11eb-9fb1-cee495e408dc.png)
6. `echo -e "[tool.commitizen]\nchange_type_order = [\"Feat\", \"Perf\"]" > pyproject.toml`
7. `cz ch --dry-run`
![image](https://user-images.githubusercontent.com/32695581/125208547-29726500-e261-11eb-9d43-7c2dc592f178.png)

## Current behavior
The default change_type_order is ineffective and pre #323 LIFO ordering is used in the changelog

## Desired behavior
Changelog sections should be ordered according to https://github.com/commitizen-tools/commitizen/blob/master/commitizen/defaults.py#L43 

## Environment
- commitizen version: 2.17.12
- python version: 3.6.9
- operating system: Linux

**Comment by lobotmcj** [comment]
I'm not positive, but as far as I can tell, this only is in effect when using cz_conventional_commits and is caused by the change_type_map which maps "perf" to "Perf", etc here: https://github.com/commitizen-tools/commitizen/blob/aa0debe9ae5939afb54de5f26c7f0c395894e330/commitizen/cz/conventional_commits/conventional_commits.py#L35-L40

**Comment by Lee-W** [comment]
closed by #403
