### ISSUE TITLE
Changelog empty in existing project

### ISSUE THREAD

**Issue by ckoehler** [commitizen-tools/commitizen#411]
Hi there,

Running `cz ch` creates an empty changelog with only a `## Unreleased` section, but nothing listed in it. This is an existing project and only the latest commit conforms to the correct format.

# Expected output

A  `## Unreleased` section listing the one commit that conforms to the right format

# Actual output

An empty `## Unreleased` section

# More info

I've been playing around with different tags and `start-rev` arguments, but I never see any actual commits listed. This is likely user error... what am I missing? Thanks!

**Comment by ckoehler** [comment]
A `feat` change did show up in the changelog; the others were `docs` changes. Do those not show in the changelog? That would kinda make sense...

**Comment by Woile** [comment]
indeed, only a bunch from the spec are included and even bumping a release:

```
fix
feat
refactor
perf
```
