### ISSUE TITLE
Content to be added or fixed

### ISSUE THREAD

**Issue by falko-apheris** [commitizen-tools/commitizen#412]
## Type

* [x] Content inaccurate
* [x] Content missing
* [x] Typo

## URL
https://github.com/apheris/cz-github-jira-conventional

## Description
Hello there, I have created a 3rd party add on for commitizen that I would like to share with you. The addon extends the commitizen tools by:
- **requiring a Jira issue id** in the commit message
- **createing links to GitHub** commits in the CHANGELOG.md
- **createing links to Jira** issues in the CHANGELOG.md

Thanks for your awesome tool and all the work you have invested in it

**Comment by Lee-W** [comment]
This looks awesome! Could you please send ur a PR? you can modify the documentation here https://github.com/commitizen-tools/commitizen/blob/master/docs/third-party-commitizen.md
I believe you could introduce the cz rule better than we do

**Comment by Woile** [comment]
Super good, please add it to the third party as @Lee-W recommended

**Comment by falko-apheris** [comment]
https://github.com/commitizen-tools/commitizen/pull/413
