### ISSUE TITLE
I did not automatically generate a 'tag' after completing a commit using 'cz commit'.

### ISSUE THREAD

**Issue by tufbel** [commitizen-tools/commitizen#416]
My profile is `pyproject.toml`：
```
[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
tag_format = "v$version"
use_shortcuts = true
```
I used `fix` in `cz commit` and the $PATCH did not change and no `tag` was generated.

**Comment by Woile** [comment]
Hello @tufbel what was the outcome of `cz bump` ?

Normally you create one or more commits with conventional commits (starting with `fix:`, `feat:`, etc). And then you bump.
Usiny `cz commit` will only "assist" in the creation of a commit complying with conventional commits.

**Comment by tufbel** [comment]
> Hello @tufbel what was the outcome of `cz bump` ?
> 
> Normally you create one or more commits with conventional commits (starting with `fix:`, `feat:`, etc). And then you bump.
> Usiny `cz commit` will only "assist" in the creation of a commit complying with conventional commits.

`cz bump` can successfully generate a tag.
