### ISSUE TITLE
remove coloring from pre-commit prints

### ISSUE THREAD

**Issue by 12rambau** [commitizen-tools/commitizen#417]
## Description
I use the pre-commit framework to apply some sanity check before committing to my repositories. I recently discover this lib and wanted to give it a try. Fantastic work ! 

I use te following command to create a new commit: 
```
cz commit
```
 And I get the following results (sorry for the image but everything is about coloring):  
<img width="990" alt="Capture d’écran 2021-09-07 à 16 41 00" src="https://user-images.githubusercontent.com/12596392/132364926-28d38426-e2b9-4829-a8b2-1f17a6808dc4.png">

after `#258`which is the commit message, the pre-commit checks start and normally at the end of their lines `skipped`should be blue, `passed`: green and `failed` red. when creating a commit with `cz`I loose these colors. I tested back using simply `git commit`and it worked. 

Question then: why is the coloring of `pre-commit` disabled by `cz` ?

**Comment by Lee-W** [comment]
Thanks for reporting! if my memory serves me right, we did not do anything to disable the color 🤔 might need to take a look at the pre-commit side as well

**Comment by 12rambau** [comment]
Finally took the time to dive into this one: 

That's actually quite simple and it's definitely coming from here. Going upstream from `cli.py` I think commit are created using : `cmd.run(f"git commit {args} -F {f.name}")` where `cmd` is a `Command` object. the `run` method execute a subprocess call and redirect the resulting lines to `out`. 

If `git` is called from a subprocess it doesn't know if it's outputted to a terminal and switch off the ANSI coloring (ref: https://stackoverflow.com/questions/42589584/ansi-color-lost-when-using-python-subprocess, https://stackoverflow.com/questions/38084815/can-you-have-subprocesss-popen-retain-color-in-stdout-stderr). 

Now the question is: should the ANSI colorisation be authorized in the `Command` object or should we keep it that way to avoid compatibility issues whith platforms ?

**Comment by Lee-W** [comment]
Hi @12rambau Thanks for your help! Does that mean if we keep the ANSI coloring, we might break platform compatibility? If that's the case, I'd say platform compatibility is way more important.

**Comment by 12rambau** [comment]
> If that's the case, I'd say platform compatibility is way more important.

Agreed. Then I'll check if it can be set somewhere in the documentation in a note and then I'll close this issue

**Comment by Lee-W** [comment]
@12rambau Great! Thanks for your help!
