### ISSUE TITLE
Run Error: Invalid package name "accepts@1.3.7": name can only contain URL-friendly characters

### ISSUE THREAD

**Issue by NoripChan** [commitizen-tools/commitizen#422]
## Environment

- commitizen version:
- python version:
- operating system:
![Capture](https://user-images.githubusercontent.com/57546478/133540763-6d47ea1b-7c29-47b9-a5d4-77642c3b5a20.JPG)

**Comment by Lee-W** [comment]
Hi, I guess you're reporting to the wrong repo. This one is python commitizen not js one
