### ISSUE TITLE
brew install commitizen fail on linux brew

### ISSUE THREAD

**Issue by aufawibowo** [commitizen-tools/commitizen#423]
## Description
brew install commitizen fail on linux brew

## Steps to reproduce

installer returns 
```
Failed to build cryptography
  ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
  Installing build dependencies: finished with status 'error'
```
![image](https://user-images.githubusercontent.com/22342569/133634713-711f19a7-ed02-4b17-964a-311575a9634d.png)
## Desired behavior

return success 

## Environment

Ubuntu 20.04 64 bit on VMware Workstation 16 player and WSL 2 on Windows 11 64 bit

**Comment by Lee-W** [comment]
I'm not familiar with linux brew. Is it fully compatible with homebrew?

**Comment by aufawibowo** [comment]
well, it is homebrew (mac) running on Linux. 
https://docs.brew.sh/Homebrew-on-Linux

**Comment by Woile** [comment]
I was trying to find why we depend on the  package `cryptography`, maybe we could find out if that dependency can be bumped and that helps solve the problem. Or even remove the dependency. I tried looking at the lock file but found nothing

**Comment by woile** [comment]
Is this still the case? closing for now, but reopen if it persists. Please try `v3`
