### ISSUE TITLE
Document how to create a multi-repository commitizen configuration with pre-commit

### ISSUE THREAD

**Issue by offbyone** [commitizen-tools/commitizen#432]
## Type

* [ ] Content inaccurate
* [X] Content missing
* [ ] Typo

## URL
https://commitizen-tools.github.io/commitizen/config/

## Description
It's not clear how to set up a cross-repository `.cz.toml` that can provide team-wide commit message expectations.

**Comment by Lee-W** [comment]
We currently don't support cross-repository configuration. so the best way might be maintain one template and copy it to each project

**Comment by offbyone** [comment]
Not gonna re-open this, but ... would you be interested in a PR that allows for this?

**Comment by Lee-W** [comment]
That sounds great but not sure what would be the best way to solve it. Maybe you could create another feature request first so that we could discuss a bit more on that one
