### ISSUE TITLE
Document how to add custom third party templates to commitizen when using pre-commit

### ISSUE THREAD

**Issue by offbyone** [commitizen-tools/commitizen#433]
## Type

* [ ] Content inaccurate
* [X] Content missing
* [ ] Typo

## URL
https://commitizen-tools.github.io/commitizen/third-party-commitizen/

## Description
As a non-expert in pre-commit, I'm not sure how to add these other dependencies to the pre-commit configuration for commitizen, nor how to add my own custom templates. Please expand on that documentation.

**Comment by Lee-W** [comment]
Totally agree. I don't think we have a clear enough rule on how this should be handled yet.
