### ISSUE TITLE
Manually bump entire version, not just manually specify which part to increment

### ISSUE THREAD

**Issue by adamcunnington-gdt** [commitizen-tools/commitizen#435]
The [docs](https://commitizen-tools.github.io/commitizen/bump/#about) state that the version can be manually bumped but I believe this is incorrect as there's no other mention of this in the docs or in the CLI help beyond `--increment {MAJOR,MINOR,PATCH}` which is merely specifying the part to auto-increment.

Why do I want to manually specify the version to bump to? Well, I don't but unfortunately, dev versions are not supported - but I still want to make use of commitizen's version-updating inside of files. Otherwise, I will need to use a separate tool in conjunction, such as [bumpversion](https://github.com/c4urself/bump2version).

I want to be able to do `cz bump 1.0.1` for example (optional positional arg or `--manual <foo>` option would be fine).

A question on this though - whilst commitizen does not support dev versions, will it still be able to successfully parse a PEP440-compatible version that includes a dev version, for the sake of bumping? I.e. will commitizen be able to bump `1.0.1.dev0+foo.bar.baz` to `1.0.2` or `1.1.0` etc.?

And the ultimate related question - is there any planned support for dev versions?

**Comment by adamcunnington-gdt** [comment]
@Lee-W grateful for just your quick top-of-the-head thoughts here. Essentially:
- Can you confirm my understanding is correct.
- Can you indicate how willing you would be to support this?

**Comment by Lee-W** [comment]
I notice there's a discussion on #150 . Do you think they're related?

**Comment by adamcunnington-gdt** [comment]
Not really, no.
#150 is about a specific scenario in which the tool can't bump.

This issue is about supporting explicit manual bumping - i.e. not relying on any auto-bumping at all.
I think this is a critical feature because it provides a workaround for every issue where auto-bumping doesn't work / doesn't produce desired result.

**Comment by Woile** [comment]
> A question on this though - whilst commitizen does not support dev versions, will it still be able to successfully parse a PEP440-compatible version that includes a dev version, for the sake of bumping? 

We use the python packaging version parser, so it should work I guess.
And I'd like to make use of [poetry's semver](https://github.com/python-poetry/semver) at some point.

I like this proposal: `cz bump 1.0.1`, it's quite straightforward and similar to what cz changelog is going to support after https://github.com/commitizen-tools/commitizen/pull/400

**Comment by adamcunnington-mlg** [comment]
@manang ?

**Comment by manang** [comment]
Hi,
sorry, it is bank holiday and I'm not at home.
I will contact you this week about this feature.
See you
Angelo

**Comment by adamcunnington-mlg** [comment]
@manang i take it that are you not picking this up?

**Comment by manang** [comment]
sorry, nono, I need to finish it. this week end I will push the modification. sorry for the delay, but I'm busy for the last things before Christmas.
Angelo

**Comment by adamcunnington-mlg** [comment]
@manang I guess you are not ever getting around to this, right?

**Comment by jakob-keller** [comment]
I would also love to see this feature implemented!

**Comment by adamhoffstein** [comment]
So I take it this isn't happening?

**Comment by jakob-keller** [comment]
> So I take it this isn't happening?

It's been implemented and shipped since 2.34.0.
