### ISSUE TITLE
cannot execut changelog command

### ISSUE THREAD

**Issue by 12rambau** [commitizen-tools/commitizen#440]
## Description
I would like to update my changelog using the `changelog` command. 
When I run the following: 
```
cz changelog --incremental
```

I get the following error 

> No tag found to do an incremental changelog

I don't get it because I have checked `git tag` and I have 3 new one that are still unreferenced in the changelog

Is there a way to have a more comprehensive error message or maybe you have already faced this issue and you know what I missed in the configuration of my project (https://github.com/12rambau/sepal_ui)

## Environment

Python 3.8.10
platform: Linux 
commitizen: 2.19.0

**Comment by adamcunnington-gdt** [comment]
Is your problem not the exact one described in https://commitizen-tools.github.io/commitizen/changelog/#unreleased_version?

**Comment by 12rambau** [comment]
this is exactly this.... I though I was better at reading. Sorry for the noise !
