### ISSUE TITLE
cz check fails

### ISSUE THREAD

**Issue by manang** [commitizen-tools/commitizen#444]
## Description
cz check fails if the scope contains a space, but it is possible to commit with a space among the words.

## Steps to reproduce
cz commit
->write a scope of two words with a space between  
 cz check --rev-range origin/master..

## Current behavior
It fails, because the scope contains a space

## Desired behavior
it does not show errors

## Environment
Commitizen Version: 2.19.0
Python Version: 3.9.7 (default, Sep  3 2021, 12:37:55)
[Clang 12.0.5 (clang-1205.0.22.9)]
Operating System: Darwin (or ubuntu)

**Comment by Woile** [comment]
somehow cz commit and cz check should match, I agree.

there's not much information about the scope. I'm not a big fan of spaces but there shouldn't be anything wrong with them, the changelog would look ok as well:

*test config*: changed parameter for foobar

I've seen ppl using a `-` to separate words.

**Comment by CarlosBrunoE** [comment]
v2.20.0
was released yesterday

**Comment by Lee-W** [comment]
I've sent a PR to address homebrew publishing issue https://github.com/commitizen-tools/commitizen/pull/445
