### ISSUE TITLE
cz check does not detect incorrectly formatted commit message

### ISSUE THREAD

**Issue by nvtkaszpir** [commitizen-tools/commitizen#449]
## Description

Looks like cz does not detect properly incorrect commit messages, it only parses first line?

## Steps to reproduce
1. create file named BAD_MSG with the following content:
```text
ci: check commit message on merge
testing with more complex commit mes

age with error
```
as you can see there is no empty line between first and second line.

2. run `cz check --commit-msg-file BAD_MSG`

## Current behavior
```
Commit validation: successful!
```

## Desired behavior
```
commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "CI_COMMIT_MESSAGE"
pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)
```

## Environment

cz version -r
```
Commitizen Version: 2.20.0
Python Version: 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
Operating System: Linux
```

**Comment by Lee-W** [comment]
Hi @nvtkaszpir , thanks for reporting. I've confirmed this bug. It's most likely an error due to https://github.com/commitizen-tools/commitizen/blob/v2.20.0/commitizen/cz/conventional_commits/conventional_commits.py#L191

**Comment by Bogay** [comment]
@Lee-W I tried to fix this and found there might be some errors in `test_check_commands.py`.
Is `"fix(commands/init): fix clean up file when initialize commitizen config\n#138"` a valid commit message? According to the [spec](https://www.conventionalcommits.org/en/v1.0.0/#specification) of conventional commits, the body must begin one blank line after the description.

Here are the ill formatted commit messages I found: 
https://github.com/commitizen-tools/commitizen/blob/master/tests/commands/test_check_command.py#L24
https://github.com/commitizen-tools/commitizen/blob/master/tests/commands/test_check_command.py#L32-L36

**Comment by Lee-W** [comment]
@Bogay Yep, I think those test cases are inaccurate which seems to be a bug. Thanks for your finding!
