### ISSUE TITLE
Support for git --hooks

### ISSUE THREAD

**Issue by TheKnockFather** [commitizen-tools/commitizen#450]
## Description

With commitizen in node it is very straight forward on how to replace `git commit` in a project using git hooks, however, this does not seem to work in my current python project using poetry but is possible if you bring in `npm` as an additional dependency. Not ideal. 

## Possible Solution
Make `cz commit` replace `git commit` when a contributor is committing inside of a repository.

**Comment by Lee-W** [comment]
If you use `pip` or `pipx` to install `commitizen` in your local environment, then you can run `cz commit` driectly

**Comment by Lee-W** [comment]
As this is a duplicate issue to #249 , let's close this one and discuss there
