### ISSUE TITLE
Add --commit-args command line option to cz commit

### ISSUE THREAD

**Issue by adamcunnington-mlg** [commitizen-tools/commitizen#451]
Given `cz commit` wraps `git commit`, it would be great to be able to pass arbitrary args to the underlying git commit. This is a common pattern, for example, pip-tools' pip-compile has a `--pip-args` option.

Specifically, I need to be able to pass `--no-verify` to some commits to occasionally brute force supress hooks but I think you can just allow the user to pass a string of arbitrary `--commit-args` to cz commit which you then pass through to git commit.

**Comment by Bogay** [comment]
I am interesting to implementing this feature.
But some of `git` arguments might conflict with `cz` arguments?
For example, `cz c --commit-args -m foo` should be invalid because the commit message will be generated by `cz`?
I am not sure how to process these cases. Just ignore them or print a warning?

**Comment by Woile** [comment]
It seems similar to this discussion:
https://github.com/commitizen-tools/commitizen/issues/248

Which of all the proposed methods would be best?
Alternatively we can manually add one by one as they are required (which might not be the best)

**Comment by Bogay** [comment]
@Woile I read the discussion of #248 and I think `--` is a good idea.
About handing invalid arguments, I come up with two approach:
1. Directly pass all arguments after `--` to `git commit` and let `git` handle them. Leave the responsibility of giving correct args to the user. But there are so many edge cases might brake `cz`'s behavior, which affects the UX.
2. Add a whitelist to filter which argument can use. For example, `-S/--gpg-sign`, `-s/--signoff`, `-n/--no-verify`. At least I saw issues which discuss about these features. But this is less flexible if the whitelist is hard-coded in source.

**Comment by Lee-W** [comment]
I like the first solution a bit more. @Woile what do you think?

**Comment by adamcunnington-mlg** [comment]
Hi all, thanks for the consideration on this ticket. Really keen for this - is anyone picking it up?

**Comment by Lee-W** [comment]
@adamcunnington-mlg AFAIK, no one is picking it. Feel free to create a PR if you're interested in it. Thanks!

**Comment by adamcunnington-mlg** [comment]
I've not had chance to pick this up but would really love this

**Comment by SCrocky** [comment]
Is anybody working on this?

**Comment by Lee-W** [comment]
AFAIK, there's no one working on it. Feel free to take it :)

**Comment by adamcunnington-mlg** [comment]
@Lee-W did anyone review @SCrocky's MR?

**Comment by Lee-W** [comment]
Hi @adamcunnington-mlg, I just took a look. The idea is great. But we still need some test and doc

**Comment by SCrocky** [comment]
@Lee-W I've added tests on the raises.

I wanted to add a test on successfully passing the extra arguments to the `git.commit` call, but I'm having a hard time mocking the `commands.commit.Commit.__call__` in a way that will allow me to test the `arguments` property.

As for documentation, I can spare the time to add it. Did you have anything in mind?

**Comment by SCrocky** [comment]
Added some simple documentation for the syntax in `docs/commit.md`

**Comment by SCrocky** [comment]
Modifications done, branch rebased, ready for next round
