### ISSUE TITLE
cz bump return git.commit error : ""

### ISSUE THREAD

**Issue by Mara-Li** [commitizen-tools/commitizen#464]
## Description
`cz bump` return `git.commit error: ""`. 

```bash
> cz bump
bump: version 0.3.0 → 0.4.0
tag to create: v0.4.0
increment detected: MINOR

git.commit error: ""
```
Configuration : 
```yaml
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version: 0.4.0
```

It seems that the configuration file is updated, but not the changelog and no tag is created. 

## Steps to reproduce
1. run `cz bump`

## Current behavior
`cz bump` return `git.commit error: ""`. 

## Desired behavior

- Creation of the tag
- Update changelog

**Screenshots**
![image](https://user-images.githubusercontent.com/30244939/147098928-d61af864-4c87-48a1-a110-540c6feea21c.png)

## Environment

Add output of the following command to include the following
- Commitizen Version: 2.20.3
- Python Version: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
- Operating System: Windows

**Comment by Lee-W** [comment]
@Mara-Li Hi, may I know what's the status of your repo? Is it staged? Is there any commit before your first bump? and etc.

**Comment by Mara-Li** [comment]
There was commit before the first bump. The file was commit.

**Comment by Woile** [comment]
Could you also share your `git --version`? Thanks

**Comment by Mara-Li** [comment]
Hello !
My git version : `git version 2.33.0.windows.1`

**Comment by Mara-Li** [comment]
I up this. 
Each time I want to use cz bump, it blocks at the tag creation : it updates the file, and block. 
So I need to :
- Revert in the file the version.
- use `cz bump -ch` to manually update the changelog
- use `git push` to update with the changelog.
With that, it seems to block at the push ? 
Here is my log : 
```terminal
$ cz bump
bump: version 0.4.0 → 0.5.0
tag to create: v0.5.0
increment detected: MINOR

git.commit error: ""

$ cz bump -ch
Tag v0.5.0 could not be found.
Possible causes:
- version in configuration is not the current version
- tag_format is missing, check them using 'git tag --list'

? Is this the first tag created? No
[NO_COMMITS_FOUND]
No new commits found.
$ git tag --list
v0.1.0
v0.2.0
v0.3.0
v0.4.0
$ git tag v0.5.0
$ git tag --list
v0.1.0
v0.2.0
v0.3.0
v0.4.0
v0.5.0
$ cz bump -ch   
[NO_COMMITS_FOUND]
No new commits found.
$ git tag --d v0.5.0
$ cz bump -ch 
$ git push
```

(the last log was overwritten because a crash, but after the revert file, it works)

**Comment by Woile** [comment]
To update the changelog by doing only `cz bump`, you need the setting `update_changelog_on_bump = true`
see https://commitizen-tools.github.io/commitizen/bump/#update_changelog_on_bump
Otherwise you have to manually specify the `--changelog` flag.

To the git error I'm a bit puzzled, could you run with:

```
cz --debug bump
```
and share the output with us?

also:
```
which cz
```

The commit is not created probably because it fails to create the commit before 🤔
