### ISSUE TITLE
Exception when command is not given

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#47]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5144808/68481397-0d3f4900-0272-11ea-81c9-a861bdb0c704.png">

e.g., `cz --debug`, `cz --name <anything>`

**Comment by Lee-W** [comment]
The PR has been merged. Should we close this issue?

**Comment by Woile** [comment]
@Lee-W could you elaborate what needs to be done for this?

**Comment by Lee-W** [comment]
It is already fixed for 1.* All we need to do is remove the corresponding line (I mark a `TODO: remove in 2.0`), and then we can close this issue.

**Comment by Lee-W** [comment]
close by #230
