### ISSUE TITLE
EAFP: Add try/except around each attempt to load discover_this

### ISSUE THREAD

**Issue by KyleKing** [commitizen-tools/commitizen#474]
I have an issue with pdocs, that the package being documented (`cz_Legacy`) isn't fully initialized when commitizen is looking for discover_this. I know this is an edge case and there are plans to improve plugins (#287), but I wondered if you would be open to a small rewrite:

https://github.com/commitizen-tools/commitizen/blob/32916abd2210e8c2c8852b42f51fcbbb01181f4b/commitizen/cz/__init__.py#L15-L19

To something like this:

```py
def _is_likely_a_cz_plugin(name: str) -> bool:
    import warnings
    try:
        importlib.import_module(name).discover_this
        return True
    except AttributeError:
        warnings.warn(f"{name} is not a commitizen plugin")
        return False

# ...

plugins = {
    name: importlib.import_module(name).discover_this  # type: ignore
    for finder, name, ispkg in pkgutil.iter_modules()
    if name.startswith("cz_") and _is_likely_a_cz_plugin(name)
}
```

Or could be something like:

```py
# Could lru_cache, but probably won't make a difference
def _get_plugin_class(name: str):
    import warnings
    try:
        return importlib.import_module(name).discover_this
    except AttributeError:
        warnings.warn(f"{name} is not a commitizen plugin")

# ...

plugins = {
    name: _get_plugin_class(name)  # type: ignore
    for finder, name, ispkg in pkgutil.iter_modules()
    if name.startswith("cz_") and _get_plugin_class(name)
}
```

**Comment by Woile** [comment]
I'm in to improving the module section (it's not the best), though I don't understand what issue are you having with pdocs, could you elaborate on the error?

**Comment by KyleKing** [comment]
I'm not sure. I think the issue is how `pdocs` surveys the available modules, so it could be from here: https://github.com/timothycrosley/pdocs/blob/c122cdf873aad4fa131bc7ed968da3dd393df43b/pdocs/extract.py#L37-L78 or somewhere else in the codebase

Suppressing the `discover_this` error for `pdocs` still properly shows the right code on my documentation site: https://cz_legacy.kyleking.me/modules/cz_legacy/cz_legacy/ and doesn't impact the plugins use otherwise

There are very few packages (maybe ~4 in total on pypi) with the prefix `cz_` and no one has reported any issues, so while this change would preemptively address packages not related to commitizen, in practice that really isn't an issue

**Comment by KyleKing** [comment]
Here is the full traceback:

```sh
~/Developer/packages/cz_legacy main ?1 > poetry run pdocs as_markdown cz_legacy
Error importing cz_legacy: partially initialized module 'cz_legacy' has no attribute 'discover_this' (most likely due to a circular import)
```

**Comment by Lee-W** [comment]
Hi @KyleKing , it seems https://github.com/commitizen-tools/commitizen/pull/480/files might have been tackled on https://github.com/commitizen-tools/commitizen/pull/480/files. I'll close this issue for now. But feel free to let me know or reopen the issue, if I misunderstand the purpose of this issue
