### ISSUE TITLE
cz check skip merge messages

### ISSUE THREAD

**Issue by manang** [commitizen-tools/commitizen#483]
Hi, is it possible to skip the check of messages like "merge branch"
So, the idea is that I want to skip the check of messages that match a regex.
Thanks

**Comment by Lee-W** [comment]
commitizen skips "merge" automatically. we're working on make it configurable, but this is not available as of now. another way is to configure through https://commitizen-tools.github.io/commitizen/customization/

**Comment by manang** [comment]
I'm talking of cz check

this is an example of the commit message  that bitbucket generates automatically:
`Merge: 792e33e 6bbfe0e
Author: Angelo Mantellini
Date:   Thu Feb 10 20:24:26 2022 +0000

    Pull request #74: Merge release bugfixes into devel

    Merge in myteam/repo from master to devel

    * commit '6bbfe0ee00765b1572050931da01c11ed79e6ab6': (2 commits)
      bump: version 1.9.0b0 → 1.9.0
      ...
`

cz check returns a different value than 0.
My problem is that in this case I can't customise the merge messages.
Thanks a lot for your answer
Angelo

**Comment by Lee-W** [comment]
That's a bit weird as this should be skipped [here](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/check.py#L103). Could you please provide the version you test on?

**Comment by manang** [comment]
I'm checking why my "cz check" fails...thanks, I will report here..

**Comment by Lee-W** [comment]
hmmm... interesting. I'm thinking of using re to check. @Woile  what do you think?

**Comment by Woile** [comment]
I was not aware of this check, I think is worth adding `Pull request` to the list.
I think the ideal solution would be to have a setting users can set with commit messages to be skipped, besides the defaults

**Comment by manang** [comment]
can I create pull request adding pull request to the list?
let me know, I can do today.
Thanks

**Comment by Lee-W** [comment]
@manang Yes, that would be most appreciated. Many thanks!

**Comment by manang** [comment]
Hi, can you tell me why my pull request fails?
https://github.com/commitizen-tools/commitizen/pull/487
thanks

**Comment by manang** [comment]
I understood the problem, thanks

**Comment by manang** [comment]
no, I don't understand, there is an error outside the part that I changed.
can you help me? thanks

**Comment by manang** [comment]
how long do you need to create the debian package with the correction of cz?
Thanks

**Comment by Woile** [comment]
We do not maintain a debian package afaik.

The installation methods are listed here: https://commitizen-tools.github.io/commitizen/#installation

Looking at them, I'm thinking we should review them. Probably nowadays is best to use something like `pipx`, or pip install --user instead of `sudo`.
And maybe we can provide something like a binary using pyinstaller 🤔

**Comment by manang** [comment]
ah, it is true...thanks a lot for your support
