### ISSUE TITLE
spell checking commit messages

### ISSUE THREAD

**Issue by kbroch-rivosinc** [commitizen-tools/commitizen#490]
### Description

Consider adding a configurable spell checker option.

I realize this feature could create false positives and negatives, but also think it could do a lot of good to catch many of the typos I see in commit messages. 

### Possible Solution

https://github.com/codespell-project/codespell

**Comment by Lee-W** [comment]
I'm not really interested in implementing it but will accept it if anyone sends us a PR. @Woile What do you think?

**Comment by Woile** [comment]
To me it's a really good idea but as a separate project. You could run a precommit hook and check the spelling in the commit message. The good thing is that you could get rid of commitizen and keep using the spell checking if you wanted.

I think it's out of the scope of this project, but I would gladly list it in the third party tools, it would be a good addition

**Comment by Lee-W** [comment]
@Woile agree, in that case, I'll mark this as `won't implement` and close it

**Comment by kbroch-rivosinc** [comment]
Thanks for the input.  I will look into creating a separate hook for it.
