### ISSUE TITLE
option to specify newline types

### ISSUE THREAD

**Issue by CanisHelix** [commitizen-tools/commitizen#492]
### Description

I have pre-commit hooks to enforce LF line endings, this fails on every commitizen commit as it writes CRLF on windows. An option to configure this would be good.

### Possible Solution

Hacky, but I have customized my local commitizen and found all instances of `open` and added `newline='\n'` to them if they are `w` opens. And option in the .cz.yaml to specify this would be the optimal method.

**Comment by Lee-W** [comment]
@Woile I'm good with it and think it might be helpful. What do you think?

**Comment by Woile** [comment]
I'm also good with it as an option in the configuration
