### ISSUE TITLE
pre-commit check in CI

### ISSUE THREAD

**Issue by vhemt** [commitizen-tools/commitizen#494]
### Type

- [ ] Content inaccurate
- [X] Content missing
- [ ] Typo

### URL

https://github.com/commitizen-tools/commitizen#integrating-with-pre-commit

### Description

Hi, I can't find (if there is any) documentation or ideas about how to run the pre-commit check as part of a CI, so on a later stage than `commit-msg`.

Is there a way to check the commit messages after they are pushed?

**Comment by Lee-W** [comment]
We've not yet implement it as a pre-commit hook, but you can try ` cz check --rev-range main..`

**Comment by nejch** [comment]
If if helps anyone, we use this for GitLab CI to get reliable results across forks when using [merge request pipeline workflows](https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html):

`cz check --rev-range $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA`

**Comment by Kurt-von-Laven** [comment]
@nejch, FYI, there is a pre-commit hook now.

**Comment by Lee-W** [comment]
Thanks @nejch ! It's really helpful. Wondering would you be interested in opening a PR and adding it into part of our documentation

**Comment by Lee-W** [comment]
@vhemt as this is answered, I'll close this one. feel free to reopen it if you think your issue is not resolved
