### ISSUE TITLE
Support Regexes Containing Colons

### ISSUE THREAD

**Issue by Kurt-von-Laven** [commitizen-tools/commitizen#499]
### Description

One limitation of [this very cool feature](https://commitizen-tools.github.io/commitizen/bump/#version_files) is that if you put a `:` in your regex, anything from the colon on will be ignored (and there is no way to escape the colon).

### Possible Solution

Use [`str.partition()`](https://docs.python.org/3/library/stdtypes.html#str.partition) rather than [`str.split()`](https://docs.python.org/3/library/stdtypes.html#str.split) [here](https://github.com/commitizen-tools/commitizen/blob/605b1252c2b9bb4ce82d14e1fde26a8139ad5e23/commitizen/bump.py#L144) (and make the corresponding changes this entails).

**Comment by Lee-W** [comment]
I'm good with this. Would be great if you're interested in sending a PR 🙂
