### ISSUE TITLE
cz bump results in UnicodeEncodeError

### ISSUE THREAD

**Issue by manishrma** [commitizen-tools/commitizen#500]
### Description

cz bump results in the below error 
$ cz bump
Traceback (most recent call last):
  File "/usr/local/bin/cz", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/commitizen/cli.py", line 323, in main
    args.func(conf, vars(args))()
  File "/usr/local/lib64/python3.6/site-packages/commitizen/commands/bump.py", line 170, in __call__
    out.write(information)
  File "/usr/local/lib64/python3.6/site-packages/commitizen/out.py", line 8, in write
    print(value, *args)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2192' in position 21: ordinal not in range(128)

My latest tag is v2.9.0

### Steps to reproduce

Installed cz using 
sudo pip3 install -U Commitizen
do configuration via 
cz init 
and ran 
cz bump to get the next version

### Current behavior

Same as above

### Desired behavior

cz bump should give back the bumped version

### Environment

$ cz version --report
Commitizen Version: 2.23.0
Python Version: 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Operating System: Linux

**Comment by Lee-W** [comment]
@manishrma We've been working on encoding issue these days. Could you please check whether the latest version solve this one? 
I'll close this one for now. If the latest version doesn't not work for you, feel free to reopen it.
