### ISSUE TITLE
Default bump pattern is inconsistent with cz command

### ISSUE THREAD

**Issue by adamcunnington-mlg** [commitizen-tools/commitizen#507]
### Description

When using the `cz commit` command, you are prompted to choose type of change. The options are:
* fix
* feat
* docs
* style
* refactor
* perf
* test
* build
* ci

However, the default [bump_pattern](https://github.com/commitizen-tools/commitizen/blob/354f9ea687b1aee0e69ad2976dc23b1d6121ae3b/commitizen/defaults.py#L70) and [bump_map](https://github.com/commitizen-tools/commitizen/blob/354f9ea687b1aee0e69ad2976dc23b1d6121ae3b/commitizen/defaults.py#L71) only recognise:
* feat
* fix
* refactor
* perf

This seems like an odd oversight and presumably not deliberate.

Please can you update the default to be compatible/consistent with the types you support via the commit wrapper?
Without this, we are finding our master pipelines are failing when trying to bump the release version because the merged commit was for `tests` or `ci` or `style` - probably the most common types of change - and commitizen is not detecting these commits as "valid" determinants of version change.

The current workaround is to define custom patterns as per [customisation doc](https://commitizen-tools.github.io/commitizen/customization/).

### Steps to reproduce

^

### Current behavior

^

### Desired behavior

^

### Environment

Installed Commitizen Version: 2.24.0

**Comment by lovetheguitar** [comment]
Those commit types do not warrant a version change in general, so you should deal with that within your CI system.
I.e. do not let the job fail, but either ignore those errors (`--no-raise` flag) or handle the exit codes appropriately.

**Comment by adamcunnington-mlg** [comment]
Based on what sorry?

We use immutable build artifacts in our production environment - which is both very orthodox and very sensible.

**Comment by lovetheguitar** [comment]
E.g. a change in your CI system should not generally change your package or whatever you release. 
Its explicitly stated in the commitizen docs that the [bump command](https://commitizen-tools.github.io/commitizen/bump/) 
> ... follows [semantic versioning](https://semver.org/).

**Comment by adamcunnington-mlg** [comment]
@lovetheguitar sure, I conceded that one but how about tests - I want to install an explicit version with tests that I run? How about a style change that then went on to break functionality? Both of these should be immutable versions, no?

**Comment by adamcunnington-mlg** [comment]
I do see that this is subjective though so I will close.

**Comment by Lee-W** [comment]
@adamcunnington-mlg you can customize the behavior through [cz_customize](https://commitizen-tools.github.io/commitizen/customization/). We're planning on making the bump_map of cz_conventional_commit customizable as well. but due to the limited bandwidth, we cannot guarantee when it will be released
