### ISSUE TITLE
Duplicate Changelog Entries for Merged Branches

### ISSUE THREAD

**Issue by lovetheguitar** [commitizen-tools/commitizen#510]
### Description

Somehow I end up with duplicate changelog entries after merging a MR.
E.g. 
```markdown
## v0.1.2 (2022-05-02)

### Fix

- **release**: do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH
- **release**: do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH
- **release**: try to not escape $CI_DEFAULT_BRANCH default value
- **release**: do not run run bump_version/dry_run in tag pipeline
```

### Steps to reproduce

Use gitlab and add some commits to a new branch.
Open a MR and merge it.
Run commitizen on the main branch and get a changelog with duplicated entries.

### Current behavior

Duplicate Changelog Entries:
```markdown
## v0.1.2 (2022-05-02)

### Fix

- **release**: do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH
- **release**: do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH
- **release**: try to not escape $CI_DEFAULT_BRANCH default value
- **release**: do not run run bump_version/dry_run in tag pipeline
```

### Desired behavior

No duplicates from merging a MR:
```markdown
## v0.1.2 (2022-05-02)

### Fix

- **release**: do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH
- **release**: try to not escape $CI_DEFAULT_BRANCH default value
- **release**: do not run run bump_version/dry_run in tag pipeline
```

### Screenshots

Problem appears to be that commitizen seems to parse the commit body also?!

Git log shows:
```bash
Date:   Mon May 2 15:28:31 2022 +0200

    Merge branch 'fix/improve_release_jobs' into 'master'

    fix(release): do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH

    Closes #4

    See merge request group/ci_templates!10

Date:   Mon May 2 15:12:10 2022 +0200

    fix(release): do version bump on $RELEASE_BRANCH (if defined) else on $CI_DEFAULT_BRANCH

    else dry run version bump
...
```

### Environment

Commitizen Version: 2.24.0
Python Version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Operating System: Windows

Thanks for the nice tool. 😃

**Comment by tanguy-a** [comment]
Hey, got the exact same issue here:
Commitizen Version: 2.24.0
Python Version: 3.7.12 && 3.9.1

I tried with `pip3 install -U Commitizen==2.20.0` and it did not duplicate. 
The versions after this one seem to have the duplication issue.

**Comment by adam-grant-hendry** [comment]
@lovetheguitar Thanks for submitting this! I think I'll downgrade until a fix is submitted.

**Comment by Lee-W** [comment]
Hi @lovetheguitar could you please provide concrete steps for us to reproduce this issue on our side? Thanks !

**Comment by Woile** [comment]
I think this is related to the fact that we process the body, even though the subject of a commit message may not match conventional commits.
https://github.com/commitizen-tools/commitizen/blob/afa0d93544405bb0a871b5072e0a814720d933be/commitizen/changelog.py#L116-L140

I think if the subject doesn't match, we should skip directly, no?

I see this happening also now because github is adding the commit message in the body.
