### ISSUE TITLE
Ability to append or prepend commit hashes in change logs

### ISSUE THREAD

**Issue by usrme** [commitizen-tools/commitizen#513]
### Description

An ability to either append or prepend a shortened commit hash to a message. 

### Possible Solution

Given the change log:

```md
## 0.0.1b5 (2022-05-06)

### Dependencies

- **deps**: update 'requirements.txt'
- **deps**: bump ansible from 5.7.0 to 5.7.1
- **deps-dev**: bump mkdocs-material from 8.2.12 to 8.2.13

### Features

- **#35**: add raw root deployment error JSON as an attachment to the sent event
```

the feature would provide the user an ability to either prepend commit hashes:

```md
## 0.0.1b5 (2022-05-06)

### Dependencies

- c7e24f2 **deps**: update 'requirements.txt'
- 5c31edf **deps**: bump ansible from 5.7.0 to 5.7.1
- f4df18e **deps-dev**: bump mkdocs-material from 8.2.12 to 8.2.13

### Features

- 514e2b2 **#35**: add raw root deployment error JSON as an attachment to the sent event
```

or append commit hashes:

```md
## 0.0.1b5 (2022-05-06)

### Dependencies

- **deps**: update 'requirements.txt' c7e24f2 
- **deps**: bump ansible from 5.7.0 to 5.7.1 5c31edf 
- **deps-dev**: bump mkdocs-material from 8.2.12 to 8.2.13 f4df18e 

### Features

- **#35**: add raw root deployment error JSON as an attachment to the sent event 514e2b2
```

Maybe this is already possible through some sort of customization, but I wasn't able to find what I was looking for. I'm using GitLab behind the scenes, so these plaintext commit hashes would automatically be rendered as links, which would be really useful.

**Comment by Lee-W** [comment]
Hi @usrme , thanks for the suggestion! I'm good with this feature. Feel free to send us a pull request. Thanks!

**Comment by Woile** [comment]
Users already have the ability to customize this, see [custom-changelog-generator](https://commitizen-tools.github.io/commitizen/customization/#custom-changelog-generator) section. In the example you can see the author is being added to the changelog, you also have the has available.
I prefer to keep the changelog lean, but feel free to create a new commitizen, publish and add it to the Third party section in the docs!

**Comment by usrme** [comment]
Thanks for getting back to me! I'll definitely poke around with this once I get some time, but I'll close this for the time being.

**Comment by usrme** [comment]
Related to: https://github.com/commitizen-tools/commitizen/issues/396.
