### ISSUE TITLE
`cz changelog` is not reporting git errors (`git.py` missing `cmd.return_code` checks)

### ISSUE THREAD

**Issue by bhelgs** [commitizen-tools/commitizen#518]
### Description

`cz commit` worked just fine, but `cz changelog` resulted in the error:
> "No commits found"

I later came to find the calls to git were silently failing in `git.get_tags` due to an unsupported version of git.
It's not very obvious the issue is with git.
Might we want some kind of warnings/exceptions [here](https://github.com/commitizen-tools/commitizen/blob/afa0d93544405bb0a871b5072e0a814720d933be/commitizen/git.py#L123)"?

### Steps to reproduce

1. unsupported git (e.g. 1.8.3.1) (normally we use a newer version)
2. `cz changelog` (`cz commit` worked)

### Current behavior

Error handling could be improved.

### Desired behavior

Maybe a warning or `raise` would help users out when `cmd.run( ...git...)` fails?

### Environment

CentOS7

**Comment by bhelgs** [comment]
If you'd like to see a fork/PR just let me know if/what you'd like.
I've already made a few alterations for my teams anyway.

**Comment by Lee-W** [comment]
Sorry for the late reply. Yep, this is something we missed. Would be great if you're interested in sending a PR 🙂

**Comment by bhelgs** [comment]
Sounds good. No problem.
