### ISSUE TITLE
Add Package to Conda (Forge)

### ISSUE THREAD

**Issue by mahyarmirrashed** [commitizen-tools/commitizen#526]
### Description

I know that this project is on PyPi, but is there a possibility to add it to `conda`? Not sure how much extra overhead that adds.

### Possible Solution

I would be interested in helping out getting that done.

**Comment by Lee-W** [comment]
I've not yet have the experience on publishing package to `conda` but would be glad if you're interesting in investigating on it 🙂

**Comment by alexvorndran** [comment]
Someone gave it a try and put a version up on conda-forge: https://github.com/conda-forge/commitizen-feedstock/. Interestingly (or sadly?), it was last updated one day before this issue was opened.

**Comment by Lee-W** [comment]
interesting 🤔 but somehow it seems to be outdated. we might need to find out a way to update it automatically

**Comment by dmyersturnbull** [comment]
@Lee-W See [Grayskull](https://github.com/conda/grayskull) as well as [Tyrannosaurus](https://github.com/dmyersturnbull/tyrannosaurus), which uses Grayskull.
This is how I kept the recipe up-to-date after running `tyrannosaurus recipe` the first time:
[Contributing guide / Publishing a new version](https://github.com/dmyersturnbull/tyrannosaurus/blob/main/CONTRIBUTING.md#publishing-a-new-version)

**Comment by kmnhan** [comment]
I'm trying to update the conda-forge feedstock but one of our upstream dependencies [decli](https://github.com/conda-forge/decli-feedstock) also needs a recipe update.

I've updated the commitizen recipe to `3.1.1`, the latest version that is compatible with `decli=0.5.2`. Will bump to newest version once `decli>=0.6.0` is available on conda-forge.

**Comment by Lee-W** [comment]
@woile Will you be able to update on the `decli` side?

**Comment by woile** [comment]
I'm not the conda maintainer, I have never publish to conda 😅 Better to open an issue there

**Comment by kmnhan** [comment]
I filed [an issue](https://github.com/conda-forge/decli-feedstock/issues/4#issue-2570450330) to add myself to the decli feedstock list of maintainers. If the maintainers do not respond in a couple of days, I will contact conda-forge as mentioned in the [conda-forge docs](https://conda-forge.org/docs/maintainer/maintainer_faq/#a-feedstock-has-been-abandoned-and-i-would-like-to-take-over-maintenance)!

**Comment by Lee-W** [comment]
> I'm not the conda maintainer, I have never publish to conda 😅 Better to open an issue there

hmmmmm... interesting. I thought it you 🤔

**Comment by kmnhan** [comment]
`commitizen` v3.29.1 is now on `conda-forge`, as well as `decli` v0.6.2.

Here is the badge in case you want it in the readme:

![Conda Version](https://img.shields.io/conda/vn/conda-forge/commitizen?style=flat-square)

**Comment by Lee-W** [comment]
looks like we're good to close this one haha @kmnhan  do you want to create a PR to include the badge in the README and then we can close this one?
