### ISSUE TITLE
Generate Changelog from commits

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#53]
#### Goal
Generate a changelog using [Keep a changelog](https://keepachangelog.com/en/1.0.0/)
#### Description
* [WIP commit](https://github.com/Woile/commitizen/commit/f5943536b94fc088ac27396f487db4e733d30413)
  * Step 1: Parse changelog (Done)
  * Step 2: Parse git log

#### Other Reference
* [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages)
    * [conventional-changelog/packages/git-raw-commits/index.js](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/git-raw-commits/index.js)
    * [conventional-changelog-cli/](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli)
        * [cli.js](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-cli/cli.js)
    * [conventional-changelog-core](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core)
        * [lib/merge-config.js](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core)
* [vaab/gitchangelog (python)](https://github.com/vaab/gitchangelog)
    * [Good ways to manage a changelog using git?](https://stackoverflow.com/questions/3523534/good-ways-to-manage-a-changelog-using-git)
* [git-extras](https://github.com/tj/git-extras)
    * [git-changelog](https://github.com/tj/git-extras/blob/master/Commands.md#git-changelog)
* [github-changelog-generator (ruby)](https://github.com/github-changelog-generator/github-changelog-generator#why-should-i-care)
* Original Git
    * [Generate your changelogs with Git log](https://coderwall.com/p/5cv5lg/generate-your-changelogs-with-git-log)
    * [Git: How to get latest tag version from bash script](https://cleanprogrammer.net/git-how-to-get-latest-tag-version-from-bash-script/)

**Comment by pawamoy** [comment]
I don't what's your progress on this, but you could take a look at the one I wrote as well: [git-changelog](https://github.com/pawamoy/git-changelog)

It's not as flexible as I would like it to be, but I'm slowly improving it. Maybe you'll find interesting snippets :)

**Comment by Lee-W** [comment]
It looks great! Will take a deeper look. Thanks 😃

**Comment by Woile** [comment]
Thanks @pawamoy we will!

The latest work is here: https://github.com/commitizen-tools/commitizen/pull/163

**Comment by Lee-W** [comment]
Since the changlog feature is released, I think we can close this issue and create specific issues for feature enhancement
