### ISSUE TITLE
GitLab CI, NO_VERSION_SPECIFIED error

### ISSUE THREAD

**Issue by fly-shark** [commitizen-tools/commitizen#532]
### Description

development environment  :  java  project & gradle.

When I use GitLab CI, the following error is reporte：

`
Switched to branch 'feature/git-gradle'
$ cz bump
[NO_VERSION_SPECIFIED]
Check if current version is specified in config file, like:
version = 0.4.3
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 

###  CI  in non master branch

1.  .cz.yaml config:
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version: 1.1.0
  version_files:
  -build.gradle: version
`
2. CI config:
`
 auto-bump:
  stage: auto-bump
  image: python:3.8
  needs: ["prepare"]
  before_script:
    - "which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )"
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    - pip3 install -U Commitizen # install commitizen
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git remote set-url origin git@gitlabee.chehejia.com:dip/dip-ab-test.git # git configuration
    - git config --global user.email  "{CI_EMAIL}"  && git config --global user.name "${CI_USERNAME}"
    - git checkout feature/git-gradle
    - cz bump # execute auto bump and push to master
    - git push origin feature/git-gradle:$CI_COMMIT_REF_NAME
    - TAG=$(head -n 1 VERSION) # get the new software version and save into artifacts
    - echo "#!/bin/sh" >> variables
    - echo "export TAG='$TAG'" >> variables
    - git push origin $TAG
  only:
    refs:
      - feature/git-gradle
  artifacts:
    paths:
      - variables
`

### Current behavior

Local exec  `cz bump `is ok

bug GitLab CI failed
[NO_VERSION_SPECIFIED]

### Desired behavior

what happen? Please help me...

### Screenshots

![image](https://user-images.githubusercontent.com/45747286/176409730-5af735ae-57a6-4823-9885-cc49bc57976e.png)
![image](https://user-images.githubusercontent.com/45747286/176409790-4885508f-0dfb-4486-8e2c-c7d19ec30be1.png)
![image](https://user-images.githubusercontent.com/45747286/176409862-2c230eed-735d-47de-9dd6-0977ece4d99c.png)

### Environment

python version ： 3.8
commitizen version : 2.27.1
jdk version : 1.8
gradle version: 7.2

**Comment by Woile** [comment]
Try adding before `cz bump` the following command: `git fetch --tags`

**Comment by fly-shark** [comment]
> Try adding before `cz bump` the following command: `git fetch --tags`

Thank you very much. Maybe it's GitLab CI chache. Now it's successful

**Comment by Woile** [comment]
Normally you need to tell git to pull the tags, specially inside CI's, not sure why, I would theorise that they are configured to pull only the minimum necessary.
