### ISSUE TITLE
Allow lower case names for SemVer `--increment` 

### ISSUE THREAD

**Issue by edgarrmondragon** [commitizen-tools/commitizen#533]
### Description

The cz cli only accepts upper case increment names, but some tools work with lower case names for the same increment types. So, to keep things simpler in scripts, it'd be great to don't care about transforming to lower/upper case.

### Possible Solution

Since `decli` is mostly a declarative wrapper around `argparse`, maybe a simple `str.upper` can be used as the [`type`](https://docs.python.org/3/library/argparse.html#type) for `increment`.

This seems to work:

```python
# rps.py
import argparse

parser = argparse.ArgumentParser()
parser.add_argument(
    'move',
    choices=['ROCK', 'PAPER', 'SCISSORS'],
    type=str.upper,
)

args = parser.parse_args()
print(args.move)
```

```console
$ python rps.py rock     
ROCK
```

### Additional context

I can submit a PR if this is desirable.

**Comment by Woile** [comment]
Hey Edgar, that would be great! A PR is more than welcome
