### ISSUE TITLE
Produce changelog with `cz bump --dry-run --changelog-to-stdout`

### ISSUE THREAD

**Issue by bavedarnow** [commitizen-tools/commitizen#538]
### Description

I'm using the commitizen pre-commit hook paired with renovate for automated dependency updates.

I'd like to test the commitizen functionality before merging the upgrade PR. One thing I'd like to see is if the changelog is being generated correctly.

### Issue: 
pairing the `--dry-run` arg with `--changelog-to-stdout` does not produce the changelog

### Steps to reproduce

1. checkout your repository at an older version tag `git checkout 1.0.0`
2. soft reset to a newer version `git reset --soft 1.1.0`
3. `cz bump --changelog-to-stdout --dry-run`

not sure if this matters, but `changelog_incremental = true`

### Current behavior

```
cz bump --changelog-to-stdout --dry-run
bump: version 1.0.0 → 1.1.0
tag to create: 9.6.0
increment detected: MINOR
```

### Desired behavior

```
cz bump --changelog-to-stdout --dry-run
bump: version 1.0.0 → 1.1.0
tag to create: 1.1.0
increment detected: MINOR

## 1.1.0 (2022-07-25)

### CHANGELOG SHOWS UP HERE
```

### Environment

```
cz version --report
Commitizen Version: 2.27.1
Python Version: 3.10.4 (main, May 26 2022, 14:56:41) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Operating System: Darwin
```

**Comment by Woile** [comment]
Seems like a valid bug. I will try to submit a fix soon

**Comment by bavedarnow** [comment]
> Seems like a valid bug. I will try to submit a fix soon

I opened a PR here: https://github.com/commitizen-tools/commitizen/pull/539
