### ISSUE TITLE
Update supported Python classifiers

### ISSUE THREAD

**Issue by jenstroeger** [commitizen-tools/commitizen#548]
### Description

Considering that

https://github.com/commitizen-tools/commitizen/blob/2ff9f155435b487057ce5bd8e32e1ab02fd57c94/pyproject.toml#L47-L48

the current list of [classifiers](https://pypi.org/classifiers/)

https://github.com/commitizen-tools/commitizen/blob/2ff9f155435b487057ce5bd8e32e1ab02fd57c94/pyproject.toml#L42-L44

are incomplete. Should probably be fixed as they’re used by other services including PyPI.

### Steps to reproduce

Read the code 😉

### Current behavior

n/a

### Desired behavior

n/a

### Environment

Package metadata.

**Comment by Woile** [comment]
Thanks! Feel free to submit a PR for this 💪🏻
