### ISSUE TITLE
Give the user the possibility to commit without add files to staging before.

### ISSUE THREAD

**Issue by buhtz** [commitizen-tools/commitizen#554]
### Description

I am new to cz.

Usually I commit via `git commit -a`. So every tracked and un-staged file is staged automaticllly.

It seems to me that this is not possible with cz. I got the message "No files added to staging!".

I also tried `cz commit -- -a` which gives me an "unrecognized command" error.

### Possible Solution

Give the user the possibility to commit without add files to staging before.

### Additional context

#418

**Comment by Lee-W** [comment]
I'm week against this feature. IMO, deciding which files should be include in a commit is an important thing.  @Woile what do you think?

**Comment by Woile** [comment]
I think we've decided a long time ago not to use `-a`. I suggest 2 alternatives:

1. If you really wanna use cz commit, then create an alias: `alias czc="git add -u && cz commit"`
2. Use `fix/feat` in your commits and skip the interactive prompt: `git commit -am "feat: add shiny thing"`

On the other hand we added `-s` to commit, maybe we can add `-a` as well which is a commonly used param 🤔

**Comment by Lee-W** [comment]
If @Woile 's good with it, I'm good with it as well :) I guess we'll need to make some change to https://github.com/commitizen-tools/commitizen/blob/master/commitizen/git.py and https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/commit.py. It'd be great if you could sent us a PR :)

**Comment by Lee-W** [comment]
I think this one is finished in #821. Close this one. Thanks for @ttw225's reminder
