### ISSUE TITLE
cz c error while cz init with cz_commitizen_emoji option 

### ISSUE THREAD

**Issue by wn0x00** [commitizen-tools/commitizen#556]
### Description

[INFO] Stashing unstaged files to /home/wn/.cache/pre-commit/patch1660466731-7557.
check yaml...........................................(no files to check)Skipped
black................................................(no files to check)Skipped
commitizen check.........................................................Failed
- hook id: commitizen
- exit code: 1

The committer has not been found in the system.

Try running 'pip install cz_commitizen_emoji'

[INFO] Restored changes from /home/wn/.cache/pre-commit/patch1660466731-7557

### Steps to reproduce

1. pre-commit install 
2. pre-commit autoupdate
3. cz init
4. git add .
5. cz c

### Current behavior

The committer has not been found in the system.

Try running 'pip install cz_commitizen_emoji'

[INFO] Restored changes from /home/wn/.cache/pre-commit/patch1660466731-7557.

### Desired behavior

.......

### Environment

2.29.6

**Comment by Lee-W** [comment]
Hi @wn0x00 , it's seems there's no `cz_commitizen_emoji`. It should be `commitizen-emoji`. Please try `pip install commitizen-emoji`. I'll close it for now. Feel free to reopen it if you think you're issue is not solved
