### ISSUE TITLE
Enforce 72 character limit on commit msg header

### ISSUE THREAD

**Issue by rkr87** [commitizen-tools/commitizen#559]
### Description

Would it be possible to enforce a limit of 72 characters on commit msg headers per git recommendations?

It would of course need to take into consideration any values already entered for "type of change" and "scope", eg;

"fix(class) " should reduce the number of characters available for the header to 61 characters.

**Comment by Lee-W** [comment]
I think it a duplicate issue of #191 . In this https://github.com/commitizen-tools/commitizen/issues/191#issuecomment-1214314251, we might not be able to achieve it as of now. But new idea is welcome. I close this and let's discuss on #191 Thanks!
