### ISSUE TITLE
Ensure subject char is lowercase

### ISSUE THREAD

**Issue by juanvalino** [commitizen-tools/commitizen#584]
### Description

Currently `cz_conventional_commits` allows uppercase char at subject beginning although question description states "write a short and imperative summary of the code changes: (**lower case** and no period)".

### Possible Solution

Modify `conventional_commits.py` `parse_subject` function to ensure subject first char is lowercase, in a similar way dot strip that is already implemented.

**Comment by Lee-W** [comment]
I'm not sure whether we need to enforce this 🤔 To be frank, I'm a bit against it. We've already instruct the users through the message and it would not break anything if they choose not to. @woile What do you think?

**Comment by woile** [comment]
I agree with @Lee-W , we used to have something like this at the beginning but it was very annoying. Specially when you want to use class names at the beginning.
`fix: ApiView path`

I want ApiView to remain like the original, no to be `apiView`.
I would recommend creating a custom [commitizen class](https://commitizen-tools.github.io/commitizen/customization/#2-customize-through-customizing-a-class)
