### ISSUE TITLE
Relax specification for argcomplete dependency

### ISSUE THREAD

**Issue by jakob-keller** [commitizen-tools/commitizen#588]
### Description

Commitizen currently requires argcomplete ^1.12.1, which officially supports Python 3.5-3.9.

argcomplete 2.0 is available, which adds support for Python 3.10 and drops support for Python 3.5 ([see CHANGES](https://github.com/kislyuk/argcomplete/blob/develop/Changes.rst#changes-for-v200-2022-01-03)).

To allow for use of argcomplete 2.0.x in commitizen enabled projects, its dependency specification needs to be relaxed.

### Possible Solution

Modify pyproject.toml:

Old:

```
argcomplete = "^1.12.1"
```

New

```
argcomplete = ">=1.12.1,<2.1"
```

I will prepare a trivial PR.

**Comment by sshishov** [comment]
Can we add the support for `argcomplete 3.0+`?

**Comment by jakob-keller** [comment]
> Can we add the support for `argcomplete 3.0+`?

#702 should adress this

**Comment by sshishov** [comment]
Thanks @jakob-keller , can confirm it is fixed now 👍
