### ISSUE TITLE
Make empty commit

### ISSUE THREAD

**Issue by Dranaxel** [commitizen-tools/commitizen#590]
### Description

I wan to allow dev to create an empty commit with only cz message

### Possible Solution

Add an --allow-empty option

### Additional context

I work with a team using gitflow. I want to allow people to work freely on their feature branch and make a last conventionnally formated commit so we can merge-squash with the good message on develop branch

**Comment by Lee-W** [comment]
Hi @Dranaxel , thanks for the feedback. We have a duplicate issue https://github.com/commitizen-tools/commitizen/issues/247 to track this one. Let's discuss there. Also, PRs are welcome. Thanks!

**Comment by Dranaxel** [comment]
Hi @Lee-W thanks for your answer. I saw this issue but the status wasn't clear to me, sorry for the duplicate.
Does a PR with only allow-empty would fit ?

**Comment by Lee-W** [comment]
Yep, I'm good with it 👍
