### ISSUE TITLE
version 4.2.5 don't support cz-customizable's customScope

### ISSUE THREAD

**Issue by Fear2014** [commitizen-tools/commitizen#594]
### Description

When i use git-cz and select custom for scope, terminal dont show customScope. 
But it's ok when commitizen version is 4.2.4

### Steps to reproduce

git cz 

### Current behavior

![image](https://user-images.githubusercontent.com/34330035/191907739-895a0a20-72ec-4901-988c-d58053d4fc5c.png)

### Desired behavior

![image](https://user-images.githubusercontent.com/34330035/191907808-5c34f4d6-11a2-4f74-82f6-390ae28ca75d.png)

### Environment

/usr/local/lib
├── @commitlint/cli@17.1.2
├── @commitlint/config-conventional@17.1.0
├── commitizen@4.2.5
├── corepack@0.12.1
├── cz-customizable@7.0.0
├── n@9.0.0
├── npm@8.15.0
├── pm2@5.2.0
└── yapi-cli@1.5.0

**Comment by woile** [comment]
I think this is for the [javascript commitizen](https://github.com/commitizen/cz-cli). Please re-open if I'm mistaken.
