### ISSUE TITLE
Global Configuration

### ISSUE THREAD

**Issue by liblaf** [commitizen-tools/commitizen#597]
### Description

It would be nice to support global configuration, say `~/.cz.yaml`, to reduce the trouble of creating custom commitizen for each project.

### Possible Solution

Append `Path.home()` to `cfg_search_paths` in `commitizen/config/__init__.py`.

**Comment by liblaf** [comment]
https://github.com/commitizen-tools/commitizen/commit/41d3510bffebb0176177b6a1d65c0cdcdbd5a0d2

**Comment by Lee-W** [comment]
This is something we remove since `v2.0.0`. I'm not sure whether we're to adding it back. I'm a bit against it. @woile What do you think?

**Comment by Lee-W** [comment]
It looks like we've already concluded that we won't implement it. Close this one.
