### ISSUE TITLE
Commitizen pre-commit fails when using `git commit -v`

### ISSUE THREAD

**Issue by albertocerrone** [commitizen-tools/commitizen#598]
### Description

I usually create commits by using the `git commit -v` to have a verbose commit with all my changes.

### Steps to reproduce

Run ´git commit -v´

### Current behavior

```bash
commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "fix: Remove `.` to the commitizen version
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 0db57fb..ec425e1 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -54,7 +54,7 @@ repos:
     hooks:
       - id: doc8
   - repo: https://github.com/commitizen-tools/commitizen
-    rev: v.2.35.0
+    rev: v2.35.0
     hooks:
       - id: commitizen
         stages:"
pattern: (?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$
```

### Desired behavior

It should pass without any errors

### Environment

pre-commit = "^2.18.1"

**Comment by Lee-W** [comment]
Thanks for your report! I've verify the issue.

**Comment by Lee-W** [comment]
just traced the code, we probably need to add a similar filter [here](https://github.com/commitizen-tools/commitizen/blob/6e1e1a2439228044f59449e66d7fb698acd2c23c/commitizen/commands/check.py#L95) to filter all the things after `diff --git ...`

**Comment by albertocerrone** [comment]
@Lee-W I can take care of it if that helps you 🤗

**Comment by Lee-W** [comment]
@albertocerrone That would be awesome! Thanks!

**Comment by woile** [comment]
I think this PR was merged. Feel free to reopen again.
