### ISSUE TITLE
Not all version files are updating when running cz bump

### ISSUE THREAD

**Issue by courtneysprouse** [commitizen-tools/commitizen#601]
### Description

I have defined the following in my poetry toml file for my python project. 

```
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version = "4.0.6"
version_files = [
    "gitlab-testing-ground/__init__.py:__version__",
    "gitlab-testing-ground/__version__.py"
]
```

The `__version__.py` file updates with the new version but not the `__init__.py` file, which is weird and I've tried `gitlab-testing-ground/__init__.py` and a few other iterations, but nothing seems to work 

Contents of `__init__.py` file:
``__version__ = "3.2.1"``

Contents of `__version__.py` file:
``__version__ = "4.0.6"``

### Steps to reproduce

1. `cz c` (make some version update)
2. `cz bump` (check the files and one will be bumped and the other not )

### Current behavior

It's just weird that one of the files in the `version_files` updates, but not the other? Maybe I'm wrong and you can only put in certain files, but when I read the documentation, it didn't seem that way 

### Desired behavior

All files defined in `version_files` updates when you run `cz bump`

### Environment

commitizen version: 2.35.0
python version: 3.8.13

**Comment by woile** [comment]
In your init.py the version does not match your commitizen version. Commitizen will only update the version if it matches the current version. Otherwise it has no reason to touch that place.

Both files should have the version `4.0.6`

**Comment by woile** [comment]
No problem! Glad it's working! I'm closing this one
