### ISSUE TITLE
`/bin/sh` not on Windows

### ISSUE THREAD

**Issue by adam-grant-hendry** [commitizen-tools/commitizen#602]
### Description

The `pre-commit` scripts `test` and `format` rely on `/bin/sh`, which does not exist on Windows (at least the path). This is a non-portable shebang, which can be fixed by using `#!/usr/bin/env sh` instead.

### Steps to reproduce

1. Follow the [Contributing](https://commitizen-tools.github.io/commitizen/contributing/) steps to:
    (a) Fork the repo, install dependencies through `poetry`, and setup the `pre-commit` hooks
2. Run `pre-commit run --all`

### Current behavior

On Windows, the `pre-commit` hooks `format` and `linter and test` fail with the error message `Executable '/bin/sh' not found`.

### Desired behavior

The `pre-commit` hooks are able to run the provided shell scripts.

### Screenshots

![image](https://user-images.githubusercontent.com/59346180/195949218-18ec689a-7956-4176-99e2-93a6ad60d323.png)

### Environment

Commitizen Version: 2.35.0
Python Version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Operating System: Windows

**Comment by adam-grant-hendry** [comment]
Substituting the portable shebang works. However, `pytest` reports many failing tests and errors (completely unrelated to the changes). The following report was generated with `pytest-html`:

[pytest_report.zip](https://github.com/commitizen-tools/commitizen/files/9790428/pytest_report.zip)

**Comment by Lee-W** [comment]
Hi @adam-grant-hendry , thanks for your report. The html seems to miss some style and barely readable now. Could you guide me through on how to view it correctly? Or could you please share a few example on what you're testing and what's not working even with shebang?

**Comment by adam-grant-hendry** [comment]
> The html seems to miss some style and barely readable now. Could you guide me through on how to view it correctly?

I forgot to zip the CSS assets with it, my mistake. I updated the link, so please try downloading and unzipping again. You should see a folder `assets` with a file `style.css` in addition to `pytest_report.html` that will help it render properly.

> I ask because both [format](https://github.com/commitizen-tools/commitizen/issues/602) and [test](https://github.com/commitizen-tools/commitizen/blob/master/scripts/test) scripts are sh (e.g. bash and co) scripts that assume an appropriate environment.

I use vanilla Windows. The fact the test scripts require that environment [is not specified in the Contributing Guide](https://commitizen-tools.github.io/commitizen/contributing/). Rather than switching over to WSL or Cygwin/MSYS, I changed the shebang to a portable variant. My users use Windows, so I develop on Windows (it's easier for me to find problems and help them that way).

Regardless, the greater problem is [your Windows CI doesn't run](https://github.com/commitizen-tools/commitizen/issues/604). Even if I switched to WSL or Cygwin/MSYS, I have no confidence that `commitizen` will work for my PowerShell users.

Is `commitizen` intended only to be used by `bash`/`sh` users? That's going to cut off a lot of end users from using it without bugs.

**Comment by Lee-W** [comment]
https://gnupg.org/download/

> Is commitizen intended only to be used by bash/sh users? T

Ideally, no. We hope this project can be used by all users

**Comment by adam-grant-hendry** [comment]
> I just saw your test output. Could you please install https://gnupg.org/download/ and see how it works? It seems the doc is outdated. Before we add it to the doc, let's verify whether installing gpg fix it

I installed that and also tested out `gpg.exe` that ships with Git for Windows (it resides in `C:\Program Files\Git\usr\bin`. Both work well.

All tests are now passing in PR #605, so I was able to fix all the errors previously experienced on Windows. Please kindly re-review it at your earliest convenience.

Thank you!
