### ISSUE TITLE
[FEAT]: Add Discussions Tab

### ISSUE THREAD

**Issue by adam-grant-hendry** [commitizen-tools/commitizen#606]
### Description

The `Discussions` tab on GitHub has become the modern way of separating feature requests/bug reports/etc. from user questions/idea sharing/etc. This helps promote separation of concerns: a user can post a question in the `Discussions` and these can be converted into `Issues` if contributors/maintainers identify whether something is indeed a bug or should be added as a feature request.

Leaving the `Issues` tab only for identified bugs/feature requests/etc. helps maintainers schedule work more effectively.

### Possible Solution

Please enable the `Discussions` tab for this repo.

### Additional context

N/A

### Additional context

N/A

**Comment by Lee-W** [comment]
Thanks for the suggestion. @woile just opened it 🎉
https://github.com/commitizen-tools/commitizen/discussions
