### ISSUE TITLE
[FEAT]: 🌄 Sunset `Python 3.6`

### ISSUE THREAD

**Issue by adam-grant-hendry** [commitizen-tools/commitizen#607]
### Description

`Python 3.6` reached its [end of life](https://peps.python.org/pep-0494/) on 2021-12-23 (see also [PEP 602](https://peps.python.org/pep-0602/)).

In attempting to update `pyproject.toml` dependencies, some packages are requiring `Python >= 3.7`, which may warrant retiring `3.6`.

### Possible Solution

Please add a `DeprecationWarning` for `Python 3.6` to give existing users time to update their code bases and issue an agreed-upon sunset date for `Python 3.6` support.

### Additional context

See [PR #605](https://github.com/commitizen-tools/commitizen/pull/605) for discussion of some CI workflows that are failing due to outdated dependencies.

**Comment by Lee-W** [comment]
I'm good with this. @woile What do you think? Users using 3.6 can still use version < current version

**Comment by woile** [comment]
I'm good with this too.
