### ISSUE TITLE
Content to be added or fixed

### ISSUE THREAD

**Issue by smolendawid** [commitizen-tools/commitizen#609]
### Type

- [ ] Content inaccurate
- [X] Content missing
- [ ] Typo

### URL

https://commitizen-tools.github.io/commitizen/changelog/

### Description

It's not clear to me how to add hash and PR reference in the changelog. It's mentioned it's possible here: https://github.com/commitizen-tools/commitizen/issues/513

Especially I'm not interested in Python API, I'd like to activate this function from the config level (pyproject.toml).

I think it would be great to add the example in docs - I could create PR, but I don't get yet how to add references to CHANGELOG.

**Comment by Lee-W** [comment]
Hi @smolendawid , thanks for your report. I don't thing we can do it in config level as of now. According to the doc, we'll need to change `changelog_message_builder_hook`.

**Comment by smolendawid** [comment]
I think that's it, thank you. I think it would be great to be able to set it in config. Maybe the difference is not huge but I like the fact that I don't have to write anything but a config args in the file that already exists.
