### ISSUE TITLE
Improve `cz init` command

### ISSUE THREAD

**Issue by woile** [commitizen-tools/commitizen#625]
### Description

The `cz init` needs a revamp:

- If the latest or initial tag is `<1.0`, we should show a prompt for the `major_version_zero` setting.
- If cancel by user (ctrl+c) the file should not be created.
- Ask the user for `update_changelog_on_bump`

**Comment by ChauhanKrunal** [comment]
> ### Description
> The `cz init` needs a revamp:
> 
> * If the latest or initial tag is `<1.0`, we should show a prompt for the `major_version_zero` setting.
> * If cancel by user (ctrl+c) the file should not be created.
> * Ask the user for `update_changelog_on_bump`

Adding to the preceding points

- Display an appropriate error message if a user does not select any of the pre-commit hooks `commit-msg`, `pre-push`, or one of them.
