### ISSUE TITLE
Support new charset-normalizer v3

### ISSUE THREAD

**Issue by sshishov** [commitizen-tools/commitizen#635]
### Description

The package `charset-normalizer` has released the v3. The dependency for this project is `<3.0.0,>=2.1.0`

### Possible Solution

Add the support for new version of `charset-normalizer` and add it to the supported versions

### Additional context

https://github.com/Ousret/charset_normalizer/releases
The 3.0.0 released in Oct, version 3.0.1 released in Nov.

**Comment by Lee-W** [comment]
Hi @sshishov Thanks for reporting. Feel free to test comitizen with higher charset-normalizer version and send us a PR. Thanks!
