### ISSUE TITLE
Bump without commits to bump shouldn’t fail (option)

### ISSUE THREAD

**Issue by jenstroeger** [commitizen-tools/commitizen#642]
### Description

See also issue https://github.com/jenstroeger/python-package-template/issues/422 

In CI the non-zero return code [Non-Increment exit `21`](https://commitizen-tools.github.io/commitizen/exit_codes/) fails an Action run, which isn’t really desirable. Using [`continue-on-error: true`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) we could probably work around this, but I wonder if it would make more sense to add a command-line option `--exit-zero` (or some such) to `bump` which would prevent the command from returning a non-zero exit code. I think a command-line option makes my intent clearer than silencing the failing command from the Github Action.

### Possible Solution

See above.

### Additional context

n/a

### Additional context

n/a

**Comment by Lee-W** [comment]
I think we could try `cz -nr 21 bump` to avoid this. I'll close for now, but feel free to reopen it if it doesn't solve your issue :)

**Comment by jenstroeger** [comment]
Oh… should’ve erad the [Avoid raising errors](https://commitizen-tools.github.io/commitizen/bump/#avoid-raising-errors), thanks @Lee-W 👍🏼
