### ISSUE TITLE
Skip Commits in Changelog

### ISSUE THREAD

**Issue by Pukimaa** [commitizen-tools/commitizen#653]
### Description

Something similar to the skip ci flag would be cool. So I can have commits like automatic linting commits excluded from the Changelog generated by commitizen.

### Possible Solution

The commit message could look something like this:
`type(skip ch): message`

**Comment by woile** [comment]
This is already the case, commits that do not match the rules are skipped. So you can already do something like:

```
format: applied black and ruff
```
as a commit, and the changelog will skip it.
