### ISSUE TITLE
Does not work with python 3.6

### ISSUE THREAD

**Issue by gabohc** [commitizen-tools/commitizen#665]
### Type

- [X] Content inaccurate
- [ ] Content missing
- [ ] Typo

### URL

https://commitizen-tools.github.io/commitizen/

### Description

According to the docs, it requires python 3.6 at minimum.

However, `hooks.py` uses `from __future__ import annotations`, which is [not supported by python 3.6](https://docs.python.org/3.6/library/__future__.html)

**Comment by Lee-W** [comment]
@woile It seems I accidentally merged a branch that would break 3.6. I'm thinking of merging `v3` and explicitly dropping 3.6 support

**Comment by woile** [comment]
Agreed, py36 support was dropped officially, we should drop it and maybe next year also 3.7. I remember a discussion or PR to drop 3.6 somewhere, right?

**Comment by Lee-W** [comment]
Yep, if my memory serves me right, we decide to do so in `v3`. As this sounds like a breaking change to me. `v3` might be a reasonable option

**Comment by woile** [comment]
We no longer support python 3.6
