### ISSUE TITLE
Be able to configure the allowed prefixes list

### ISSUE THREAD

**Issue by Lotram** [commitizen-tools/commitizen#672]
### Description

https://github.com/commitizen-tools/commitizen/issues/414 and https://github.com/commitizen-tools/commitizen/pull/551 introduced what is a breaking change for my team, since we want `cz check` to fail in the CI, in case of a fixup. 
[This comment](https://github.com/commitizen-tools/commitizen/pull/551#issuecomment-1217168208) suggests to add this list to the config, which IMO is a good idea. 

### Possible Solution

I've already written the PR to implement this new config / cli argument [here](https://github.com/Lotram/commitizen/commit/6e874d4bb9a1554ca50803d802f8a0d7ae688d72), but, as written in [contributing.md](https://github.com/commitizen-tools/commitizen/blob/master/docs/contributing.md), I'm creating an issue to validate this change first.

**Comment by Lee-W** [comment]
Close this issue as #678 has been merged
