### ISSUE TITLE
`bump` does not pick a breaking change for `chore!:`

### ISSUE THREAD

**Issue by jenstroeger** [commitizen-tools/commitizen#673]
### Description

According to the [spec](https://www.conventionalcommits.org/en/v1.0.0/#summary):

> BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with [MAJOR](http://semver.org/#summary) in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.

Please not the last sentence, it says “of any type”.

After we shipped v2.7.0 for our template repo we added a breaking change https://github.com/jenstroeger/python-package-template/commit/144aac7239e831d47c90df3f6503ca8a21c8290c (or `git log v2.7.0..v2.8.0`):
```
chore!: drop support for Python 3.9, add support for Python 3.11 (#445)
```
However, this commit did _not_ result in a major version bump as expected, and the [CHANGELOG](https://github.com/jenstroeger/python-package-template/releases/tag/v2.8.0) does not even mention the breaking `chore:`.

### Steps to reproduce

Try it on the template itself:
```
> git clone https://github.com/jenstroeger/python-package-template.git
> cd python-package-template/
> git reset HEAD^  # Drop the last bump commit.
> git restore .  # Remove the changes.
> git log v2.7.0..HEAD  # Ensure the chore! commit is there.
> cz bump  # Bump, which should create v3.0.0.
```
which then results in
```
bump: release 2.7.0 → 2.8.0

Automatically generated by Commitizen.

tag to create: v2.8.0
increment detected: MINOR

[main f5e8fc3] bump: release 2.7.0 → 2.8.0
 3 files changed, 19 insertions(+), 2 deletions(-)

fatal: tag 'v2.8.0' already exists
```

### Current behavior

The `chore!:` commit isn’t regarded as a breaking change.

### Desired behavior

The `chore!:` commit should be regarded as a breaking change, and be listed as such in the CHANGELOG.

### Environment

```
> cz version --report
Commitizen Version: 2.42.0
Python Version: 3.11.2 (main, Feb 10 2023, 08:20:03) [Clang 14.0.0 (clang-1400.0.29.202)]
Operating System: Darwin
```

**Comment by jenstroeger** [comment]
@woile @Lee-W ping?

**Comment by woile** [comment]
I've missed this. I'll try to take a look this weekend. PRs are welcome as well

**Comment by jenstroeger** [comment]
Happy to provide a PR after you confirm it’s a bug and want it fixed 🤓

**Comment by woile** [comment]
The bug seems to happen on this line:

https://github.com/commitizen-tools/commitizen/blob/master/commitizen/defaults.py#L91

in this sample, only the first 2 match the regex:

```
feat(cli)!: added version
feat(cli): added version
chore!: drop support for Python 3.9
docs(README): motivation
```

**Comment by jenstroeger** [comment]
So the [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0/#summary) says

> _types_ other than `fix:` and `feat:` are allowed, for example [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) (based on the [Angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)) recommends `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others.

Only two of those recommended are listed in that regex:

https://github.com/commitizen-tools/commitizen/blob/0354a9d41e0d04ac689edce4a0352804539e95b5/commitizen/defaults.py#L91

Moreover, the spec says “and others” which seems to indicate that user may invent _any_ other type as well? Perhaps that’s a little too far, but it would make sense for commitizen to follow Angular’s recommendations at least?

**Comment by woile** [comment]
Should we make every other from the "angular" spec a `patch` change? @Lee-W do you have any thoughts? Maybe for v4?

I've been thinking of creating a new cz rule: `cz_conventional_commits_v1` with only `fix` and `feat` (and the breaking mechanisms). And maybe letting the user add `ci: PATCH` if they want new types.

The existing `cz_conventional_commits` is quite old and drags a lot of issues from older versions of the spec.

**Comment by Lee-W** [comment]
> Should we make every other from the "angular" spec a patch change? @Lee-W do you have any thoughts? Maybe for v4?

I'm good with making it a `patch` update for now. As for v4, I'm thinking of separating cz rules (e.g., `cz_conventional_commits`) with `commitizen` itself and releasing them in a different cycle. We can have a few default extras with `commitizen`.

**Comment by evanjmg** [comment]
please update the python file to follow the documentation

**Comment by Lee-W** [comment]
Just notice the PR has been merged. Close this one
