### ISSUE TITLE
`cz ch ${TAG}` not woking, raise `Could not find a valid revision range.`

### ISSUE THREAD

**Issue by trim21** [commitizen-tools/commitizen#674]
### Description

I have a repo try to add commitzen to generate changelog from git commit from command `cz ch ${TAG}` for single tag

But it raise `Could not find a valid revision range.` instead of changelog

### Steps to reproduce

```shell
git clone https://github.com/trim21/transmission-rpc
cd transmission-rpc
pip install commitizen==2.42.0
cz ch v4.0.0
```

### Current behavior

```shell
(transmission-rpc-py3.11) ~/proj/python/transmission-rpc (master) # cz ch v4.0.0
Could not find a valid revision range.
```

### Desired behavior

changelog should generate

### Screenshots

no

### Environment

Commitizen Version: 2.42.0
Python Version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Operating System: Windows

**Comment by trim21** [comment]
Oh, I get it, I try to use it without config.

**Comment by lucienshawls** [comment]
please help, how can i make this to work?
```shell
cz ch v4.0.0
```
i dug into the source code and discovered that, somehow, `vx.y.z` just cannot be recognized; it just tries to match original git tags `vx.y.z` with normalized inputs `x.y.z`.

**Comment by trim21** [comment]
sorry I do not use this tool anymore and I forget how to make it work at that time
