### ISSUE TITLE
Add changelog version compare URLs (usage in templates)

### ISSUE THREAD

**Issue by afuetterer** [commitizen-tools/commitizen#676]
### Description

Hi there, if this is already possible, please close the issue.

It would be nice to be able to generate "compare URLs" for the tagged versions and releases, to be used in templates. 

Example:
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/CHANGELOG.md

What do you think?

**Comment by woile** [comment]
The way to go is to create a custom cz rule: https://commitizen-tools.github.io/commitizen/customization/#custom-changelog-generator

**Comment by afuetterer** [comment]
Hi @woile, thank you for the very quick response. I will create a custom rule then, subclassing `BaseCommitizen`.

The tagged versions and releases are not accessible in templates already, right? I need to process the whole changelog in the `changelog_hook` method?
