### ISSUE TITLE
cz changelog does not create breaking change for feat(pipeline)!

### ISSUE THREAD

**Issue by StanislavKulykovRelayr** [commitizen-tools/commitizen#682]
### Description

I use commitizen for creating changelog.

i create commit with this format (example) **feat(pipeline)!: some text with breaking change**

but in the changelog it not marking as Breaking change

### Steps to reproduce

cz changelog --incremental --unreleased-version="v1.0.0"

config yaml is 
      commitizen:
          name: cz_customize
          customize:
            commit_parser: '^(?P<change_type>build|chore|docs|fix|hotfix|perf|refactor|revert|style|test|feat)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?:\s(?P<message>.*)?'
            changelog_pattern: '^(build|chore|docs|fix|hotfix|perf|refactor|revert|style|test|feat)(\([\w\s-]*\))!?:\s*(.+)$'
            change_type_map:
              build: Build
              chore: Chore
              docs: Docs
              fix: Fix
              hotfix: Hotfix
              perf: Perf
              refactor: Refactor
              revert: Revert
              style: Style
              test: Test
              feat: Feat

### Current behavior

commit **feat(pipeline)!: some text with breaking change** not marked as breaking change

### Desired behavior

commit **feat(pipeline)!: some text with breaking change**  described as Breaking changes in changelog.md

### Environment

cz version --report
Commitizen Version: 2.42.1
Python Version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Operating System: Windows

**Comment by jenstroeger** [comment]
_Maybe_ related to issue https://github.com/commitizen-tools/commitizen/issues/673?
