### ISSUE TITLE
`cz init` fails, When any one or none of the pre-commit hooks are selected

### ISSUE THREAD

**Issue by ChauhanKrunal** [commitizen-tools/commitizen#694]
### Description

When I run `cz init` and choose none of the pre-commit hooks from `commit-msg` and `pre-push`, or one of them, it displays the following message.
```
commitizen already in pre-commit config
Failed to install pre-commit hook.
pre-commit is not installed in current environment.
```

### Steps to reproduce

1. Run `cz init`
2. Choose any one of the commit rule
3. Enter the version
4. Select any one or none of the pre-commit hooks from `commit-msg`, `pre-push`rules

### Current behavior

Displaying an error message

```
commitizen already in pre-commit config
Failed to install pre-commit hook.
pre-commit is not installed in current environment.
```

### Desired behavior

I'm not sure if this is expected behavior, but I believe prompting a well-suited error message would be appropriate; if not, I believe it requires a fix.

### Screenshots

![Screenshot from 2023-04-01 21-59-16](https://user-images.githubusercontent.com/86162969/229302993-2e47df2f-b7cc-4c14-a1fe-f962f9724969.png)
![Screenshot from 2023-04-01 21-59-32](https://user-images.githubusercontent.com/86162969/229302997-a6818f7e-7c0e-4a92-a755-ad487cfe07b2.png)

### Environment

- commitizen version: `2.42.1`
- python version: `3.8.10`
- operating system: `Linux`

**Comment by woile** [comment]
I was not able to reproduce it

**Comment by woile** [comment]
Feel free to reopen if it happens again with more detailed steps to reproduce, also check commitizen `v3`. Also check if you already have a pre-commit file or similar

**Comment by Anrock** [comment]
I'm currently evaluating different tools for conventional commits and encountered this issue while evaluating commitizen 4.8.3 on test repo.

Test repo is the most barebones repo:
```
$ mkdir test-repo
$ echo "a" >> test.txt
$ git commit add test.txt
$ git commit -m "initial"
$ git tag 1.0.0
```
Then I've tried to init commitizen following steps from README:
```
$ cz init
Welcome to commitizen!

Answer the questions to configure your project.
For further configuration visit:

https://commitizen-tools.github.io/commitizen/config/

? Please choose a supported config file:  .cz.toml
? Please choose a cz (commit rule): (default: cz_conventional_commits) cz_conventional_commits
? Choose the source of the version: scm: Fetch the version from git and does not need to set it back
? Is 1.0.0 the latest tag? Yes
? Choose version scheme:  semver
? Please enter the correct version format: (default: "$version")
? Create changelog automatically on bump Yes
? What types of pre-commit hook you want to install? (Leave blank if you don't want to install) [pre-push]
Failed to install pre-commit hook.
pre-commit is not installed in current environment.
```
It looked weird - I've only asked for pre-push, why does complain about pre-commit? I've tried it again
```
$ cz init
Welcome to commitizen!

Answer the questions to configure your project.
For further configuration visit:

https://commitizen-tools.github.io/commitizen/config/

? Please choose a supported config file:  .cz.toml
? Please choose a cz (commit rule): (default: cz_conventional_commits) cz_conventional_commits
? Choose the source of the version: scm: Fetch the version from git and does not need to set it back
? Is 1.0.0 the latest tag? Yes
? Choose version scheme:  semver
? Please enter the correct version format: (default: "$version")
? Create changelog automatically on bump Yes
? What types of pre-commit hook you want to install? (Leave blank if you don't want to install) [pre-push]
commitizen already in pre-commit config
Failed to install pre-commit hook.
pre-commit is not installed in current environment.
```
I've checked hooks in this barebones repo - `.git/hooks/` only contained *.sample files.

I have custom `core.hooksPath` set up in `~/.config/git/config` because I already use other hooks.
It already had
- commit-msg
- post-checkout
- post-commit
- post-merge
- pre-commit
- pre-commit-latest
- pre-push

None of them were modified. However `.pre-commit-config.yaml` was created in test repo root

I've created a test commit with commit message that doesn't conform with conventional commit format and didn't get any warning or error about it.

**Comment by woile** [comment]
`commitizen` assumes that you know about the tool called [pre-commit](https://pre-commit.com/), which is the one used by commitizen for anything git-hook related.

I'm not a user of `pre-commit` myself, but it's a fairly widely used tool for automation of git hooks, specially aimed at reproducibility.

**Comment by Lee-W** [comment]
according to the error message, `pre-commit is not installed in current environment.` you do not have pre-commit to check it for you automatically

**Comment by Anrock** [comment]
Ah, I see. I guess it should be listed in requirements section of readme then. I've never heard about this tool before and assumed that it refers to pre-commit hook.
I'll try again tomorrow with pre-commit tool installed.

**Comment by woile** [comment]
You are right, I just realized how confusing the name can be 😅 it can definitely give the wrong idea.
