### ISSUE TITLE
Bump Increments `PATCH` Version on `ci` Commit

### ISSUE THREAD

**Issue by Kurt-von-Laven** [commitizen-tools/commitizen#695]
### Description

commitizen-action cut a spurious patch release when we merged a `ci` commit, ScribeMD/slack-templates@e2d9df0fd40c871ef9627c82005e0a127a5d39d0, to `main`, because `cz bump` incorrectly committed a bump. We made many `ci` commits previously without encountering this issue, and I am not sure what was special about this case.

### Steps to reproduce

1. Run `git clone git@github.com:ScribeMD/slack-templates`.
2. Run `git checkout 0.6.17^` to checkout the commit that triggered the spurious release.
3. Refer to our [contributing guide](https://github.com/ScribeMD/.github/blob/main/CONTRIBUTING.md#setup) if desired to maximize fidelity between our dev environments, but you can most likely get away with simply running commitizen 2.42.1.
4. Run `poetry run cz --no-raise 21 bump --yes --changelog --check-consistency --dry-run`. (Omit the `poetry run` portion if you didn't follow our contributing guide and installed commitizen some other way.)
5. Observe the following output:

    ```
    bump: version 0.6.16 → 0.6.17
    tag to create: 0.6.17
    increment detected: PATCH
    
    ## 0.6.17 (2023-04-05)
    ```

### Current behavior

Here is the pertinent output from commitizen-action:

```
Commitizen version: 2.42.1
cz --no-raise 21 bump --yes --changelog --check-consistency
bump: version 0.6.16 → 0.6.17
tag to create: 0.6.17
increment detected: PATCH
```

### Desired behavior

Commitizen shouldn't increment the version number when there are no `feat`, `fix`, or `refactor` commits since the previous tag, 0.6.16 in this case.

### Environment

- Commitizen version: 2.42.1
- Python version: 3.11.2
- Operating system: Linux

**Comment by woile** [comment]
Could you share the commit log? Summary and body of each commit message?

My first guess would be that there was another commit in the branch that triggered the patch

**Comment by Kurt-von-Laven** [comment]
[Here](https://github.com/ScribeMD/slack-templates/compare/0.6.16...0.6.17) is the log, but as you can see there are only `chore`, `docs`, and `style` commits in addition to the lone `ci` commit at the end. We run the commitizen-action after every merge to main and only merge one commit at a time, so it would be even more mysterious if the preceding commits factored into this bug.

**Comment by Kurt-von-Laven** [comment]
[A subsequent `ci` commit](https://github.com/ScribeMD/slack-templates/commit/6184e79f0783ca7a24519d3611a11f9ea3b64eee) didn't trigger a release. Still not sure what was different about ScribeMD/slack-templates@e2d9df0fd40c871ef9627c82005e0a127a5d39d0.

**Comment by Kurt-von-Laven** [comment]
I believe the issue is that one of the lines of the body of the commit message started with the characters "perf," and [Commitizen searches the full commit message](https://github.com/commitizen-tools/commitizen/blob/378a42881891633d8a81939cb46426eb36ed01aa/commitizen/bump.py#L28). It seems like it should only search the subject with the exception of `BREAKING CHANGES`?

**Comment by woile** [comment]
I think it supports parsing the body for simplicity, this way the regex can include `BREAKING CHANGE`. 
Which commit has the `perf`? I think it should only parse if it's `perf:`, rather than just perf

**Comment by Kurt-von-Laven** [comment]
The commit is ScribeMD/slack-templates@e2d9df0fd40c871ef9627c82005e0a127a5d39d0. It currently matches [`perf`](https://github.com/commitizen-tools/commitizen/blob/378a42881891633d8a81939cb46426eb36ed01aa/commitizen/defaults.py#L92). Should it match `perf[!]:` instead?

**Comment by woile** [comment]
I think it might be this: https://github.com/commitizen-tools/commitizen/blob/378a42881891633d8a81939cb46426eb36ed01aa/commitizen/defaults.py#L84

Be can be sure with a test probably

**Comment by Kurt-von-Laven** [comment]
Sorry, yes, you are correct. I linked to the wrong line.

**Comment by woile** [comment]
Confirmed, gonna submit a patch soon
