### ISSUE TITLE
CI incorrectly says setup.py version is wrong

### ISSUE THREAD

**Issue by mmorley0395** [commitizen-tools/commitizen#699]
### Description

Github CI is throwing an error when attempting to autoincrement, and the error doesn't appear to be true. 

setup py looks like: 

> setup(
>     name="planbelt",
>     version="0.1.0",
>     packages=find_packages(),
>     include_package_data=True,
>     install_requires=[
>         "Click", ......

pyproject.toml looks like: 

> [tool.commitizen]
> name = "cz_conventional_commits"
> version_files = [
>   "setup.py::version",
>   "pyproject.toml:version"
> ]
> version = "0.1.0"
> tag_format = "v$major.$minor.$patch$prerelease"
> 

When something is pushed to main, the job mostly runs, but fails at incrementing and throws:

> 
> Current version 0.1.0 is not found in setup.py::version.
> The version defined in commitizen configuration and the ones in version_files are possibly inconsistent.

### Steps to reproduce

1. Copy this repo, install dependencies 
2. Commit a feat or fix with cz
3. Push to main
4. Check logs for CI

### Current behavior

logs for github CI job state that version isn't in setup.py

### Desired behavior

Version is in setup.py, so this error shouldn't appear or should be more precise on what else to check

### Environment

Commitizen Version: 2.42.1
Python Version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Operating System: Linux

**Comment by woile** [comment]
Shouldn't you have just one colons `:`?

**Comment by mmorley0395** [comment]
ah! that was it.. sorry ! closing!
