### ISSUE TITLE
Support `charset-normalizer` 3.x versions, not just 3.0.x

### ISSUE THREAD

**Issue by sshishov** [commitizen-tools/commitizen#700]
### Description

Currently the version restriction for `charset-normalizer` is 3.0.x, why we only support patch versions? Usually in minor versions should not be any breaking changes.

I would suggest to support the `major` version or at least keep the pace to support new version of packages when they become available.

**Comment by woile** [comment]
latest version of commitizen supports `charset-normalizer<4`
