### ISSUE TITLE
Add `-a` and `-A` support

### ISSUE THREAD

**Issue by yajo** [commitizen-tools/commitizen#739]
### Description

Common workflow:

```sh
git add -A
cz c
```

Boring. Could be better with a single command.

### Possible Solution

```sh
cz c -A
```

Adds all changed files and issues the commit subcommand.

### Additional context

Git also adds one of these shortcuts: `git commit -a`. So it seems to make sense...

**Comment by Lee-W** [comment]
I think this one is finished in https://github.com/commitizen-tools/commitizen/pull/821. Feel free to reopen it if this is not the case 🙂  Thanks @Ellie-Yen for reminder
