### ISSUE TITLE
Add a simple changelog line pattern and allow including the commit author or issue number

### ISSUE THREAD

**Issue by Alexander-Serov** [commitizen-tools/commitizen#748]
### Description

I have looked through the customization options, but haven't found an easy way to have a custom format of the changelog lines without creating a custom changelog generator from the `BaseCommitizen` class. However, sometimes it is practical to have some simple indicators such as the commit author or the issue they were working in the changelog line.

For instance, currently a changelog line looks like:
> feat(context): commit message

It would make our changelog more organized if we could have
> context: commit message (John Doe) #issue

### Possible Solution

I was wondering if it could be possible to add this message format pattern as a parameter to the `cz changelog` and `cz bump`. No need to do anything complicated, but just do standard formatting based on a limited number of available variables. For instance,

```
[tool.commitizen.customize]
bump_message_template = "%context: %msg (%author) %issue"
```

### Additional context

Our general motivation: we have a multi-member team and it's not always possible to follow which member made which change or within which issue. Tracking this information could allow us to keep track of those things and reach out to the right person with questions on changes. The changelog is not directly shared with outside clients, so there is no problem with having this information in the changelog.

**Comment by woile** [comment]
Mm we don't have plans to support this as the capacity is very low, increases complexity, and it adds maintenance burden for us. We recommend implementing your own version.

For my work I made a custom one, which includes the commit hash, the very same `git.GitCommit` includes the author, so it would be relatively simple to add.

See:

https://github.com/kpn/cz-kpn/blob/488307e0adae4fb3e16157d4e1db156d65f1d7af/src/cz_kpn/rules.py#L103-L113

You only need to set the `commit_url` in the settings.

For the issue number, nothing needs to be done, in gitlab, github, and bitbucket all integrate well by just using the `#<issue_id>`. When the README is rendered by the platform, it automatically includes the link

**Comment by sandzhaj** [comment]
> https://github.com/kpn/cz-kpn/blob/488307e0adae4fb3e16157d4e1db156d65f1d7af/src/cz_kpn/rules.py#L103-L113

Your implementation changes the default representation of message. While I was talking not changing the defaults, but providing users an ability to write customizable jinja templates.
 
How a few keys in dict adds maintenance burden? In my fork the most difficult part of "maintaining" that feature was updating data in tests (takes 10 mins). 

Commitizen supports custom regex to add more freedom for users, that is too hard to maintenance. But passing extra data in templates increases complexity?

It seems i'll just use my fork, `parsed_message.update(commit.__dict__)` works well, if ignoring one test.

**Comment by woile** [comment]
Well... we usually try to cover all cases, not just your configuration.
What if a user has no email? I wouldn't want users to have a broken link if no email is present.

> Your implementation changes the default representation of message

I think you didn't understand, it was an example of a custom cz rule on how to use the hooks with author and email. You can choose to use the same message representation.

> It seems i'll just use my fork

Nice that you were able to solve it, closing it now

**Comment by sandzhaj** [comment]
> Well... we usually try to cover all cases, not just your configuration.
> 
> What if a user has no email? I wouldn't want users to have a broken link if no email is present.
> 
I was talking about passing mode data to template, but to change template. Just passing those objects, that your script already has to provide users extend theirs templates. Visually nothing be changed 

And every commit has an email, because if you don't set it up, you can't create and push a commit.  And you already have that attr in your class, why you can't give class object to user, by passing it to the template?
 You can still leave the your default template as is, but just provide users more freedom by passing one variable :)

**Comment by sandzhaj** [comment]
> Nice that you were able to solve it, closing it now

That is not my Issue... Other users still waiting more freedom :)
