### ISSUE TITLE
Allow releasing after a release candidate without commits

### ISSUE THREAD

**Issue by Alexander-Serov** [commitizen-tools/commitizen#751]
### Description

In our company, we make a release candidate and if it works, perform the full release. Currently, this logic is not compatible with `cz bump` because it always requires to have commits. Here is an example of the log:

The release candidate bump:
```
$ cz bump -pr rc 
bump: version 0.6.0 → 0.6.1rc0
tag to create: v0.6.1rc0
increment detected: PATCH
[detached HEAD de92ff6] bump: version 0.6.0 → 0.6.1rc0
 1 file changed, 11 insertions(+)
```

Attempting to do a real release on the commit tagged as 0.6.1rc0:
```
$ cz bump
bump: version 0.6.1rc0 → 0.6.1
tag to create: v0.6.1
No commits found
```
and exits with the exit code 3.

### Possible Solution

Sometimes a release candidate is good. Let us just allow updating the changelog and tag that commit.

### Additional context

We are using `changelog_merge_prerelease = True` so I would expect a changelog entry with the same info as in 0.6.1rc0 to be created, committed and tagged.

We have also tried to ignore the error and force proceed with
```
cz bump -nr 3
```
as indicated in the Documentation, but that gave the same result.

**Comment by aferreirap** [comment]
Our company would also be impacted by this feature!

**Comment by Lee-W** [comment]
I just tested it with the latest version (3.26.0), and it seems to work fine. I'm closing this one. Please feel free to reopen if the feature does not work. Thanks! 🙂
