### ISSUE TITLE
Question: Any way to get the current version?

### ISSUE THREAD

**Issue by abrahammurciano** [commitizen-tools/commitizen#752]
### Description

Is there any way to get the current version of a project?

### Possible Solution

Something like

```
cz bump --get-version
```

### Additional context

Would be useful in a CI pipeline that bumps the version, to get the new version without having to parse git tags or the output of bump.

**Comment by woile** [comment]
You can find in the documentation an explanation on the version command:

https://commitizen-tools.github.io/commitizen/getting_started/#get-project-version

Let me know if that helps 👍🏻

**Comment by abrahammurciano** [comment]
Thanks! I looked everywhere for that, didn't find it

**Comment by woile** [comment]
Where was it logic for you to be? Should we add a `version` section under commands?

**Comment by abrahammurciano** [comment]
Yes that was where I looked.
