### ISSUE TITLE
"cz init" should list exisitng tag in reverse order 

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#760]
### Description

When we run `cz init` in a project with existing tags, when it comes to the question `? Please choose the latest tag:  (Use arrow keys)`. We list the tags in ascending order. However, the latest tag is most likely with the largest number. Thus list the tags in reverse order makes more sense.

**Comment by Ellie-Yen** [comment]
@Lee-W  i'll take the issue

**Comment by Lee-W** [comment]
@Ellie-Yen Sure thing!
