### ISSUE TITLE
Configure `cz commit` to add `--signoff` by default

### ISSUE THREAD

**Issue by schlotter** [commitizen-tools/commitizen#785]
### Description

Many projects require developers to sign-off every commit in order to acknowledge the project's Developer Certificate of Origin (DCO). Thus, it would be useful to configure commitizen in a way so that each commit is automatically signed-off, so that the `-s`/`--signoff` options do not manually be supplied to `cz commit`.

### Possible Solution

1. Developer sets `always_signoff` setting to `true`.
2. Developer runs `cz commit` without any arguments.
3. Developer answers all questions of commitizen.
4. A Git commit is created and its message contains
   ```
   Signed-off-by: Firstname Lastname <firstname.lastname@example.com>
   ```

**Comment by Lee-W** [comment]
Hi @schlotter, thanks for proposing this issue. It sounds good to me. Would be much appreciated if you're interested in sending a PR 🙂

**Comment by Lee-W** [comment]
Thanks @JamieLee0510 for the reminder. Just verified this issue was merged long a ago and resolved
