### ISSUE TITLE
Shortcut for commit types

### ISSUE THREAD

**Issue by wardVD** [commitizen-tools/commitizen#788]
### Description

The Commitizen CLI is already very fast and easy to use, but it would be even nicer and faster if there is an option to skip the questions by adding the possibility to set the type in `cz commit`/`cz c`.

### Possible Solution

Add an extra positional argument to `cz commit` that sets the type, e.g. if `cz commit` is executed, then the questions for the commit type are still prompted.

If `cz commit feat` is executed, the questions can be dropped and the type is set as feat.

**Comment by Lee-W** [comment]
The main problem with `cz commit feat` is that we support not just `cz_convetionsal_commit` but also other `cz` such as `cz_jira`. This might not make sense to other `cz`. But I'm open to other design for addressing this issue

**Comment by Lee-W** [comment]
As this has not been discussed for some time, I'm going to close this one. Feel free to reopen it if anyone has idea 🙂
