### ISSUE TITLE
Create a flag to build the changelog from commits in multiple git repositories

### ISSUE THREAD

**Issue by mcflyhalf** [commitizen-tools/commitizen#790]
### Description

Reviewed #365 prior to writing this and I believe this is different enough to warrant a different issue

**Problem**
I have 2 git repositories `core_repo` and `plugins_repo`. The 2 are developed and maintained by the same team and are deployed together; therefore we would like to have only a single changelog that tracks the changes from the 2 repos. 

### Possible Solution
Is it possible to add a flag to fetch commits from multiple repos as though all the commits came from a single repository?
I would like to be able to do something like `cz changelog --unreleased --repository $CORE_REPO_DIR $PLUGINS_REPO_DIR` and end up with a single changelog file as though the commits from both repos came from a single repo. 

### Additional context
Here is an example to demonstrate this practically
Within repo1
```
git log
feat: feature 1 in repo 1
fix: bugfix 1 in repo 1
feat: feature 2 in repo 1
fix: bugfix 2 in repo 1
```

Within repo2
```
git log
feat: feature 1 in repo 2
fix: bugfix 1 in repo 2
feat: feature 2 in repo 2
fix: bugfix 2 in repo 2
```

I would like to be able to run `cz changelog --unreleased --repository $REPO1_DIR $REPO2_DIR` and get:
```
# Changelog

All notable changes to this project will be documented in this file.

## [1.0.1] - 2023-07-14

### Bug Fixes

- Bugfix 1 in repo 1
- Bugfix 2 in repo 1
- Bugfix 1 in repo 2
- Bugfix 2 in repo 2

### Features

- Feature 1 in repo 1
- Feature 2 in repo 1
- Feature 1 in repo 2
- Feature 2 in repo 2

```

I am willing to submit a PR to do this but I will need some guidance and a bit of time

**Comment by woile** [comment]
I think it requires massive effort on our side. 

As an alternative, commitizen can output the changelog for a single version to a file. 
You could run the changelog on each repo CI, and send each changelog somewhere else to be merged.
