### ISSUE TITLE
Allow cz bump to use PEP 621 pyproject.toml/project.version

### ISSUE THREAD

**Issue by dmyersturnbull** [commitizen-tools/commitizen#794]
### Description

Currently, using [PEP 621](https://peps.python.org/pep-0621/), the version needs to be stored in pyproject.toml in two locations:
- `project.version`
- `tool.commitizen.version`

Running `cz bump` modifies only `tool.commitizen.version`, leaving the two out of sync. `project.version` is arguably the correct place to store this metadata for anything outside of commitizen's purview.

### Possible Solution

A config item / CLI option could be added to specify that commitizen should only operate on `project.version`.
Example:

```toml
[project]
name = "my-project"
version = "0.1.0"

[tool.commitizen]
version_key = "project.version"

### Additional context

_No response_

### Additional context

_No response_

**Comment by woile** [comment]
Already supported: https://commitizen-tools.github.io/commitizen/config/#version-providers
