### ISSUE TITLE
[Refactor] move cz_conventional_commit defaults out of defaults.py

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#818]
### Description

As described in https://github.com/commitizen-tools/commitizen/issues/425#issuecomment-1537112868, many of our values in [commitizen/defaults.py](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/defaults.py) are for cz_conventional_commit only but not necessary for the whole commitizen.

**Comment by ITingHung** [comment]
@Lee-W can I take this?

**Comment by Lee-W** [comment]
@ITingHung Sure!

**Comment by Lee-W** [comment]
Closed by #1042
