### ISSUE TITLE
Rename "files" in configuration

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#82]
**Goal**
Make the name of this configuration more intitive

**Description**
The name "files" cannot be directly linked to the files that speficy version. How about "version_files"?

**Comment by Woile** [comment]
I like it, let's deprecate the `files` in version `2.0.0`.

**Comment by Woile** [comment]
Docs have been updated to reference to `version_files`

**Comment by Lee-W** [comment]
close by #230
