### ISSUE TITLE
cz bump throws 'Version scheme "pep440" unknown.' on Windows

### ISSUE THREAD

**Issue by thecesrom** [commitizen-tools/commitizen#854]
### Description

When I run `cz bump --dry-run` I get the following error: Version scheme "pep440" unknown.

Related: #853 

### Steps to reproduce

1. cz bump --dry-run

### Current behavior

```sh
$ cz bump --dry-run
Version scheme "pep440" unknown.
```

### Desired behavior

It should work as it did in 3.8.2

### Environment

```sh
$ cz version --report
Commitizen Version: 3.9.0
Python Version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Operating System: Windows
```

**Comment by woile** [comment]
How did you install commitizen on windows?

**Comment by thecesrom** [comment]
I installed it via pipx.

It works fine in macOS and Linux, though.

**Comment by snellejelle99** [comment]
Did you upgrade from an older version recently? If so it could be related to my issue with old install remnants.
#841

**Comment by thecesrom** [comment]
I believe I did upgrade from 3.8.0, just like them.

So it might be related.

**Comment by snellejelle99** [comment]
> I believe I did upgrade from 3.8.0, just like them.
> 
> So it might be related.

Try going into the pipx install directory and manually delete the old packages. That worked for me

**Comment by Lee-W** [comment]
@thecesrom could you please try what @snellejelle99 suggested and see how it works? Thanks!
