### ISSUE TITLE
cz bump fails if any non semver tag exist

### ISSUE THREAD

**Issue by gotpist1** [commitizen-tools/commitizen#916]
### Description

When trying to use cz bump with scm as provider, cz fails on get.version() if there are any tags that does not follow semver. This is probably intentional, but i would expect it to skip the faulty ones and fetch the latest real semver tags and calculate the new version from those. This seems to work fine when you use cz init and it asks "Is this the latest tag?"

### Steps to reproduce

1. Create a faulty semver tag eg. 0.1.0-1-refs_pull_31_merge
2. create a cz config with theese settings:
```
[tool.commitizen]
name = "cz_conventional_commits"
version_scheme = "semver"
tag_format = "$version"
version_provider = "scm"
```
3. Run cz bump --dry-run

### Current behavior

This will yield an exception orginating from packaging/version stating it's an invalid version:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/cz", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/commitizen/3.12.0/libexec/lib/python3.12/site-packages/commitizen/cli.py", line 565, in main
    args.func(conf, arguments)()
  File "/opt/homebrew/Cellar/commitizen/3.12.0/libexec/lib/python3.12/site-packages/commitizen/commands/bump.py", line 136, in __call__
    current_version = self.scheme(provider.get_version())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/python-packaging/lib/python3.12/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.1.0-1-refs_pull_31_merge'
```

### Desired behavior

I would like it to be able to skip the faulty ones and use the latest "ok" semver version as it seems to do when generating the toml file. Or, if a explicit version i set with

`cz bump 1.0.1`
Use that version and skip the check against tags altogether.

### Environment

Commitizen Version: 3.12.0
Python Version: 3.12.0 (main, Oct  5 2023, 15:44:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Operating System: Darwin

**Comment by Lee-W** [comment]
I just tested in the latest version (3.26.0) without encountering the issue (but there would still be warnings). I'm going to close this one. But please feel free to reopen it if the issue still persists. Thanks!

**Comment by ek08** [comment]
The issue still persists. I have anexisiting tag as aga-fe/v1.2-kv. The error I get is InvalidVersion aga-fe/v1.2-kv doesn't match configured tag format $version

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true
changelog_file = "CHANGELOG.md"  # Specify changelog file explicitly
bump_message = "bump: version $current_version → $new_version"
allow_abort = false
check_consistency = false
changelog_start_rev = "HEAD~1" 


I am using 
Ubuntu - 22.04
Python -  3.12

**Comment by Lee-W** [comment]
> The issue still persists. I have anexisiting tag as aga-fe/v1.2-kv. The error I get is InvalidVersion aga-fe/v1.2-kv doesn't match configured tag format $version
> 
> [tool.commitizen] name = "cz_conventional_commits" tag_format = "$version" version_scheme = "pep440" version_provider = "poetry" update_changelog_on_bump = true major_version_zero = true changelog_file = "CHANGELOG.md" # Specify changelog file explicitly bump_message = "bump: version $current_version → $new_version" allow_abort = false check_consistency = false changelog_start_rev = "HEAD~1"
> 
> I am using Ubuntu - 22.04 Python - 3.12

which cz version are you using?

**Comment by ek08** [comment]
3.26.0

**Comment by Lee-W** [comment]
> 3.26.0

Could you please also try with the latest version and see whether it persists? Thanks!

**Comment by ek08** [comment]
I used 4.3.1 and yeah it is working as expected, thanks @Lee-W

**Comment by luis-alm** [comment]
I get the error in versions  > 4.3.0 when my tags are not using PEP 440, I'm using commitizen for my CI in non-python projects using semver.
My config below

Using python 3.12.3 & cz version 4.8.2
Error when running cz bump --get-next
`packaging.version.InvalidVersion: Invalid version: '1.0.48-cicd-release-suffix'`

I see a similar error from cz version 4.4.1

.cz.toml (using semver2)
```toml
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
ignored_tag_formats = ["*"]
version_scheme = "semver2"
version_provider = "scm"
update_changelog_on_bump = true
```

**Comment by Lee-W** [comment]
> I get the error in versions > 4.3.0 when my tags are not using PEP 440, I'm using commitizen for my CI in non-python projects using semver. My config below
> 
> Using python 3.12.3 & cz version 4.8.2 Error when running cz bump --get-next `packaging.version.InvalidVersion: Invalid version: '1.0.48-cicd-release-suffix'`
> 
> I see a similar error from cz version 4.4.1
> 
> .cz.toml (using semver2)
> 
> [tool.commitizen]
> name = "cz_conventional_commits"
> tag_format = "v$version"
> ignored_tag_formats = ["*"]
> version_scheme = "semver2"
> version_provider = "scm"
> update_changelog_on_bump = true

Yes, this is unfortunately a limitation of commitizen as of now https://github.com/commitizen-tools/commitizen/issues/950. Part of the semver is not supported for the time being

**Comment by waterworthd-cim** [comment]
I'm getting issues with dev releases, i.e.

```
task: [cz:bump] uvx --from commitizen cz --no-raise 21 bump --yes --dry-run --check-consistency --changelog --devrelease 20250723101618

bump: version 0.7.0.dev20250722174326 → 0.7.0.dev20250723101618
tag to create: v0.7.0.dev20250723101618

Invalid version tag: 'v0.7.0.dev20250722174326' does not match any configured tag format
Invalid version tag: 'v0.7.0.dev0' does not match any configured tag format
```

If I delete the CHANGELOG.md it works once but then fails the next time. I get the same issue with tags like 0.7.0.dev0

```
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "pep621"
```
