### ISSUE TITLE
Add chore to the list of options of commit types

### ISSUE THREAD

**Issue by danvergara** [commitizen-tools/commitizen#917]
### Description

Sometimes, I end up using other commit types that don't feel right. Some changes are more like a chore than a refactor or an style change.

### Possible Solution

I'd like to have the `chore` commit type listed as an option.

`chore`: (updating grunt tasks etc; no production code change)

### Additional context

This options is listed  on the [Conventional Commits Specifications](https://www.conventionalcommits.org/en/v1.0.0/), so I don't see any problem in adding it.

**Comment by Lee-W** [comment]
Thanks for your feedback! [This](https://commitizen-tools.github.io/commitizen/faq/#why-are-revert-and-chore-valid-types-in-the-check-pattern-of-cz-conventional_commits-but-not-types-we-can-select) is why we choose not to include it, but feel free to make your own version of cz rule
