### ISSUE TITLE
Can you add the commit sha1 in the changelog command?

### ISSUE THREAD

**Issue by gsemet** [commitizen-tools/commitizen#987]
### Description

I would like to be able to customize the changelog template adding the sha1:

```

{% for change in changes %}
{% if change.scope %}
- *{{ change.scope }}*: {{ change.message }} ({{ change.sha1 }})
{% elif change.message %}
- {{ change.message }} ({{ change.sha1 }})
{% endif %}
{% endfor %}
```

Thanks

### Possible Solution

Add the sha1 in the "Change" object. Maybe author as well.

**Comment by noirbizarre** [comment]
Hi 👋🏼 

I created a pull request (#1013) to add this, but given it's not without impact (increase memory usage on changelog generation), it needs to be discussed I think.

Anyway, this is already possible with the following (`changelog_message_builder_hook`](https://commitizen-tools.github.io/commitizen/customization/#custom-changelog-generator)

```python
def changelog_message_builder_hook(
        self, parsed_message: dict, commit: git.GitCommit
    ) -> dict | list | None:
		parsed_message.update(
			sha1=commit.rev,
            author=commit.author,
        	author_email=commit.author_email,
		)
        return parsed_message
```

**Comment by gsemet** [comment]
Hello Thanks !
